// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// UrlsKeeperMock implements mm_getuserurlshandler.UrlsKeeper
type UrlsKeeperMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcGetAllByUser          func(ctx context.Context, userID string) (urls map[string]string, err error)
	funcGetAllByUserOrigin    string
	inspectFuncGetAllByUser   func(ctx context.Context, userID string)
	afterGetAllByUserCounter  uint64
	beforeGetAllByUserCounter uint64
	GetAllByUserMock          mUrlsKeeperMockGetAllByUser
}

// NewUrlsKeeperMock returns a mock for mm_getuserurlshandler.UrlsKeeper
func NewUrlsKeeperMock(t minimock.Tester) *UrlsKeeperMock {
	m := &UrlsKeeperMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.GetAllByUserMock = mUrlsKeeperMockGetAllByUser{mock: m}
	m.GetAllByUserMock.callArgs = []*UrlsKeeperMockGetAllByUserParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mUrlsKeeperMockGetAllByUser struct {
	optional           bool
	mock               *UrlsKeeperMock
	defaultExpectation *UrlsKeeperMockGetAllByUserExpectation
	expectations       []*UrlsKeeperMockGetAllByUserExpectation

	callArgs []*UrlsKeeperMockGetAllByUserParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// UrlsKeeperMockGetAllByUserExpectation specifies expectation struct of the UrlsKeeper.GetAllByUser
type UrlsKeeperMockGetAllByUserExpectation struct {
	mock               *UrlsKeeperMock
	params             *UrlsKeeperMockGetAllByUserParams
	paramPtrs          *UrlsKeeperMockGetAllByUserParamPtrs
	expectationOrigins UrlsKeeperMockGetAllByUserExpectationOrigins
	results            *UrlsKeeperMockGetAllByUserResults
	returnOrigin       string
	Counter            uint64
}

// UrlsKeeperMockGetAllByUserParams contains parameters of the UrlsKeeper.GetAllByUser
type UrlsKeeperMockGetAllByUserParams struct {
	ctx    context.Context
	userID string
}

// UrlsKeeperMockGetAllByUserParamPtrs contains pointers to parameters of the UrlsKeeper.GetAllByUser
type UrlsKeeperMockGetAllByUserParamPtrs struct {
	ctx    *context.Context
	userID *string
}

// UrlsKeeperMockGetAllByUserResults contains results of the UrlsKeeper.GetAllByUser
type UrlsKeeperMockGetAllByUserResults struct {
	urls map[string]string
	err  error
}

// UrlsKeeperMockGetAllByUserOrigins contains origins of expectations of the UrlsKeeper.GetAllByUser
type UrlsKeeperMockGetAllByUserExpectationOrigins struct {
	origin       string
	originCtx    string
	originUserID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetAllByUser *mUrlsKeeperMockGetAllByUser) Optional() *mUrlsKeeperMockGetAllByUser {
	mmGetAllByUser.optional = true
	return mmGetAllByUser
}

// Expect sets up expected params for UrlsKeeper.GetAllByUser
func (mmGetAllByUser *mUrlsKeeperMockGetAllByUser) Expect(ctx context.Context, userID string) *mUrlsKeeperMockGetAllByUser {
	if mmGetAllByUser.mock.funcGetAllByUser != nil {
		mmGetAllByUser.mock.t.Fatalf("UrlsKeeperMock.GetAllByUser mock is already set by Set")
	}

	if mmGetAllByUser.defaultExpectation == nil {
		mmGetAllByUser.defaultExpectation = &UrlsKeeperMockGetAllByUserExpectation{}
	}

	if mmGetAllByUser.defaultExpectation.paramPtrs != nil {
		mmGetAllByUser.mock.t.Fatalf("UrlsKeeperMock.GetAllByUser mock is already set by ExpectParams functions")
	}

	mmGetAllByUser.defaultExpectation.params = &UrlsKeeperMockGetAllByUserParams{ctx, userID}
	mmGetAllByUser.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetAllByUser.expectations {
		if minimock.Equal(e.params, mmGetAllByUser.defaultExpectation.params) {
			mmGetAllByUser.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetAllByUser.defaultExpectation.params)
		}
	}

	return mmGetAllByUser
}

// ExpectCtxParam1 sets up expected param ctx for UrlsKeeper.GetAllByUser
func (mmGetAllByUser *mUrlsKeeperMockGetAllByUser) ExpectCtxParam1(ctx context.Context) *mUrlsKeeperMockGetAllByUser {
	if mmGetAllByUser.mock.funcGetAllByUser != nil {
		mmGetAllByUser.mock.t.Fatalf("UrlsKeeperMock.GetAllByUser mock is already set by Set")
	}

	if mmGetAllByUser.defaultExpectation == nil {
		mmGetAllByUser.defaultExpectation = &UrlsKeeperMockGetAllByUserExpectation{}
	}

	if mmGetAllByUser.defaultExpectation.params != nil {
		mmGetAllByUser.mock.t.Fatalf("UrlsKeeperMock.GetAllByUser mock is already set by Expect")
	}

	if mmGetAllByUser.defaultExpectation.paramPtrs == nil {
		mmGetAllByUser.defaultExpectation.paramPtrs = &UrlsKeeperMockGetAllByUserParamPtrs{}
	}
	mmGetAllByUser.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetAllByUser.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetAllByUser
}

// ExpectUserIDParam2 sets up expected param userID for UrlsKeeper.GetAllByUser
func (mmGetAllByUser *mUrlsKeeperMockGetAllByUser) ExpectUserIDParam2(userID string) *mUrlsKeeperMockGetAllByUser {
	if mmGetAllByUser.mock.funcGetAllByUser != nil {
		mmGetAllByUser.mock.t.Fatalf("UrlsKeeperMock.GetAllByUser mock is already set by Set")
	}

	if mmGetAllByUser.defaultExpectation == nil {
		mmGetAllByUser.defaultExpectation = &UrlsKeeperMockGetAllByUserExpectation{}
	}

	if mmGetAllByUser.defaultExpectation.params != nil {
		mmGetAllByUser.mock.t.Fatalf("UrlsKeeperMock.GetAllByUser mock is already set by Expect")
	}

	if mmGetAllByUser.defaultExpectation.paramPtrs == nil {
		mmGetAllByUser.defaultExpectation.paramPtrs = &UrlsKeeperMockGetAllByUserParamPtrs{}
	}
	mmGetAllByUser.defaultExpectation.paramPtrs.userID = &userID
	mmGetAllByUser.defaultExpectation.expectationOrigins.originUserID = minimock.CallerInfo(1)

	return mmGetAllByUser
}

// Inspect accepts an inspector function that has same arguments as the UrlsKeeper.GetAllByUser
func (mmGetAllByUser *mUrlsKeeperMockGetAllByUser) Inspect(f func(ctx context.Context, userID string)) *mUrlsKeeperMockGetAllByUser {
	if mmGetAllByUser.mock.inspectFuncGetAllByUser != nil {
		mmGetAllByUser.mock.t.Fatalf("Inspect function is already set for UrlsKeeperMock.GetAllByUser")
	}

	mmGetAllByUser.mock.inspectFuncGetAllByUser = f

	return mmGetAllByUser
}

// Return sets up results that will be returned by UrlsKeeper.GetAllByUser
func (mmGetAllByUser *mUrlsKeeperMockGetAllByUser) Return(urls map[string]string, err error) *UrlsKeeperMock {
	if mmGetAllByUser.mock.funcGetAllByUser != nil {
		mmGetAllByUser.mock.t.Fatalf("UrlsKeeperMock.GetAllByUser mock is already set by Set")
	}

	if mmGetAllByUser.defaultExpectation == nil {
		mmGetAllByUser.defaultExpectation = &UrlsKeeperMockGetAllByUserExpectation{mock: mmGetAllByUser.mock}
	}
	mmGetAllByUser.defaultExpectation.results = &UrlsKeeperMockGetAllByUserResults{urls, err}
	mmGetAllByUser.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetAllByUser.mock
}

// Set uses given function f to mock the UrlsKeeper.GetAllByUser method
func (mmGetAllByUser *mUrlsKeeperMockGetAllByUser) Set(f func(ctx context.Context, userID string) (urls map[string]string, err error)) *UrlsKeeperMock {
	if mmGetAllByUser.defaultExpectation != nil {
		mmGetAllByUser.mock.t.Fatalf("Default expectation is already set for the UrlsKeeper.GetAllByUser method")
	}

	if len(mmGetAllByUser.expectations) > 0 {
		mmGetAllByUser.mock.t.Fatalf("Some expectations are already set for the UrlsKeeper.GetAllByUser method")
	}

	mmGetAllByUser.mock.funcGetAllByUser = f
	mmGetAllByUser.mock.funcGetAllByUserOrigin = minimock.CallerInfo(1)
	return mmGetAllByUser.mock
}

// When sets expectation for the UrlsKeeper.GetAllByUser which will trigger the result defined by the following
// Then helper
func (mmGetAllByUser *mUrlsKeeperMockGetAllByUser) When(ctx context.Context, userID string) *UrlsKeeperMockGetAllByUserExpectation {
	if mmGetAllByUser.mock.funcGetAllByUser != nil {
		mmGetAllByUser.mock.t.Fatalf("UrlsKeeperMock.GetAllByUser mock is already set by Set")
	}

	expectation := &UrlsKeeperMockGetAllByUserExpectation{
		mock:               mmGetAllByUser.mock,
		params:             &UrlsKeeperMockGetAllByUserParams{ctx, userID},
		expectationOrigins: UrlsKeeperMockGetAllByUserExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetAllByUser.expectations = append(mmGetAllByUser.expectations, expectation)
	return expectation
}

// Then sets up UrlsKeeper.GetAllByUser return parameters for the expectation previously defined by the When method
func (e *UrlsKeeperMockGetAllByUserExpectation) Then(urls map[string]string, err error) *UrlsKeeperMock {
	e.results = &UrlsKeeperMockGetAllByUserResults{urls, err}
	return e.mock
}

// Times sets number of times UrlsKeeper.GetAllByUser should be invoked
func (mmGetAllByUser *mUrlsKeeperMockGetAllByUser) Times(n uint64) *mUrlsKeeperMockGetAllByUser {
	if n == 0 {
		mmGetAllByUser.mock.t.Fatalf("Times of UrlsKeeperMock.GetAllByUser mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetAllByUser.expectedInvocations, n)
	mmGetAllByUser.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetAllByUser
}

func (mmGetAllByUser *mUrlsKeeperMockGetAllByUser) invocationsDone() bool {
	if len(mmGetAllByUser.expectations) == 0 && mmGetAllByUser.defaultExpectation == nil && mmGetAllByUser.mock.funcGetAllByUser == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetAllByUser.mock.afterGetAllByUserCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetAllByUser.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetAllByUser implements mm_getuserurlshandler.UrlsKeeper
func (mmGetAllByUser *UrlsKeeperMock) GetAllByUser(ctx context.Context, userID string) (urls map[string]string, err error) {
	mm_atomic.AddUint64(&mmGetAllByUser.beforeGetAllByUserCounter, 1)
	defer mm_atomic.AddUint64(&mmGetAllByUser.afterGetAllByUserCounter, 1)

	mmGetAllByUser.t.Helper()

	if mmGetAllByUser.inspectFuncGetAllByUser != nil {
		mmGetAllByUser.inspectFuncGetAllByUser(ctx, userID)
	}

	mm_params := UrlsKeeperMockGetAllByUserParams{ctx, userID}

	// Record call args
	mmGetAllByUser.GetAllByUserMock.mutex.Lock()
	mmGetAllByUser.GetAllByUserMock.callArgs = append(mmGetAllByUser.GetAllByUserMock.callArgs, &mm_params)
	mmGetAllByUser.GetAllByUserMock.mutex.Unlock()

	for _, e := range mmGetAllByUser.GetAllByUserMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.urls, e.results.err
		}
	}

	if mmGetAllByUser.GetAllByUserMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetAllByUser.GetAllByUserMock.defaultExpectation.Counter, 1)
		mm_want := mmGetAllByUser.GetAllByUserMock.defaultExpectation.params
		mm_want_ptrs := mmGetAllByUser.GetAllByUserMock.defaultExpectation.paramPtrs

		mm_got := UrlsKeeperMockGetAllByUserParams{ctx, userID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetAllByUser.t.Errorf("UrlsKeeperMock.GetAllByUser got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetAllByUser.GetAllByUserMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.userID != nil && !minimock.Equal(*mm_want_ptrs.userID, mm_got.userID) {
				mmGetAllByUser.t.Errorf("UrlsKeeperMock.GetAllByUser got unexpected parameter userID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetAllByUser.GetAllByUserMock.defaultExpectation.expectationOrigins.originUserID, *mm_want_ptrs.userID, mm_got.userID, minimock.Diff(*mm_want_ptrs.userID, mm_got.userID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetAllByUser.t.Errorf("UrlsKeeperMock.GetAllByUser got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetAllByUser.GetAllByUserMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetAllByUser.GetAllByUserMock.defaultExpectation.results
		if mm_results == nil {
			mmGetAllByUser.t.Fatal("No results are set for the UrlsKeeperMock.GetAllByUser")
		}
		return (*mm_results).urls, (*mm_results).err
	}
	if mmGetAllByUser.funcGetAllByUser != nil {
		return mmGetAllByUser.funcGetAllByUser(ctx, userID)
	}
	mmGetAllByUser.t.Fatalf("Unexpected call to UrlsKeeperMock.GetAllByUser. %v %v", ctx, userID)
	return
}

// GetAllByUserAfterCounter returns a count of finished UrlsKeeperMock.GetAllByUser invocations
func (mmGetAllByUser *UrlsKeeperMock) GetAllByUserAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetAllByUser.afterGetAllByUserCounter)
}

// GetAllByUserBeforeCounter returns a count of UrlsKeeperMock.GetAllByUser invocations
func (mmGetAllByUser *UrlsKeeperMock) GetAllByUserBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetAllByUser.beforeGetAllByUserCounter)
}

// Calls returns a list of arguments used in each call to UrlsKeeperMock.GetAllByUser.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetAllByUser *mUrlsKeeperMockGetAllByUser) Calls() []*UrlsKeeperMockGetAllByUserParams {
	mmGetAllByUser.mutex.RLock()

	argCopy := make([]*UrlsKeeperMockGetAllByUserParams, len(mmGetAllByUser.callArgs))
	copy(argCopy, mmGetAllByUser.callArgs)

	mmGetAllByUser.mutex.RUnlock()

	return argCopy
}

// MinimockGetAllByUserDone returns true if the count of the GetAllByUser invocations corresponds
// the number of defined expectations
func (m *UrlsKeeperMock) MinimockGetAllByUserDone() bool {
	if m.GetAllByUserMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetAllByUserMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetAllByUserMock.invocationsDone()
}

// MinimockGetAllByUserInspect logs each unmet expectation
func (m *UrlsKeeperMock) MinimockGetAllByUserInspect() {
	for _, e := range m.GetAllByUserMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UrlsKeeperMock.GetAllByUser at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetAllByUserCounter := mm_atomic.LoadUint64(&m.afterGetAllByUserCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetAllByUserMock.defaultExpectation != nil && afterGetAllByUserCounter < 1 {
		if m.GetAllByUserMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to UrlsKeeperMock.GetAllByUser at\n%s", m.GetAllByUserMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to UrlsKeeperMock.GetAllByUser at\n%s with params: %#v", m.GetAllByUserMock.defaultExpectation.expectationOrigins.origin, *m.GetAllByUserMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetAllByUser != nil && afterGetAllByUserCounter < 1 {
		m.t.Errorf("Expected call to UrlsKeeperMock.GetAllByUser at\n%s", m.funcGetAllByUserOrigin)
	}

	if !m.GetAllByUserMock.invocationsDone() && afterGetAllByUserCounter > 0 {
		m.t.Errorf("Expected %d calls to UrlsKeeperMock.GetAllByUser at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetAllByUserMock.expectedInvocations), m.GetAllByUserMock.expectedInvocationsOrigin, afterGetAllByUserCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *UrlsKeeperMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockGetAllByUserInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *UrlsKeeperMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *UrlsKeeperMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockGetAllByUserDone()
}
