// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// RepositoryMock implements mm_statshandler.Repository
type RepositoryMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcGetStats          func(ctx context.Context) (urls int, users int, err error)
	funcGetStatsOrigin    string
	inspectFuncGetStats   func(ctx context.Context)
	afterGetStatsCounter  uint64
	beforeGetStatsCounter uint64
	GetStatsMock          mRepositoryMockGetStats
}

// NewRepositoryMock returns a mock for mm_statshandler.Repository
func NewRepositoryMock(t minimock.Tester) *RepositoryMock {
	m := &RepositoryMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.GetStatsMock = mRepositoryMockGetStats{mock: m}
	m.GetStatsMock.callArgs = []*RepositoryMockGetStatsParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mRepositoryMockGetStats struct {
	optional           bool
	mock               *RepositoryMock
	defaultExpectation *RepositoryMockGetStatsExpectation
	expectations       []*RepositoryMockGetStatsExpectation

	callArgs []*RepositoryMockGetStatsParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// RepositoryMockGetStatsExpectation specifies expectation struct of the Repository.GetStats
type RepositoryMockGetStatsExpectation struct {
	mock               *RepositoryMock
	params             *RepositoryMockGetStatsParams
	paramPtrs          *RepositoryMockGetStatsParamPtrs
	expectationOrigins RepositoryMockGetStatsExpectationOrigins
	results            *RepositoryMockGetStatsResults
	returnOrigin       string
	Counter            uint64
}

// RepositoryMockGetStatsParams contains parameters of the Repository.GetStats
type RepositoryMockGetStatsParams struct {
	ctx context.Context
}

// RepositoryMockGetStatsParamPtrs contains pointers to parameters of the Repository.GetStats
type RepositoryMockGetStatsParamPtrs struct {
	ctx *context.Context
}

// RepositoryMockGetStatsResults contains results of the Repository.GetStats
type RepositoryMockGetStatsResults struct {
	urls  int
	users int
	err   error
}

// RepositoryMockGetStatsOrigins contains origins of expectations of the Repository.GetStats
type RepositoryMockGetStatsExpectationOrigins struct {
	origin    string
	originCtx string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetStats *mRepositoryMockGetStats) Optional() *mRepositoryMockGetStats {
	mmGetStats.optional = true
	return mmGetStats
}

// Expect sets up expected params for Repository.GetStats
func (mmGetStats *mRepositoryMockGetStats) Expect(ctx context.Context) *mRepositoryMockGetStats {
	if mmGetStats.mock.funcGetStats != nil {
		mmGetStats.mock.t.Fatalf("RepositoryMock.GetStats mock is already set by Set")
	}

	if mmGetStats.defaultExpectation == nil {
		mmGetStats.defaultExpectation = &RepositoryMockGetStatsExpectation{}
	}

	if mmGetStats.defaultExpectation.paramPtrs != nil {
		mmGetStats.mock.t.Fatalf("RepositoryMock.GetStats mock is already set by ExpectParams functions")
	}

	mmGetStats.defaultExpectation.params = &RepositoryMockGetStatsParams{ctx}
	mmGetStats.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetStats.expectations {
		if minimock.Equal(e.params, mmGetStats.defaultExpectation.params) {
			mmGetStats.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetStats.defaultExpectation.params)
		}
	}

	return mmGetStats
}

// ExpectCtxParam1 sets up expected param ctx for Repository.GetStats
func (mmGetStats *mRepositoryMockGetStats) ExpectCtxParam1(ctx context.Context) *mRepositoryMockGetStats {
	if mmGetStats.mock.funcGetStats != nil {
		mmGetStats.mock.t.Fatalf("RepositoryMock.GetStats mock is already set by Set")
	}

	if mmGetStats.defaultExpectation == nil {
		mmGetStats.defaultExpectation = &RepositoryMockGetStatsExpectation{}
	}

	if mmGetStats.defaultExpectation.params != nil {
		mmGetStats.mock.t.Fatalf("RepositoryMock.GetStats mock is already set by Expect")
	}

	if mmGetStats.defaultExpectation.paramPtrs == nil {
		mmGetStats.defaultExpectation.paramPtrs = &RepositoryMockGetStatsParamPtrs{}
	}
	mmGetStats.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetStats.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetStats
}

// Inspect accepts an inspector function that has same arguments as the Repository.GetStats
func (mmGetStats *mRepositoryMockGetStats) Inspect(f func(ctx context.Context)) *mRepositoryMockGetStats {
	if mmGetStats.mock.inspectFuncGetStats != nil {
		mmGetStats.mock.t.Fatalf("Inspect function is already set for RepositoryMock.GetStats")
	}

	mmGetStats.mock.inspectFuncGetStats = f

	return mmGetStats
}

// Return sets up results that will be returned by Repository.GetStats
func (mmGetStats *mRepositoryMockGetStats) Return(urls int, users int, err error) *RepositoryMock {
	if mmGetStats.mock.funcGetStats != nil {
		mmGetStats.mock.t.Fatalf("RepositoryMock.GetStats mock is already set by Set")
	}

	if mmGetStats.defaultExpectation == nil {
		mmGetStats.defaultExpectation = &RepositoryMockGetStatsExpectation{mock: mmGetStats.mock}
	}
	mmGetStats.defaultExpectation.results = &RepositoryMockGetStatsResults{urls, users, err}
	mmGetStats.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetStats.mock
}

// Set uses given function f to mock the Repository.GetStats method
func (mmGetStats *mRepositoryMockGetStats) Set(f func(ctx context.Context) (urls int, users int, err error)) *RepositoryMock {
	if mmGetStats.defaultExpectation != nil {
		mmGetStats.mock.t.Fatalf("Default expectation is already set for the Repository.GetStats method")
	}

	if len(mmGetStats.expectations) > 0 {
		mmGetStats.mock.t.Fatalf("Some expectations are already set for the Repository.GetStats method")
	}

	mmGetStats.mock.funcGetStats = f
	mmGetStats.mock.funcGetStatsOrigin = minimock.CallerInfo(1)
	return mmGetStats.mock
}

// When sets expectation for the Repository.GetStats which will trigger the result defined by the following
// Then helper
func (mmGetStats *mRepositoryMockGetStats) When(ctx context.Context) *RepositoryMockGetStatsExpectation {
	if mmGetStats.mock.funcGetStats != nil {
		mmGetStats.mock.t.Fatalf("RepositoryMock.GetStats mock is already set by Set")
	}

	expectation := &RepositoryMockGetStatsExpectation{
		mock:               mmGetStats.mock,
		params:             &RepositoryMockGetStatsParams{ctx},
		expectationOrigins: RepositoryMockGetStatsExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetStats.expectations = append(mmGetStats.expectations, expectation)
	return expectation
}

// Then sets up Repository.GetStats return parameters for the expectation previously defined by the When method
func (e *RepositoryMockGetStatsExpectation) Then(urls int, users int, err error) *RepositoryMock {
	e.results = &RepositoryMockGetStatsResults{urls, users, err}
	return e.mock
}

// Times sets number of times Repository.GetStats should be invoked
func (mmGetStats *mRepositoryMockGetStats) Times(n uint64) *mRepositoryMockGetStats {
	if n == 0 {
		mmGetStats.mock.t.Fatalf("Times of RepositoryMock.GetStats mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetStats.expectedInvocations, n)
	mmGetStats.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetStats
}

func (mmGetStats *mRepositoryMockGetStats) invocationsDone() bool {
	if len(mmGetStats.expectations) == 0 && mmGetStats.defaultExpectation == nil && mmGetStats.mock.funcGetStats == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetStats.mock.afterGetStatsCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetStats.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetStats implements mm_statshandler.Repository
func (mmGetStats *RepositoryMock) GetStats(ctx context.Context) (urls int, users int, err error) {
	mm_atomic.AddUint64(&mmGetStats.beforeGetStatsCounter, 1)
	defer mm_atomic.AddUint64(&mmGetStats.afterGetStatsCounter, 1)

	mmGetStats.t.Helper()

	if mmGetStats.inspectFuncGetStats != nil {
		mmGetStats.inspectFuncGetStats(ctx)
	}

	mm_params := RepositoryMockGetStatsParams{ctx}

	// Record call args
	mmGetStats.GetStatsMock.mutex.Lock()
	mmGetStats.GetStatsMock.callArgs = append(mmGetStats.GetStatsMock.callArgs, &mm_params)
	mmGetStats.GetStatsMock.mutex.Unlock()

	for _, e := range mmGetStats.GetStatsMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.urls, e.results.users, e.results.err
		}
	}

	if mmGetStats.GetStatsMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetStats.GetStatsMock.defaultExpectation.Counter, 1)
		mm_want := mmGetStats.GetStatsMock.defaultExpectation.params
		mm_want_ptrs := mmGetStats.GetStatsMock.defaultExpectation.paramPtrs

		mm_got := RepositoryMockGetStatsParams{ctx}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetStats.t.Errorf("RepositoryMock.GetStats got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetStats.GetStatsMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetStats.t.Errorf("RepositoryMock.GetStats got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetStats.GetStatsMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetStats.GetStatsMock.defaultExpectation.results
		if mm_results == nil {
			mmGetStats.t.Fatal("No results are set for the RepositoryMock.GetStats")
		}
		return (*mm_results).urls, (*mm_results).users, (*mm_results).err
	}
	if mmGetStats.funcGetStats != nil {
		return mmGetStats.funcGetStats(ctx)
	}
	mmGetStats.t.Fatalf("Unexpected call to RepositoryMock.GetStats. %v", ctx)
	return
}

// GetStatsAfterCounter returns a count of finished RepositoryMock.GetStats invocations
func (mmGetStats *RepositoryMock) GetStatsAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetStats.afterGetStatsCounter)
}

// GetStatsBeforeCounter returns a count of RepositoryMock.GetStats invocations
func (mmGetStats *RepositoryMock) GetStatsBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetStats.beforeGetStatsCounter)
}

// Calls returns a list of arguments used in each call to RepositoryMock.GetStats.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetStats *mRepositoryMockGetStats) Calls() []*RepositoryMockGetStatsParams {
	mmGetStats.mutex.RLock()

	argCopy := make([]*RepositoryMockGetStatsParams, len(mmGetStats.callArgs))
	copy(argCopy, mmGetStats.callArgs)

	mmGetStats.mutex.RUnlock()

	return argCopy
}

// MinimockGetStatsDone returns true if the count of the GetStats invocations corresponds
// the number of defined expectations
func (m *RepositoryMock) MinimockGetStatsDone() bool {
	if m.GetStatsMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetStatsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetStatsMock.invocationsDone()
}

// MinimockGetStatsInspect logs each unmet expectation
func (m *RepositoryMock) MinimockGetStatsInspect() {
	for _, e := range m.GetStatsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to RepositoryMock.GetStats at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetStatsCounter := mm_atomic.LoadUint64(&m.afterGetStatsCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetStatsMock.defaultExpectation != nil && afterGetStatsCounter < 1 {
		if m.GetStatsMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to RepositoryMock.GetStats at\n%s", m.GetStatsMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to RepositoryMock.GetStats at\n%s with params: %#v", m.GetStatsMock.defaultExpectation.expectationOrigins.origin, *m.GetStatsMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetStats != nil && afterGetStatsCounter < 1 {
		m.t.Errorf("Expected call to RepositoryMock.GetStats at\n%s", m.funcGetStatsOrigin)
	}

	if !m.GetStatsMock.invocationsDone() && afterGetStatsCounter > 0 {
		m.t.Errorf("Expected %d calls to RepositoryMock.GetStats at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetStatsMock.expectedInvocations), m.GetStatsMock.expectedInvocationsOrigin, afterGetStatsCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *RepositoryMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockGetStatsInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *RepositoryMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *RepositoryMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockGetStatsDone()
}
