// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// AuditServiceMock implements mm_getlongurlhandler.AuditService
type AuditServiceMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcPublishFollowEvent          func(longURL string, userID string)
	funcPublishFollowEventOrigin    string
	inspectFuncPublishFollowEvent   func(longURL string, userID string)
	afterPublishFollowEventCounter  uint64
	beforePublishFollowEventCounter uint64
	PublishFollowEventMock          mAuditServiceMockPublishFollowEvent
}

// NewAuditServiceMock returns a mock for mm_getlongurlhandler.AuditService
func NewAuditServiceMock(t minimock.Tester) *AuditServiceMock {
	m := &AuditServiceMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.PublishFollowEventMock = mAuditServiceMockPublishFollowEvent{mock: m}
	m.PublishFollowEventMock.callArgs = []*AuditServiceMockPublishFollowEventParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mAuditServiceMockPublishFollowEvent struct {
	optional           bool
	mock               *AuditServiceMock
	defaultExpectation *AuditServiceMockPublishFollowEventExpectation
	expectations       []*AuditServiceMockPublishFollowEventExpectation

	callArgs []*AuditServiceMockPublishFollowEventParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// AuditServiceMockPublishFollowEventExpectation specifies expectation struct of the AuditService.PublishFollowEvent
type AuditServiceMockPublishFollowEventExpectation struct {
	mock               *AuditServiceMock
	params             *AuditServiceMockPublishFollowEventParams
	paramPtrs          *AuditServiceMockPublishFollowEventParamPtrs
	expectationOrigins AuditServiceMockPublishFollowEventExpectationOrigins

	returnOrigin string
	Counter      uint64
}

// AuditServiceMockPublishFollowEventParams contains parameters of the AuditService.PublishFollowEvent
type AuditServiceMockPublishFollowEventParams struct {
	longURL string
	userID  string
}

// AuditServiceMockPublishFollowEventParamPtrs contains pointers to parameters of the AuditService.PublishFollowEvent
type AuditServiceMockPublishFollowEventParamPtrs struct {
	longURL *string
	userID  *string
}

// AuditServiceMockPublishFollowEventOrigins contains origins of expectations of the AuditService.PublishFollowEvent
type AuditServiceMockPublishFollowEventExpectationOrigins struct {
	origin        string
	originLongURL string
	originUserID  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmPublishFollowEvent *mAuditServiceMockPublishFollowEvent) Optional() *mAuditServiceMockPublishFollowEvent {
	mmPublishFollowEvent.optional = true
	return mmPublishFollowEvent
}

// Expect sets up expected params for AuditService.PublishFollowEvent
func (mmPublishFollowEvent *mAuditServiceMockPublishFollowEvent) Expect(longURL string, userID string) *mAuditServiceMockPublishFollowEvent {
	if mmPublishFollowEvent.mock.funcPublishFollowEvent != nil {
		mmPublishFollowEvent.mock.t.Fatalf("AuditServiceMock.PublishFollowEvent mock is already set by Set")
	}

	if mmPublishFollowEvent.defaultExpectation == nil {
		mmPublishFollowEvent.defaultExpectation = &AuditServiceMockPublishFollowEventExpectation{}
	}

	if mmPublishFollowEvent.defaultExpectation.paramPtrs != nil {
		mmPublishFollowEvent.mock.t.Fatalf("AuditServiceMock.PublishFollowEvent mock is already set by ExpectParams functions")
	}

	mmPublishFollowEvent.defaultExpectation.params = &AuditServiceMockPublishFollowEventParams{longURL, userID}
	mmPublishFollowEvent.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmPublishFollowEvent.expectations {
		if minimock.Equal(e.params, mmPublishFollowEvent.defaultExpectation.params) {
			mmPublishFollowEvent.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmPublishFollowEvent.defaultExpectation.params)
		}
	}

	return mmPublishFollowEvent
}

// ExpectLongURLParam1 sets up expected param longURL for AuditService.PublishFollowEvent
func (mmPublishFollowEvent *mAuditServiceMockPublishFollowEvent) ExpectLongURLParam1(longURL string) *mAuditServiceMockPublishFollowEvent {
	if mmPublishFollowEvent.mock.funcPublishFollowEvent != nil {
		mmPublishFollowEvent.mock.t.Fatalf("AuditServiceMock.PublishFollowEvent mock is already set by Set")
	}

	if mmPublishFollowEvent.defaultExpectation == nil {
		mmPublishFollowEvent.defaultExpectation = &AuditServiceMockPublishFollowEventExpectation{}
	}

	if mmPublishFollowEvent.defaultExpectation.params != nil {
		mmPublishFollowEvent.mock.t.Fatalf("AuditServiceMock.PublishFollowEvent mock is already set by Expect")
	}

	if mmPublishFollowEvent.defaultExpectation.paramPtrs == nil {
		mmPublishFollowEvent.defaultExpectation.paramPtrs = &AuditServiceMockPublishFollowEventParamPtrs{}
	}
	mmPublishFollowEvent.defaultExpectation.paramPtrs.longURL = &longURL
	mmPublishFollowEvent.defaultExpectation.expectationOrigins.originLongURL = minimock.CallerInfo(1)

	return mmPublishFollowEvent
}

// ExpectUserIDParam2 sets up expected param userID for AuditService.PublishFollowEvent
func (mmPublishFollowEvent *mAuditServiceMockPublishFollowEvent) ExpectUserIDParam2(userID string) *mAuditServiceMockPublishFollowEvent {
	if mmPublishFollowEvent.mock.funcPublishFollowEvent != nil {
		mmPublishFollowEvent.mock.t.Fatalf("AuditServiceMock.PublishFollowEvent mock is already set by Set")
	}

	if mmPublishFollowEvent.defaultExpectation == nil {
		mmPublishFollowEvent.defaultExpectation = &AuditServiceMockPublishFollowEventExpectation{}
	}

	if mmPublishFollowEvent.defaultExpectation.params != nil {
		mmPublishFollowEvent.mock.t.Fatalf("AuditServiceMock.PublishFollowEvent mock is already set by Expect")
	}

	if mmPublishFollowEvent.defaultExpectation.paramPtrs == nil {
		mmPublishFollowEvent.defaultExpectation.paramPtrs = &AuditServiceMockPublishFollowEventParamPtrs{}
	}
	mmPublishFollowEvent.defaultExpectation.paramPtrs.userID = &userID
	mmPublishFollowEvent.defaultExpectation.expectationOrigins.originUserID = minimock.CallerInfo(1)

	return mmPublishFollowEvent
}

// Inspect accepts an inspector function that has same arguments as the AuditService.PublishFollowEvent
func (mmPublishFollowEvent *mAuditServiceMockPublishFollowEvent) Inspect(f func(longURL string, userID string)) *mAuditServiceMockPublishFollowEvent {
	if mmPublishFollowEvent.mock.inspectFuncPublishFollowEvent != nil {
		mmPublishFollowEvent.mock.t.Fatalf("Inspect function is already set for AuditServiceMock.PublishFollowEvent")
	}

	mmPublishFollowEvent.mock.inspectFuncPublishFollowEvent = f

	return mmPublishFollowEvent
}

// Return sets up results that will be returned by AuditService.PublishFollowEvent
func (mmPublishFollowEvent *mAuditServiceMockPublishFollowEvent) Return() *AuditServiceMock {
	if mmPublishFollowEvent.mock.funcPublishFollowEvent != nil {
		mmPublishFollowEvent.mock.t.Fatalf("AuditServiceMock.PublishFollowEvent mock is already set by Set")
	}

	if mmPublishFollowEvent.defaultExpectation == nil {
		mmPublishFollowEvent.defaultExpectation = &AuditServiceMockPublishFollowEventExpectation{mock: mmPublishFollowEvent.mock}
	}

	mmPublishFollowEvent.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmPublishFollowEvent.mock
}

// Set uses given function f to mock the AuditService.PublishFollowEvent method
func (mmPublishFollowEvent *mAuditServiceMockPublishFollowEvent) Set(f func(longURL string, userID string)) *AuditServiceMock {
	if mmPublishFollowEvent.defaultExpectation != nil {
		mmPublishFollowEvent.mock.t.Fatalf("Default expectation is already set for the AuditService.PublishFollowEvent method")
	}

	if len(mmPublishFollowEvent.expectations) > 0 {
		mmPublishFollowEvent.mock.t.Fatalf("Some expectations are already set for the AuditService.PublishFollowEvent method")
	}

	mmPublishFollowEvent.mock.funcPublishFollowEvent = f
	mmPublishFollowEvent.mock.funcPublishFollowEventOrigin = minimock.CallerInfo(1)
	return mmPublishFollowEvent.mock
}

// When sets expectation for the AuditService.PublishFollowEvent which will trigger the result defined by the following
// Then helper
func (mmPublishFollowEvent *mAuditServiceMockPublishFollowEvent) When(longURL string, userID string) *AuditServiceMockPublishFollowEventExpectation {
	if mmPublishFollowEvent.mock.funcPublishFollowEvent != nil {
		mmPublishFollowEvent.mock.t.Fatalf("AuditServiceMock.PublishFollowEvent mock is already set by Set")
	}

	expectation := &AuditServiceMockPublishFollowEventExpectation{
		mock:               mmPublishFollowEvent.mock,
		params:             &AuditServiceMockPublishFollowEventParams{longURL, userID},
		expectationOrigins: AuditServiceMockPublishFollowEventExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmPublishFollowEvent.expectations = append(mmPublishFollowEvent.expectations, expectation)
	return expectation
}

// Then sets up AuditService.PublishFollowEvent return parameters for the expectation previously defined by the When method

func (e *AuditServiceMockPublishFollowEventExpectation) Then() *AuditServiceMock {
	return e.mock
}

// Times sets number of times AuditService.PublishFollowEvent should be invoked
func (mmPublishFollowEvent *mAuditServiceMockPublishFollowEvent) Times(n uint64) *mAuditServiceMockPublishFollowEvent {
	if n == 0 {
		mmPublishFollowEvent.mock.t.Fatalf("Times of AuditServiceMock.PublishFollowEvent mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmPublishFollowEvent.expectedInvocations, n)
	mmPublishFollowEvent.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmPublishFollowEvent
}

func (mmPublishFollowEvent *mAuditServiceMockPublishFollowEvent) invocationsDone() bool {
	if len(mmPublishFollowEvent.expectations) == 0 && mmPublishFollowEvent.defaultExpectation == nil && mmPublishFollowEvent.mock.funcPublishFollowEvent == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmPublishFollowEvent.mock.afterPublishFollowEventCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmPublishFollowEvent.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// PublishFollowEvent implements mm_getlongurlhandler.AuditService
func (mmPublishFollowEvent *AuditServiceMock) PublishFollowEvent(longURL string, userID string) {
	mm_atomic.AddUint64(&mmPublishFollowEvent.beforePublishFollowEventCounter, 1)
	defer mm_atomic.AddUint64(&mmPublishFollowEvent.afterPublishFollowEventCounter, 1)

	mmPublishFollowEvent.t.Helper()

	if mmPublishFollowEvent.inspectFuncPublishFollowEvent != nil {
		mmPublishFollowEvent.inspectFuncPublishFollowEvent(longURL, userID)
	}

	mm_params := AuditServiceMockPublishFollowEventParams{longURL, userID}

	// Record call args
	mmPublishFollowEvent.PublishFollowEventMock.mutex.Lock()
	mmPublishFollowEvent.PublishFollowEventMock.callArgs = append(mmPublishFollowEvent.PublishFollowEventMock.callArgs, &mm_params)
	mmPublishFollowEvent.PublishFollowEventMock.mutex.Unlock()

	for _, e := range mmPublishFollowEvent.PublishFollowEventMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return
		}
	}

	if mmPublishFollowEvent.PublishFollowEventMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmPublishFollowEvent.PublishFollowEventMock.defaultExpectation.Counter, 1)
		mm_want := mmPublishFollowEvent.PublishFollowEventMock.defaultExpectation.params
		mm_want_ptrs := mmPublishFollowEvent.PublishFollowEventMock.defaultExpectation.paramPtrs

		mm_got := AuditServiceMockPublishFollowEventParams{longURL, userID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.longURL != nil && !minimock.Equal(*mm_want_ptrs.longURL, mm_got.longURL) {
				mmPublishFollowEvent.t.Errorf("AuditServiceMock.PublishFollowEvent got unexpected parameter longURL, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmPublishFollowEvent.PublishFollowEventMock.defaultExpectation.expectationOrigins.originLongURL, *mm_want_ptrs.longURL, mm_got.longURL, minimock.Diff(*mm_want_ptrs.longURL, mm_got.longURL))
			}

			if mm_want_ptrs.userID != nil && !minimock.Equal(*mm_want_ptrs.userID, mm_got.userID) {
				mmPublishFollowEvent.t.Errorf("AuditServiceMock.PublishFollowEvent got unexpected parameter userID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmPublishFollowEvent.PublishFollowEventMock.defaultExpectation.expectationOrigins.originUserID, *mm_want_ptrs.userID, mm_got.userID, minimock.Diff(*mm_want_ptrs.userID, mm_got.userID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmPublishFollowEvent.t.Errorf("AuditServiceMock.PublishFollowEvent got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmPublishFollowEvent.PublishFollowEventMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		return

	}
	if mmPublishFollowEvent.funcPublishFollowEvent != nil {
		mmPublishFollowEvent.funcPublishFollowEvent(longURL, userID)
		return
	}
	mmPublishFollowEvent.t.Fatalf("Unexpected call to AuditServiceMock.PublishFollowEvent. %v %v", longURL, userID)

}

// PublishFollowEventAfterCounter returns a count of finished AuditServiceMock.PublishFollowEvent invocations
func (mmPublishFollowEvent *AuditServiceMock) PublishFollowEventAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmPublishFollowEvent.afterPublishFollowEventCounter)
}

// PublishFollowEventBeforeCounter returns a count of AuditServiceMock.PublishFollowEvent invocations
func (mmPublishFollowEvent *AuditServiceMock) PublishFollowEventBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmPublishFollowEvent.beforePublishFollowEventCounter)
}

// Calls returns a list of arguments used in each call to AuditServiceMock.PublishFollowEvent.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmPublishFollowEvent *mAuditServiceMockPublishFollowEvent) Calls() []*AuditServiceMockPublishFollowEventParams {
	mmPublishFollowEvent.mutex.RLock()

	argCopy := make([]*AuditServiceMockPublishFollowEventParams, len(mmPublishFollowEvent.callArgs))
	copy(argCopy, mmPublishFollowEvent.callArgs)

	mmPublishFollowEvent.mutex.RUnlock()

	return argCopy
}

// MinimockPublishFollowEventDone returns true if the count of the PublishFollowEvent invocations corresponds
// the number of defined expectations
func (m *AuditServiceMock) MinimockPublishFollowEventDone() bool {
	if m.PublishFollowEventMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.PublishFollowEventMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.PublishFollowEventMock.invocationsDone()
}

// MinimockPublishFollowEventInspect logs each unmet expectation
func (m *AuditServiceMock) MinimockPublishFollowEventInspect() {
	for _, e := range m.PublishFollowEventMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to AuditServiceMock.PublishFollowEvent at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterPublishFollowEventCounter := mm_atomic.LoadUint64(&m.afterPublishFollowEventCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.PublishFollowEventMock.defaultExpectation != nil && afterPublishFollowEventCounter < 1 {
		if m.PublishFollowEventMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to AuditServiceMock.PublishFollowEvent at\n%s", m.PublishFollowEventMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to AuditServiceMock.PublishFollowEvent at\n%s with params: %#v", m.PublishFollowEventMock.defaultExpectation.expectationOrigins.origin, *m.PublishFollowEventMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcPublishFollowEvent != nil && afterPublishFollowEventCounter < 1 {
		m.t.Errorf("Expected call to AuditServiceMock.PublishFollowEvent at\n%s", m.funcPublishFollowEventOrigin)
	}

	if !m.PublishFollowEventMock.invocationsDone() && afterPublishFollowEventCounter > 0 {
		m.t.Errorf("Expected %d calls to AuditServiceMock.PublishFollowEvent at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.PublishFollowEventMock.expectedInvocations), m.PublishFollowEventMock.expectedInvocationsOrigin, afterPublishFollowEventCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *AuditServiceMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockPublishFollowEventInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *AuditServiceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *AuditServiceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockPublishFollowEventDone()
}
