// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// UrlsKeeperMock implements mm_getlongurlhandler.UrlsKeeper
type UrlsKeeperMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcGet          func(ctx context.Context, shortURL string) (url string, found bool, err error)
	funcGetOrigin    string
	inspectFuncGet   func(ctx context.Context, shortURL string)
	afterGetCounter  uint64
	beforeGetCounter uint64
	GetMock          mUrlsKeeperMockGet
}

// NewUrlsKeeperMock returns a mock for mm_getlongurlhandler.UrlsKeeper
func NewUrlsKeeperMock(t minimock.Tester) *UrlsKeeperMock {
	m := &UrlsKeeperMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.GetMock = mUrlsKeeperMockGet{mock: m}
	m.GetMock.callArgs = []*UrlsKeeperMockGetParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mUrlsKeeperMockGet struct {
	optional           bool
	mock               *UrlsKeeperMock
	defaultExpectation *UrlsKeeperMockGetExpectation
	expectations       []*UrlsKeeperMockGetExpectation

	callArgs []*UrlsKeeperMockGetParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// UrlsKeeperMockGetExpectation specifies expectation struct of the UrlsKeeper.Get
type UrlsKeeperMockGetExpectation struct {
	mock               *UrlsKeeperMock
	params             *UrlsKeeperMockGetParams
	paramPtrs          *UrlsKeeperMockGetParamPtrs
	expectationOrigins UrlsKeeperMockGetExpectationOrigins
	results            *UrlsKeeperMockGetResults
	returnOrigin       string
	Counter            uint64
}

// UrlsKeeperMockGetParams contains parameters of the UrlsKeeper.Get
type UrlsKeeperMockGetParams struct {
	ctx      context.Context
	shortURL string
}

// UrlsKeeperMockGetParamPtrs contains pointers to parameters of the UrlsKeeper.Get
type UrlsKeeperMockGetParamPtrs struct {
	ctx      *context.Context
	shortURL *string
}

// UrlsKeeperMockGetResults contains results of the UrlsKeeper.Get
type UrlsKeeperMockGetResults struct {
	url   string
	found bool
	err   error
}

// UrlsKeeperMockGetOrigins contains origins of expectations of the UrlsKeeper.Get
type UrlsKeeperMockGetExpectationOrigins struct {
	origin         string
	originCtx      string
	originShortURL string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGet *mUrlsKeeperMockGet) Optional() *mUrlsKeeperMockGet {
	mmGet.optional = true
	return mmGet
}

// Expect sets up expected params for UrlsKeeper.Get
func (mmGet *mUrlsKeeperMockGet) Expect(ctx context.Context, shortURL string) *mUrlsKeeperMockGet {
	if mmGet.mock.funcGet != nil {
		mmGet.mock.t.Fatalf("UrlsKeeperMock.Get mock is already set by Set")
	}

	if mmGet.defaultExpectation == nil {
		mmGet.defaultExpectation = &UrlsKeeperMockGetExpectation{}
	}

	if mmGet.defaultExpectation.paramPtrs != nil {
		mmGet.mock.t.Fatalf("UrlsKeeperMock.Get mock is already set by ExpectParams functions")
	}

	mmGet.defaultExpectation.params = &UrlsKeeperMockGetParams{ctx, shortURL}
	mmGet.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGet.expectations {
		if minimock.Equal(e.params, mmGet.defaultExpectation.params) {
			mmGet.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGet.defaultExpectation.params)
		}
	}

	return mmGet
}

// ExpectCtxParam1 sets up expected param ctx for UrlsKeeper.Get
func (mmGet *mUrlsKeeperMockGet) ExpectCtxParam1(ctx context.Context) *mUrlsKeeperMockGet {
	if mmGet.mock.funcGet != nil {
		mmGet.mock.t.Fatalf("UrlsKeeperMock.Get mock is already set by Set")
	}

	if mmGet.defaultExpectation == nil {
		mmGet.defaultExpectation = &UrlsKeeperMockGetExpectation{}
	}

	if mmGet.defaultExpectation.params != nil {
		mmGet.mock.t.Fatalf("UrlsKeeperMock.Get mock is already set by Expect")
	}

	if mmGet.defaultExpectation.paramPtrs == nil {
		mmGet.defaultExpectation.paramPtrs = &UrlsKeeperMockGetParamPtrs{}
	}
	mmGet.defaultExpectation.paramPtrs.ctx = &ctx
	mmGet.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGet
}

// ExpectShortURLParam2 sets up expected param shortURL for UrlsKeeper.Get
func (mmGet *mUrlsKeeperMockGet) ExpectShortURLParam2(shortURL string) *mUrlsKeeperMockGet {
	if mmGet.mock.funcGet != nil {
		mmGet.mock.t.Fatalf("UrlsKeeperMock.Get mock is already set by Set")
	}

	if mmGet.defaultExpectation == nil {
		mmGet.defaultExpectation = &UrlsKeeperMockGetExpectation{}
	}

	if mmGet.defaultExpectation.params != nil {
		mmGet.mock.t.Fatalf("UrlsKeeperMock.Get mock is already set by Expect")
	}

	if mmGet.defaultExpectation.paramPtrs == nil {
		mmGet.defaultExpectation.paramPtrs = &UrlsKeeperMockGetParamPtrs{}
	}
	mmGet.defaultExpectation.paramPtrs.shortURL = &shortURL
	mmGet.defaultExpectation.expectationOrigins.originShortURL = minimock.CallerInfo(1)

	return mmGet
}

// Inspect accepts an inspector function that has same arguments as the UrlsKeeper.Get
func (mmGet *mUrlsKeeperMockGet) Inspect(f func(ctx context.Context, shortURL string)) *mUrlsKeeperMockGet {
	if mmGet.mock.inspectFuncGet != nil {
		mmGet.mock.t.Fatalf("Inspect function is already set for UrlsKeeperMock.Get")
	}

	mmGet.mock.inspectFuncGet = f

	return mmGet
}

// Return sets up results that will be returned by UrlsKeeper.Get
func (mmGet *mUrlsKeeperMockGet) Return(url string, found bool, err error) *UrlsKeeperMock {
	if mmGet.mock.funcGet != nil {
		mmGet.mock.t.Fatalf("UrlsKeeperMock.Get mock is already set by Set")
	}

	if mmGet.defaultExpectation == nil {
		mmGet.defaultExpectation = &UrlsKeeperMockGetExpectation{mock: mmGet.mock}
	}
	mmGet.defaultExpectation.results = &UrlsKeeperMockGetResults{url, found, err}
	mmGet.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGet.mock
}

// Set uses given function f to mock the UrlsKeeper.Get method
func (mmGet *mUrlsKeeperMockGet) Set(f func(ctx context.Context, shortURL string) (url string, found bool, err error)) *UrlsKeeperMock {
	if mmGet.defaultExpectation != nil {
		mmGet.mock.t.Fatalf("Default expectation is already set for the UrlsKeeper.Get method")
	}

	if len(mmGet.expectations) > 0 {
		mmGet.mock.t.Fatalf("Some expectations are already set for the UrlsKeeper.Get method")
	}

	mmGet.mock.funcGet = f
	mmGet.mock.funcGetOrigin = minimock.CallerInfo(1)
	return mmGet.mock
}

// When sets expectation for the UrlsKeeper.Get which will trigger the result defined by the following
// Then helper
func (mmGet *mUrlsKeeperMockGet) When(ctx context.Context, shortURL string) *UrlsKeeperMockGetExpectation {
	if mmGet.mock.funcGet != nil {
		mmGet.mock.t.Fatalf("UrlsKeeperMock.Get mock is already set by Set")
	}

	expectation := &UrlsKeeperMockGetExpectation{
		mock:               mmGet.mock,
		params:             &UrlsKeeperMockGetParams{ctx, shortURL},
		expectationOrigins: UrlsKeeperMockGetExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGet.expectations = append(mmGet.expectations, expectation)
	return expectation
}

// Then sets up UrlsKeeper.Get return parameters for the expectation previously defined by the When method
func (e *UrlsKeeperMockGetExpectation) Then(url string, found bool, err error) *UrlsKeeperMock {
	e.results = &UrlsKeeperMockGetResults{url, found, err}
	return e.mock
}

// Times sets number of times UrlsKeeper.Get should be invoked
func (mmGet *mUrlsKeeperMockGet) Times(n uint64) *mUrlsKeeperMockGet {
	if n == 0 {
		mmGet.mock.t.Fatalf("Times of UrlsKeeperMock.Get mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGet.expectedInvocations, n)
	mmGet.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGet
}

func (mmGet *mUrlsKeeperMockGet) invocationsDone() bool {
	if len(mmGet.expectations) == 0 && mmGet.defaultExpectation == nil && mmGet.mock.funcGet == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGet.mock.afterGetCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGet.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Get implements mm_getlongurlhandler.UrlsKeeper
func (mmGet *UrlsKeeperMock) Get(ctx context.Context, shortURL string) (url string, found bool, err error) {
	mm_atomic.AddUint64(&mmGet.beforeGetCounter, 1)
	defer mm_atomic.AddUint64(&mmGet.afterGetCounter, 1)

	mmGet.t.Helper()

	if mmGet.inspectFuncGet != nil {
		mmGet.inspectFuncGet(ctx, shortURL)
	}

	mm_params := UrlsKeeperMockGetParams{ctx, shortURL}

	// Record call args
	mmGet.GetMock.mutex.Lock()
	mmGet.GetMock.callArgs = append(mmGet.GetMock.callArgs, &mm_params)
	mmGet.GetMock.mutex.Unlock()

	for _, e := range mmGet.GetMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.url, e.results.found, e.results.err
		}
	}

	if mmGet.GetMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGet.GetMock.defaultExpectation.Counter, 1)
		mm_want := mmGet.GetMock.defaultExpectation.params
		mm_want_ptrs := mmGet.GetMock.defaultExpectation.paramPtrs

		mm_got := UrlsKeeperMockGetParams{ctx, shortURL}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGet.t.Errorf("UrlsKeeperMock.Get got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGet.GetMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.shortURL != nil && !minimock.Equal(*mm_want_ptrs.shortURL, mm_got.shortURL) {
				mmGet.t.Errorf("UrlsKeeperMock.Get got unexpected parameter shortURL, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGet.GetMock.defaultExpectation.expectationOrigins.originShortURL, *mm_want_ptrs.shortURL, mm_got.shortURL, minimock.Diff(*mm_want_ptrs.shortURL, mm_got.shortURL))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGet.t.Errorf("UrlsKeeperMock.Get got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGet.GetMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGet.GetMock.defaultExpectation.results
		if mm_results == nil {
			mmGet.t.Fatal("No results are set for the UrlsKeeperMock.Get")
		}
		return (*mm_results).url, (*mm_results).found, (*mm_results).err
	}
	if mmGet.funcGet != nil {
		return mmGet.funcGet(ctx, shortURL)
	}
	mmGet.t.Fatalf("Unexpected call to UrlsKeeperMock.Get. %v %v", ctx, shortURL)
	return
}

// GetAfterCounter returns a count of finished UrlsKeeperMock.Get invocations
func (mmGet *UrlsKeeperMock) GetAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGet.afterGetCounter)
}

// GetBeforeCounter returns a count of UrlsKeeperMock.Get invocations
func (mmGet *UrlsKeeperMock) GetBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGet.beforeGetCounter)
}

// Calls returns a list of arguments used in each call to UrlsKeeperMock.Get.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGet *mUrlsKeeperMockGet) Calls() []*UrlsKeeperMockGetParams {
	mmGet.mutex.RLock()

	argCopy := make([]*UrlsKeeperMockGetParams, len(mmGet.callArgs))
	copy(argCopy, mmGet.callArgs)

	mmGet.mutex.RUnlock()

	return argCopy
}

// MinimockGetDone returns true if the count of the Get invocations corresponds
// the number of defined expectations
func (m *UrlsKeeperMock) MinimockGetDone() bool {
	if m.GetMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetMock.invocationsDone()
}

// MinimockGetInspect logs each unmet expectation
func (m *UrlsKeeperMock) MinimockGetInspect() {
	for _, e := range m.GetMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UrlsKeeperMock.Get at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetCounter := mm_atomic.LoadUint64(&m.afterGetCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetMock.defaultExpectation != nil && afterGetCounter < 1 {
		if m.GetMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to UrlsKeeperMock.Get at\n%s", m.GetMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to UrlsKeeperMock.Get at\n%s with params: %#v", m.GetMock.defaultExpectation.expectationOrigins.origin, *m.GetMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGet != nil && afterGetCounter < 1 {
		m.t.Errorf("Expected call to UrlsKeeperMock.Get at\n%s", m.funcGetOrigin)
	}

	if !m.GetMock.invocationsDone() && afterGetCounter > 0 {
		m.t.Errorf("Expected %d calls to UrlsKeeperMock.Get at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetMock.expectedInvocations), m.GetMock.expectedInvocationsOrigin, afterGetCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *UrlsKeeperMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockGetInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *UrlsKeeperMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *UrlsKeeperMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockGetDone()
}
