package main

import (
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"log"
	"os"
	"strings"

	"golang.org/x/tools/go/packages"
)

const (
	outputFilename      = "reset.gen.go"
	fileContentHeadTmpl = `
// Code generated by go generate; DO NOT EDIT.
// This file was generated by reset-gen

package %s

%s`
)

func main() {
	fmt.Println("reset-gen: Handling...")

	cfg := &packages.Config{Mode: packages.LoadSyntax}
	pkgs, err := packages.Load(cfg, "./...")
	if err != nil {
		log.Fatal(err)
	}

	for _, pkg := range pkgs {
		if pkg.Name == "mocks" {
			continue
		}

		funcs := make([]string, 0)
		for _, goFile := range pkg.GoFiles {
			if isNeedIgnore(goFile) {
				continue
			}

			fns, err := generateResetForStructs(goFile)
			if err != nil {
				fmt.Println("handle file:", goFile)
				fmt.Println("  generate reset failed:", err.Error())
				continue
			}

			funcs = append(funcs, fns...)
		}

		if len(funcs) > 0 {
			dst := fmt.Sprintf("%s/%s", pkg.Dir, outputFilename)
			content := fmt.Sprintf(fileContentHeadTmpl, pkg.Name, strings.Join(funcs, "\n"))

			bufFmt, err := format.Source([]byte(content))
			if err != nil {
				fmt.Println("handle content:", content)
				fmt.Println("  format content failed:", err.Error())
				continue
			}

			err = os.WriteFile(dst, bufFmt, 0o644)
			if err != nil {
				fmt.Println("write file:", dst)
				fmt.Println("  write file failed:", err.Error())
				continue
			}

			fmt.Println("generated file:", dst)
		}
	}

	fmt.Println("reset-gen: Handling... Done")
}

func isNeedIgnore(file string) bool {
	return strings.Contains(file, "mocks") ||
		strings.HasSuffix(file, "_test.go") ||
		strings.HasSuffix(file, ".gen.go")
}

func generateResetForStructs(src string) ([]string, error) {
	fset := token.NewFileSet()

	f, err := parser.ParseFile(fset, src, nil, parser.ParseComments)
	if err != nil {
		return nil, err
	}

	var gd *ast.GenDecl
	var ok bool

	funcs := make([]string, 0)

	for _, d := range f.Decls {
		if gd, ok = d.(*ast.GenDecl); !ok || gd.Tok != token.TYPE || gd.Doc == nil {
			continue
		}

		isNeedGenerate := false

		for _, d := range gd.Doc.List {
			if strings.HasPrefix(d.Text, "// generate:reset") {
				isNeedGenerate = true
				break
			}
		}

		if !isNeedGenerate {
			continue
		}

		// итерируемся по всем полям в структуре
		for _, s := range gd.Specs {
			var ts *ast.TypeSpec
			if ts, ok = s.(*ast.TypeSpec); !ok {
				continue
			}

			structName := ts.Name.Name

			var st *ast.StructType
			if st, ok = ts.Type.(*ast.StructType); !ok {
				continue
			}

			resetFields := handleStructFields(st)

			resetFunc := fmt.Sprintf(`func (s *%s) Reset() {%s}`, structName, strings.Join(resetFields, "\n"))
			funcs = append(funcs, resetFunc)
		}
	}

	return funcs, nil
}

func handleStructFields(st *ast.StructType) []string {
	resetFields := make([]string, 0)

	for _, f := range st.Fields.List {
		if len(f.Names) == 0 {
			continue
		}

		fieldName := f.Names[0].Name

		var resetRow string

		switch tp := f.Type.(type) {
		case *ast.Ident:
			if tp.Obj == nil {
				resetRow = fmt.Sprintf(`{ var def %s; s.%s = def }`, tp.Name, fieldName)
			} else {
				resetRow = callStructResetMethod(f, fieldName)
			}
		case *ast.StarExpr:
			if inerType, ok := tp.X.(*ast.Ident); ok {
				if inerType.Obj == nil {
					resetRow = fmt.Sprintf(`{ var def %s; s.%s = &def }`, inerType.Name, fieldName)
				} else {
					resetRow = callStructResetMethod(f, fieldName)
				}
			}
		case *ast.MapType:
			resetRow = fmt.Sprintf(`clear(s.%s)`, fieldName)
		case *ast.ArrayType:
			resetRow = fmt.Sprintf(`s.%s = s.%s[:0]`, fieldName, fieldName)
		}

		if resetRow != "" {
			resetFields = append(resetFields, resetRow)
		}
	}

	return resetFields
}

func callStructResetMethod(field *ast.Field, fieldName string) string {
	resetRow := ""
	isNeedCallResetFn := false
	ast.Inspect(field, func(n ast.Node) bool {
		if fd, ok := n.(*ast.FuncDecl); ok && fd.Name.Name == "Reset" {
			isNeedCallResetFn = true
			return false
		}

		return true
	})

	if !isNeedCallResetFn {
		resetRow = fmt.Sprintf(`s.%s.Reset()`, fieldName)
	}

	return resetRow
}
