// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// GeneratorMock implements mm_shorter.Generator
type GeneratorMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcGenerateShortID          func(url string) (s1 string)
	funcGenerateShortIDOrigin    string
	inspectFuncGenerateShortID   func(url string)
	afterGenerateShortIDCounter  uint64
	beforeGenerateShortIDCounter uint64
	GenerateShortIDMock          mGeneratorMockGenerateShortID
}

// NewGeneratorMock returns a mock for mm_shorter.Generator
func NewGeneratorMock(t minimock.Tester) *GeneratorMock {
	m := &GeneratorMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.GenerateShortIDMock = mGeneratorMockGenerateShortID{mock: m}
	m.GenerateShortIDMock.callArgs = []*GeneratorMockGenerateShortIDParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mGeneratorMockGenerateShortID struct {
	optional           bool
	mock               *GeneratorMock
	defaultExpectation *GeneratorMockGenerateShortIDExpectation
	expectations       []*GeneratorMockGenerateShortIDExpectation

	callArgs []*GeneratorMockGenerateShortIDParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// GeneratorMockGenerateShortIDExpectation specifies expectation struct of the Generator.GenerateShortID
type GeneratorMockGenerateShortIDExpectation struct {
	mock               *GeneratorMock
	params             *GeneratorMockGenerateShortIDParams
	paramPtrs          *GeneratorMockGenerateShortIDParamPtrs
	expectationOrigins GeneratorMockGenerateShortIDExpectationOrigins
	results            *GeneratorMockGenerateShortIDResults
	returnOrigin       string
	Counter            uint64
}

// GeneratorMockGenerateShortIDParams contains parameters of the Generator.GenerateShortID
type GeneratorMockGenerateShortIDParams struct {
	url string
}

// GeneratorMockGenerateShortIDParamPtrs contains pointers to parameters of the Generator.GenerateShortID
type GeneratorMockGenerateShortIDParamPtrs struct {
	url *string
}

// GeneratorMockGenerateShortIDResults contains results of the Generator.GenerateShortID
type GeneratorMockGenerateShortIDResults struct {
	s1 string
}

// GeneratorMockGenerateShortIDOrigins contains origins of expectations of the Generator.GenerateShortID
type GeneratorMockGenerateShortIDExpectationOrigins struct {
	origin    string
	originUrl string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGenerateShortID *mGeneratorMockGenerateShortID) Optional() *mGeneratorMockGenerateShortID {
	mmGenerateShortID.optional = true
	return mmGenerateShortID
}

// Expect sets up expected params for Generator.GenerateShortID
func (mmGenerateShortID *mGeneratorMockGenerateShortID) Expect(url string) *mGeneratorMockGenerateShortID {
	if mmGenerateShortID.mock.funcGenerateShortID != nil {
		mmGenerateShortID.mock.t.Fatalf("GeneratorMock.GenerateShortID mock is already set by Set")
	}

	if mmGenerateShortID.defaultExpectation == nil {
		mmGenerateShortID.defaultExpectation = &GeneratorMockGenerateShortIDExpectation{}
	}

	if mmGenerateShortID.defaultExpectation.paramPtrs != nil {
		mmGenerateShortID.mock.t.Fatalf("GeneratorMock.GenerateShortID mock is already set by ExpectParams functions")
	}

	mmGenerateShortID.defaultExpectation.params = &GeneratorMockGenerateShortIDParams{url}
	mmGenerateShortID.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGenerateShortID.expectations {
		if minimock.Equal(e.params, mmGenerateShortID.defaultExpectation.params) {
			mmGenerateShortID.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGenerateShortID.defaultExpectation.params)
		}
	}

	return mmGenerateShortID
}

// ExpectUrlParam1 sets up expected param url for Generator.GenerateShortID
func (mmGenerateShortID *mGeneratorMockGenerateShortID) ExpectUrlParam1(url string) *mGeneratorMockGenerateShortID {
	if mmGenerateShortID.mock.funcGenerateShortID != nil {
		mmGenerateShortID.mock.t.Fatalf("GeneratorMock.GenerateShortID mock is already set by Set")
	}

	if mmGenerateShortID.defaultExpectation == nil {
		mmGenerateShortID.defaultExpectation = &GeneratorMockGenerateShortIDExpectation{}
	}

	if mmGenerateShortID.defaultExpectation.params != nil {
		mmGenerateShortID.mock.t.Fatalf("GeneratorMock.GenerateShortID mock is already set by Expect")
	}

	if mmGenerateShortID.defaultExpectation.paramPtrs == nil {
		mmGenerateShortID.defaultExpectation.paramPtrs = &GeneratorMockGenerateShortIDParamPtrs{}
	}
	mmGenerateShortID.defaultExpectation.paramPtrs.url = &url
	mmGenerateShortID.defaultExpectation.expectationOrigins.originUrl = minimock.CallerInfo(1)

	return mmGenerateShortID
}

// Inspect accepts an inspector function that has same arguments as the Generator.GenerateShortID
func (mmGenerateShortID *mGeneratorMockGenerateShortID) Inspect(f func(url string)) *mGeneratorMockGenerateShortID {
	if mmGenerateShortID.mock.inspectFuncGenerateShortID != nil {
		mmGenerateShortID.mock.t.Fatalf("Inspect function is already set for GeneratorMock.GenerateShortID")
	}

	mmGenerateShortID.mock.inspectFuncGenerateShortID = f

	return mmGenerateShortID
}

// Return sets up results that will be returned by Generator.GenerateShortID
func (mmGenerateShortID *mGeneratorMockGenerateShortID) Return(s1 string) *GeneratorMock {
	if mmGenerateShortID.mock.funcGenerateShortID != nil {
		mmGenerateShortID.mock.t.Fatalf("GeneratorMock.GenerateShortID mock is already set by Set")
	}

	if mmGenerateShortID.defaultExpectation == nil {
		mmGenerateShortID.defaultExpectation = &GeneratorMockGenerateShortIDExpectation{mock: mmGenerateShortID.mock}
	}
	mmGenerateShortID.defaultExpectation.results = &GeneratorMockGenerateShortIDResults{s1}
	mmGenerateShortID.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGenerateShortID.mock
}

// Set uses given function f to mock the Generator.GenerateShortID method
func (mmGenerateShortID *mGeneratorMockGenerateShortID) Set(f func(url string) (s1 string)) *GeneratorMock {
	if mmGenerateShortID.defaultExpectation != nil {
		mmGenerateShortID.mock.t.Fatalf("Default expectation is already set for the Generator.GenerateShortID method")
	}

	if len(mmGenerateShortID.expectations) > 0 {
		mmGenerateShortID.mock.t.Fatalf("Some expectations are already set for the Generator.GenerateShortID method")
	}

	mmGenerateShortID.mock.funcGenerateShortID = f
	mmGenerateShortID.mock.funcGenerateShortIDOrigin = minimock.CallerInfo(1)
	return mmGenerateShortID.mock
}

// When sets expectation for the Generator.GenerateShortID which will trigger the result defined by the following
// Then helper
func (mmGenerateShortID *mGeneratorMockGenerateShortID) When(url string) *GeneratorMockGenerateShortIDExpectation {
	if mmGenerateShortID.mock.funcGenerateShortID != nil {
		mmGenerateShortID.mock.t.Fatalf("GeneratorMock.GenerateShortID mock is already set by Set")
	}

	expectation := &GeneratorMockGenerateShortIDExpectation{
		mock:               mmGenerateShortID.mock,
		params:             &GeneratorMockGenerateShortIDParams{url},
		expectationOrigins: GeneratorMockGenerateShortIDExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGenerateShortID.expectations = append(mmGenerateShortID.expectations, expectation)
	return expectation
}

// Then sets up Generator.GenerateShortID return parameters for the expectation previously defined by the When method
func (e *GeneratorMockGenerateShortIDExpectation) Then(s1 string) *GeneratorMock {
	e.results = &GeneratorMockGenerateShortIDResults{s1}
	return e.mock
}

// Times sets number of times Generator.GenerateShortID should be invoked
func (mmGenerateShortID *mGeneratorMockGenerateShortID) Times(n uint64) *mGeneratorMockGenerateShortID {
	if n == 0 {
		mmGenerateShortID.mock.t.Fatalf("Times of GeneratorMock.GenerateShortID mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGenerateShortID.expectedInvocations, n)
	mmGenerateShortID.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGenerateShortID
}

func (mmGenerateShortID *mGeneratorMockGenerateShortID) invocationsDone() bool {
	if len(mmGenerateShortID.expectations) == 0 && mmGenerateShortID.defaultExpectation == nil && mmGenerateShortID.mock.funcGenerateShortID == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGenerateShortID.mock.afterGenerateShortIDCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGenerateShortID.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GenerateShortID implements mm_shorter.Generator
func (mmGenerateShortID *GeneratorMock) GenerateShortID(url string) (s1 string) {
	mm_atomic.AddUint64(&mmGenerateShortID.beforeGenerateShortIDCounter, 1)
	defer mm_atomic.AddUint64(&mmGenerateShortID.afterGenerateShortIDCounter, 1)

	mmGenerateShortID.t.Helper()

	if mmGenerateShortID.inspectFuncGenerateShortID != nil {
		mmGenerateShortID.inspectFuncGenerateShortID(url)
	}

	mm_params := GeneratorMockGenerateShortIDParams{url}

	// Record call args
	mmGenerateShortID.GenerateShortIDMock.mutex.Lock()
	mmGenerateShortID.GenerateShortIDMock.callArgs = append(mmGenerateShortID.GenerateShortIDMock.callArgs, &mm_params)
	mmGenerateShortID.GenerateShortIDMock.mutex.Unlock()

	for _, e := range mmGenerateShortID.GenerateShortIDMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.s1
		}
	}

	if mmGenerateShortID.GenerateShortIDMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGenerateShortID.GenerateShortIDMock.defaultExpectation.Counter, 1)
		mm_want := mmGenerateShortID.GenerateShortIDMock.defaultExpectation.params
		mm_want_ptrs := mmGenerateShortID.GenerateShortIDMock.defaultExpectation.paramPtrs

		mm_got := GeneratorMockGenerateShortIDParams{url}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.url != nil && !minimock.Equal(*mm_want_ptrs.url, mm_got.url) {
				mmGenerateShortID.t.Errorf("GeneratorMock.GenerateShortID got unexpected parameter url, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGenerateShortID.GenerateShortIDMock.defaultExpectation.expectationOrigins.originUrl, *mm_want_ptrs.url, mm_got.url, minimock.Diff(*mm_want_ptrs.url, mm_got.url))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGenerateShortID.t.Errorf("GeneratorMock.GenerateShortID got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGenerateShortID.GenerateShortIDMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGenerateShortID.GenerateShortIDMock.defaultExpectation.results
		if mm_results == nil {
			mmGenerateShortID.t.Fatal("No results are set for the GeneratorMock.GenerateShortID")
		}
		return (*mm_results).s1
	}
	if mmGenerateShortID.funcGenerateShortID != nil {
		return mmGenerateShortID.funcGenerateShortID(url)
	}
	mmGenerateShortID.t.Fatalf("Unexpected call to GeneratorMock.GenerateShortID. %v", url)
	return
}

// GenerateShortIDAfterCounter returns a count of finished GeneratorMock.GenerateShortID invocations
func (mmGenerateShortID *GeneratorMock) GenerateShortIDAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGenerateShortID.afterGenerateShortIDCounter)
}

// GenerateShortIDBeforeCounter returns a count of GeneratorMock.GenerateShortID invocations
func (mmGenerateShortID *GeneratorMock) GenerateShortIDBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGenerateShortID.beforeGenerateShortIDCounter)
}

// Calls returns a list of arguments used in each call to GeneratorMock.GenerateShortID.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGenerateShortID *mGeneratorMockGenerateShortID) Calls() []*GeneratorMockGenerateShortIDParams {
	mmGenerateShortID.mutex.RLock()

	argCopy := make([]*GeneratorMockGenerateShortIDParams, len(mmGenerateShortID.callArgs))
	copy(argCopy, mmGenerateShortID.callArgs)

	mmGenerateShortID.mutex.RUnlock()

	return argCopy
}

// MinimockGenerateShortIDDone returns true if the count of the GenerateShortID invocations corresponds
// the number of defined expectations
func (m *GeneratorMock) MinimockGenerateShortIDDone() bool {
	if m.GenerateShortIDMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GenerateShortIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GenerateShortIDMock.invocationsDone()
}

// MinimockGenerateShortIDInspect logs each unmet expectation
func (m *GeneratorMock) MinimockGenerateShortIDInspect() {
	for _, e := range m.GenerateShortIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to GeneratorMock.GenerateShortID at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGenerateShortIDCounter := mm_atomic.LoadUint64(&m.afterGenerateShortIDCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GenerateShortIDMock.defaultExpectation != nil && afterGenerateShortIDCounter < 1 {
		if m.GenerateShortIDMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to GeneratorMock.GenerateShortID at\n%s", m.GenerateShortIDMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to GeneratorMock.GenerateShortID at\n%s with params: %#v", m.GenerateShortIDMock.defaultExpectation.expectationOrigins.origin, *m.GenerateShortIDMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGenerateShortID != nil && afterGenerateShortIDCounter < 1 {
		m.t.Errorf("Expected call to GeneratorMock.GenerateShortID at\n%s", m.funcGenerateShortIDOrigin)
	}

	if !m.GenerateShortIDMock.invocationsDone() && afterGenerateShortIDCounter > 0 {
		m.t.Errorf("Expected %d calls to GeneratorMock.GenerateShortID at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GenerateShortIDMock.expectedInvocations), m.GenerateShortIDMock.expectedInvocationsOrigin, afterGenerateShortIDCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *GeneratorMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockGenerateShortIDInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *GeneratorMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *GeneratorMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockGenerateShortIDDone()
}
