// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// URLValidatorMock implements mm_shorter.URLValidator
type URLValidatorMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcValidate          func(url string) (b1 bool)
	funcValidateOrigin    string
	inspectFuncValidate   func(url string)
	afterValidateCounter  uint64
	beforeValidateCounter uint64
	ValidateMock          mURLValidatorMockValidate
}

// NewURLValidatorMock returns a mock for mm_shorter.URLValidator
func NewURLValidatorMock(t minimock.Tester) *URLValidatorMock {
	m := &URLValidatorMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.ValidateMock = mURLValidatorMockValidate{mock: m}
	m.ValidateMock.callArgs = []*URLValidatorMockValidateParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mURLValidatorMockValidate struct {
	optional           bool
	mock               *URLValidatorMock
	defaultExpectation *URLValidatorMockValidateExpectation
	expectations       []*URLValidatorMockValidateExpectation

	callArgs []*URLValidatorMockValidateParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// URLValidatorMockValidateExpectation specifies expectation struct of the URLValidator.Validate
type URLValidatorMockValidateExpectation struct {
	mock               *URLValidatorMock
	params             *URLValidatorMockValidateParams
	paramPtrs          *URLValidatorMockValidateParamPtrs
	expectationOrigins URLValidatorMockValidateExpectationOrigins
	results            *URLValidatorMockValidateResults
	returnOrigin       string
	Counter            uint64
}

// URLValidatorMockValidateParams contains parameters of the URLValidator.Validate
type URLValidatorMockValidateParams struct {
	url string
}

// URLValidatorMockValidateParamPtrs contains pointers to parameters of the URLValidator.Validate
type URLValidatorMockValidateParamPtrs struct {
	url *string
}

// URLValidatorMockValidateResults contains results of the URLValidator.Validate
type URLValidatorMockValidateResults struct {
	b1 bool
}

// URLValidatorMockValidateOrigins contains origins of expectations of the URLValidator.Validate
type URLValidatorMockValidateExpectationOrigins struct {
	origin    string
	originUrl string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmValidate *mURLValidatorMockValidate) Optional() *mURLValidatorMockValidate {
	mmValidate.optional = true
	return mmValidate
}

// Expect sets up expected params for URLValidator.Validate
func (mmValidate *mURLValidatorMockValidate) Expect(url string) *mURLValidatorMockValidate {
	if mmValidate.mock.funcValidate != nil {
		mmValidate.mock.t.Fatalf("URLValidatorMock.Validate mock is already set by Set")
	}

	if mmValidate.defaultExpectation == nil {
		mmValidate.defaultExpectation = &URLValidatorMockValidateExpectation{}
	}

	if mmValidate.defaultExpectation.paramPtrs != nil {
		mmValidate.mock.t.Fatalf("URLValidatorMock.Validate mock is already set by ExpectParams functions")
	}

	mmValidate.defaultExpectation.params = &URLValidatorMockValidateParams{url}
	mmValidate.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmValidate.expectations {
		if minimock.Equal(e.params, mmValidate.defaultExpectation.params) {
			mmValidate.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmValidate.defaultExpectation.params)
		}
	}

	return mmValidate
}

// ExpectUrlParam1 sets up expected param url for URLValidator.Validate
func (mmValidate *mURLValidatorMockValidate) ExpectUrlParam1(url string) *mURLValidatorMockValidate {
	if mmValidate.mock.funcValidate != nil {
		mmValidate.mock.t.Fatalf("URLValidatorMock.Validate mock is already set by Set")
	}

	if mmValidate.defaultExpectation == nil {
		mmValidate.defaultExpectation = &URLValidatorMockValidateExpectation{}
	}

	if mmValidate.defaultExpectation.params != nil {
		mmValidate.mock.t.Fatalf("URLValidatorMock.Validate mock is already set by Expect")
	}

	if mmValidate.defaultExpectation.paramPtrs == nil {
		mmValidate.defaultExpectation.paramPtrs = &URLValidatorMockValidateParamPtrs{}
	}
	mmValidate.defaultExpectation.paramPtrs.url = &url
	mmValidate.defaultExpectation.expectationOrigins.originUrl = minimock.CallerInfo(1)

	return mmValidate
}

// Inspect accepts an inspector function that has same arguments as the URLValidator.Validate
func (mmValidate *mURLValidatorMockValidate) Inspect(f func(url string)) *mURLValidatorMockValidate {
	if mmValidate.mock.inspectFuncValidate != nil {
		mmValidate.mock.t.Fatalf("Inspect function is already set for URLValidatorMock.Validate")
	}

	mmValidate.mock.inspectFuncValidate = f

	return mmValidate
}

// Return sets up results that will be returned by URLValidator.Validate
func (mmValidate *mURLValidatorMockValidate) Return(b1 bool) *URLValidatorMock {
	if mmValidate.mock.funcValidate != nil {
		mmValidate.mock.t.Fatalf("URLValidatorMock.Validate mock is already set by Set")
	}

	if mmValidate.defaultExpectation == nil {
		mmValidate.defaultExpectation = &URLValidatorMockValidateExpectation{mock: mmValidate.mock}
	}
	mmValidate.defaultExpectation.results = &URLValidatorMockValidateResults{b1}
	mmValidate.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmValidate.mock
}

// Set uses given function f to mock the URLValidator.Validate method
func (mmValidate *mURLValidatorMockValidate) Set(f func(url string) (b1 bool)) *URLValidatorMock {
	if mmValidate.defaultExpectation != nil {
		mmValidate.mock.t.Fatalf("Default expectation is already set for the URLValidator.Validate method")
	}

	if len(mmValidate.expectations) > 0 {
		mmValidate.mock.t.Fatalf("Some expectations are already set for the URLValidator.Validate method")
	}

	mmValidate.mock.funcValidate = f
	mmValidate.mock.funcValidateOrigin = minimock.CallerInfo(1)
	return mmValidate.mock
}

// When sets expectation for the URLValidator.Validate which will trigger the result defined by the following
// Then helper
func (mmValidate *mURLValidatorMockValidate) When(url string) *URLValidatorMockValidateExpectation {
	if mmValidate.mock.funcValidate != nil {
		mmValidate.mock.t.Fatalf("URLValidatorMock.Validate mock is already set by Set")
	}

	expectation := &URLValidatorMockValidateExpectation{
		mock:               mmValidate.mock,
		params:             &URLValidatorMockValidateParams{url},
		expectationOrigins: URLValidatorMockValidateExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmValidate.expectations = append(mmValidate.expectations, expectation)
	return expectation
}

// Then sets up URLValidator.Validate return parameters for the expectation previously defined by the When method
func (e *URLValidatorMockValidateExpectation) Then(b1 bool) *URLValidatorMock {
	e.results = &URLValidatorMockValidateResults{b1}
	return e.mock
}

// Times sets number of times URLValidator.Validate should be invoked
func (mmValidate *mURLValidatorMockValidate) Times(n uint64) *mURLValidatorMockValidate {
	if n == 0 {
		mmValidate.mock.t.Fatalf("Times of URLValidatorMock.Validate mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmValidate.expectedInvocations, n)
	mmValidate.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmValidate
}

func (mmValidate *mURLValidatorMockValidate) invocationsDone() bool {
	if len(mmValidate.expectations) == 0 && mmValidate.defaultExpectation == nil && mmValidate.mock.funcValidate == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmValidate.mock.afterValidateCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmValidate.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Validate implements mm_shorter.URLValidator
func (mmValidate *URLValidatorMock) Validate(url string) (b1 bool) {
	mm_atomic.AddUint64(&mmValidate.beforeValidateCounter, 1)
	defer mm_atomic.AddUint64(&mmValidate.afterValidateCounter, 1)

	mmValidate.t.Helper()

	if mmValidate.inspectFuncValidate != nil {
		mmValidate.inspectFuncValidate(url)
	}

	mm_params := URLValidatorMockValidateParams{url}

	// Record call args
	mmValidate.ValidateMock.mutex.Lock()
	mmValidate.ValidateMock.callArgs = append(mmValidate.ValidateMock.callArgs, &mm_params)
	mmValidate.ValidateMock.mutex.Unlock()

	for _, e := range mmValidate.ValidateMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.b1
		}
	}

	if mmValidate.ValidateMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmValidate.ValidateMock.defaultExpectation.Counter, 1)
		mm_want := mmValidate.ValidateMock.defaultExpectation.params
		mm_want_ptrs := mmValidate.ValidateMock.defaultExpectation.paramPtrs

		mm_got := URLValidatorMockValidateParams{url}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.url != nil && !minimock.Equal(*mm_want_ptrs.url, mm_got.url) {
				mmValidate.t.Errorf("URLValidatorMock.Validate got unexpected parameter url, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmValidate.ValidateMock.defaultExpectation.expectationOrigins.originUrl, *mm_want_ptrs.url, mm_got.url, minimock.Diff(*mm_want_ptrs.url, mm_got.url))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmValidate.t.Errorf("URLValidatorMock.Validate got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmValidate.ValidateMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmValidate.ValidateMock.defaultExpectation.results
		if mm_results == nil {
			mmValidate.t.Fatal("No results are set for the URLValidatorMock.Validate")
		}
		return (*mm_results).b1
	}
	if mmValidate.funcValidate != nil {
		return mmValidate.funcValidate(url)
	}
	mmValidate.t.Fatalf("Unexpected call to URLValidatorMock.Validate. %v", url)
	return
}

// ValidateAfterCounter returns a count of finished URLValidatorMock.Validate invocations
func (mmValidate *URLValidatorMock) ValidateAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmValidate.afterValidateCounter)
}

// ValidateBeforeCounter returns a count of URLValidatorMock.Validate invocations
func (mmValidate *URLValidatorMock) ValidateBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmValidate.beforeValidateCounter)
}

// Calls returns a list of arguments used in each call to URLValidatorMock.Validate.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmValidate *mURLValidatorMockValidate) Calls() []*URLValidatorMockValidateParams {
	mmValidate.mutex.RLock()

	argCopy := make([]*URLValidatorMockValidateParams, len(mmValidate.callArgs))
	copy(argCopy, mmValidate.callArgs)

	mmValidate.mutex.RUnlock()

	return argCopy
}

// MinimockValidateDone returns true if the count of the Validate invocations corresponds
// the number of defined expectations
func (m *URLValidatorMock) MinimockValidateDone() bool {
	if m.ValidateMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.ValidateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.ValidateMock.invocationsDone()
}

// MinimockValidateInspect logs each unmet expectation
func (m *URLValidatorMock) MinimockValidateInspect() {
	for _, e := range m.ValidateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to URLValidatorMock.Validate at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterValidateCounter := mm_atomic.LoadUint64(&m.afterValidateCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.ValidateMock.defaultExpectation != nil && afterValidateCounter < 1 {
		if m.ValidateMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to URLValidatorMock.Validate at\n%s", m.ValidateMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to URLValidatorMock.Validate at\n%s with params: %#v", m.ValidateMock.defaultExpectation.expectationOrigins.origin, *m.ValidateMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcValidate != nil && afterValidateCounter < 1 {
		m.t.Errorf("Expected call to URLValidatorMock.Validate at\n%s", m.funcValidateOrigin)
	}

	if !m.ValidateMock.invocationsDone() && afterValidateCounter > 0 {
		m.t.Errorf("Expected %d calls to URLValidatorMock.Validate at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.ValidateMock.expectedInvocations), m.ValidateMock.expectedInvocationsOrigin, afterValidateCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *URLValidatorMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockValidateInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *URLValidatorMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *URLValidatorMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockValidateDone()
}
