// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// UrlsKeeperMock implements mm_shorter.UrlsKeeper
type UrlsKeeperMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcGetShortURL          func(ctx context.Context, originalURL string) (s1 string, err error)
	funcGetShortURLOrigin    string
	inspectFuncGetShortURL   func(ctx context.Context, originalURL string)
	afterGetShortURLCounter  uint64
	beforeGetShortURLCounter uint64
	GetShortURLMock          mUrlsKeeperMockGetShortURL

	funcSave          func(ctx context.Context, originalURL string, shortURL string, userID string) (err error)
	funcSaveOrigin    string
	inspectFuncSave   func(ctx context.Context, originalURL string, shortURL string, userID string)
	afterSaveCounter  uint64
	beforeSaveCounter uint64
	SaveMock          mUrlsKeeperMockSave

	funcSaveBatch          func(ctx context.Context, urls map[string]string, userID string) (err error)
	funcSaveBatchOrigin    string
	inspectFuncSaveBatch   func(ctx context.Context, urls map[string]string, userID string)
	afterSaveBatchCounter  uint64
	beforeSaveBatchCounter uint64
	SaveBatchMock          mUrlsKeeperMockSaveBatch
}

// NewUrlsKeeperMock returns a mock for mm_shorter.UrlsKeeper
func NewUrlsKeeperMock(t minimock.Tester) *UrlsKeeperMock {
	m := &UrlsKeeperMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.GetShortURLMock = mUrlsKeeperMockGetShortURL{mock: m}
	m.GetShortURLMock.callArgs = []*UrlsKeeperMockGetShortURLParams{}

	m.SaveMock = mUrlsKeeperMockSave{mock: m}
	m.SaveMock.callArgs = []*UrlsKeeperMockSaveParams{}

	m.SaveBatchMock = mUrlsKeeperMockSaveBatch{mock: m}
	m.SaveBatchMock.callArgs = []*UrlsKeeperMockSaveBatchParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mUrlsKeeperMockGetShortURL struct {
	optional           bool
	mock               *UrlsKeeperMock
	defaultExpectation *UrlsKeeperMockGetShortURLExpectation
	expectations       []*UrlsKeeperMockGetShortURLExpectation

	callArgs []*UrlsKeeperMockGetShortURLParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// UrlsKeeperMockGetShortURLExpectation specifies expectation struct of the UrlsKeeper.GetShortURL
type UrlsKeeperMockGetShortURLExpectation struct {
	mock               *UrlsKeeperMock
	params             *UrlsKeeperMockGetShortURLParams
	paramPtrs          *UrlsKeeperMockGetShortURLParamPtrs
	expectationOrigins UrlsKeeperMockGetShortURLExpectationOrigins
	results            *UrlsKeeperMockGetShortURLResults
	returnOrigin       string
	Counter            uint64
}

// UrlsKeeperMockGetShortURLParams contains parameters of the UrlsKeeper.GetShortURL
type UrlsKeeperMockGetShortURLParams struct {
	ctx         context.Context
	originalURL string
}

// UrlsKeeperMockGetShortURLParamPtrs contains pointers to parameters of the UrlsKeeper.GetShortURL
type UrlsKeeperMockGetShortURLParamPtrs struct {
	ctx         *context.Context
	originalURL *string
}

// UrlsKeeperMockGetShortURLResults contains results of the UrlsKeeper.GetShortURL
type UrlsKeeperMockGetShortURLResults struct {
	s1  string
	err error
}

// UrlsKeeperMockGetShortURLOrigins contains origins of expectations of the UrlsKeeper.GetShortURL
type UrlsKeeperMockGetShortURLExpectationOrigins struct {
	origin            string
	originCtx         string
	originOriginalURL string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetShortURL *mUrlsKeeperMockGetShortURL) Optional() *mUrlsKeeperMockGetShortURL {
	mmGetShortURL.optional = true
	return mmGetShortURL
}

// Expect sets up expected params for UrlsKeeper.GetShortURL
func (mmGetShortURL *mUrlsKeeperMockGetShortURL) Expect(ctx context.Context, originalURL string) *mUrlsKeeperMockGetShortURL {
	if mmGetShortURL.mock.funcGetShortURL != nil {
		mmGetShortURL.mock.t.Fatalf("UrlsKeeperMock.GetShortURL mock is already set by Set")
	}

	if mmGetShortURL.defaultExpectation == nil {
		mmGetShortURL.defaultExpectation = &UrlsKeeperMockGetShortURLExpectation{}
	}

	if mmGetShortURL.defaultExpectation.paramPtrs != nil {
		mmGetShortURL.mock.t.Fatalf("UrlsKeeperMock.GetShortURL mock is already set by ExpectParams functions")
	}

	mmGetShortURL.defaultExpectation.params = &UrlsKeeperMockGetShortURLParams{ctx, originalURL}
	mmGetShortURL.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetShortURL.expectations {
		if minimock.Equal(e.params, mmGetShortURL.defaultExpectation.params) {
			mmGetShortURL.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetShortURL.defaultExpectation.params)
		}
	}

	return mmGetShortURL
}

// ExpectCtxParam1 sets up expected param ctx for UrlsKeeper.GetShortURL
func (mmGetShortURL *mUrlsKeeperMockGetShortURL) ExpectCtxParam1(ctx context.Context) *mUrlsKeeperMockGetShortURL {
	if mmGetShortURL.mock.funcGetShortURL != nil {
		mmGetShortURL.mock.t.Fatalf("UrlsKeeperMock.GetShortURL mock is already set by Set")
	}

	if mmGetShortURL.defaultExpectation == nil {
		mmGetShortURL.defaultExpectation = &UrlsKeeperMockGetShortURLExpectation{}
	}

	if mmGetShortURL.defaultExpectation.params != nil {
		mmGetShortURL.mock.t.Fatalf("UrlsKeeperMock.GetShortURL mock is already set by Expect")
	}

	if mmGetShortURL.defaultExpectation.paramPtrs == nil {
		mmGetShortURL.defaultExpectation.paramPtrs = &UrlsKeeperMockGetShortURLParamPtrs{}
	}
	mmGetShortURL.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetShortURL.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetShortURL
}

// ExpectOriginalURLParam2 sets up expected param originalURL for UrlsKeeper.GetShortURL
func (mmGetShortURL *mUrlsKeeperMockGetShortURL) ExpectOriginalURLParam2(originalURL string) *mUrlsKeeperMockGetShortURL {
	if mmGetShortURL.mock.funcGetShortURL != nil {
		mmGetShortURL.mock.t.Fatalf("UrlsKeeperMock.GetShortURL mock is already set by Set")
	}

	if mmGetShortURL.defaultExpectation == nil {
		mmGetShortURL.defaultExpectation = &UrlsKeeperMockGetShortURLExpectation{}
	}

	if mmGetShortURL.defaultExpectation.params != nil {
		mmGetShortURL.mock.t.Fatalf("UrlsKeeperMock.GetShortURL mock is already set by Expect")
	}

	if mmGetShortURL.defaultExpectation.paramPtrs == nil {
		mmGetShortURL.defaultExpectation.paramPtrs = &UrlsKeeperMockGetShortURLParamPtrs{}
	}
	mmGetShortURL.defaultExpectation.paramPtrs.originalURL = &originalURL
	mmGetShortURL.defaultExpectation.expectationOrigins.originOriginalURL = minimock.CallerInfo(1)

	return mmGetShortURL
}

// Inspect accepts an inspector function that has same arguments as the UrlsKeeper.GetShortURL
func (mmGetShortURL *mUrlsKeeperMockGetShortURL) Inspect(f func(ctx context.Context, originalURL string)) *mUrlsKeeperMockGetShortURL {
	if mmGetShortURL.mock.inspectFuncGetShortURL != nil {
		mmGetShortURL.mock.t.Fatalf("Inspect function is already set for UrlsKeeperMock.GetShortURL")
	}

	mmGetShortURL.mock.inspectFuncGetShortURL = f

	return mmGetShortURL
}

// Return sets up results that will be returned by UrlsKeeper.GetShortURL
func (mmGetShortURL *mUrlsKeeperMockGetShortURL) Return(s1 string, err error) *UrlsKeeperMock {
	if mmGetShortURL.mock.funcGetShortURL != nil {
		mmGetShortURL.mock.t.Fatalf("UrlsKeeperMock.GetShortURL mock is already set by Set")
	}

	if mmGetShortURL.defaultExpectation == nil {
		mmGetShortURL.defaultExpectation = &UrlsKeeperMockGetShortURLExpectation{mock: mmGetShortURL.mock}
	}
	mmGetShortURL.defaultExpectation.results = &UrlsKeeperMockGetShortURLResults{s1, err}
	mmGetShortURL.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetShortURL.mock
}

// Set uses given function f to mock the UrlsKeeper.GetShortURL method
func (mmGetShortURL *mUrlsKeeperMockGetShortURL) Set(f func(ctx context.Context, originalURL string) (s1 string, err error)) *UrlsKeeperMock {
	if mmGetShortURL.defaultExpectation != nil {
		mmGetShortURL.mock.t.Fatalf("Default expectation is already set for the UrlsKeeper.GetShortURL method")
	}

	if len(mmGetShortURL.expectations) > 0 {
		mmGetShortURL.mock.t.Fatalf("Some expectations are already set for the UrlsKeeper.GetShortURL method")
	}

	mmGetShortURL.mock.funcGetShortURL = f
	mmGetShortURL.mock.funcGetShortURLOrigin = minimock.CallerInfo(1)
	return mmGetShortURL.mock
}

// When sets expectation for the UrlsKeeper.GetShortURL which will trigger the result defined by the following
// Then helper
func (mmGetShortURL *mUrlsKeeperMockGetShortURL) When(ctx context.Context, originalURL string) *UrlsKeeperMockGetShortURLExpectation {
	if mmGetShortURL.mock.funcGetShortURL != nil {
		mmGetShortURL.mock.t.Fatalf("UrlsKeeperMock.GetShortURL mock is already set by Set")
	}

	expectation := &UrlsKeeperMockGetShortURLExpectation{
		mock:               mmGetShortURL.mock,
		params:             &UrlsKeeperMockGetShortURLParams{ctx, originalURL},
		expectationOrigins: UrlsKeeperMockGetShortURLExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetShortURL.expectations = append(mmGetShortURL.expectations, expectation)
	return expectation
}

// Then sets up UrlsKeeper.GetShortURL return parameters for the expectation previously defined by the When method
func (e *UrlsKeeperMockGetShortURLExpectation) Then(s1 string, err error) *UrlsKeeperMock {
	e.results = &UrlsKeeperMockGetShortURLResults{s1, err}
	return e.mock
}

// Times sets number of times UrlsKeeper.GetShortURL should be invoked
func (mmGetShortURL *mUrlsKeeperMockGetShortURL) Times(n uint64) *mUrlsKeeperMockGetShortURL {
	if n == 0 {
		mmGetShortURL.mock.t.Fatalf("Times of UrlsKeeperMock.GetShortURL mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetShortURL.expectedInvocations, n)
	mmGetShortURL.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetShortURL
}

func (mmGetShortURL *mUrlsKeeperMockGetShortURL) invocationsDone() bool {
	if len(mmGetShortURL.expectations) == 0 && mmGetShortURL.defaultExpectation == nil && mmGetShortURL.mock.funcGetShortURL == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetShortURL.mock.afterGetShortURLCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetShortURL.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetShortURL implements mm_shorter.UrlsKeeper
func (mmGetShortURL *UrlsKeeperMock) GetShortURL(ctx context.Context, originalURL string) (s1 string, err error) {
	mm_atomic.AddUint64(&mmGetShortURL.beforeGetShortURLCounter, 1)
	defer mm_atomic.AddUint64(&mmGetShortURL.afterGetShortURLCounter, 1)

	mmGetShortURL.t.Helper()

	if mmGetShortURL.inspectFuncGetShortURL != nil {
		mmGetShortURL.inspectFuncGetShortURL(ctx, originalURL)
	}

	mm_params := UrlsKeeperMockGetShortURLParams{ctx, originalURL}

	// Record call args
	mmGetShortURL.GetShortURLMock.mutex.Lock()
	mmGetShortURL.GetShortURLMock.callArgs = append(mmGetShortURL.GetShortURLMock.callArgs, &mm_params)
	mmGetShortURL.GetShortURLMock.mutex.Unlock()

	for _, e := range mmGetShortURL.GetShortURLMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.s1, e.results.err
		}
	}

	if mmGetShortURL.GetShortURLMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetShortURL.GetShortURLMock.defaultExpectation.Counter, 1)
		mm_want := mmGetShortURL.GetShortURLMock.defaultExpectation.params
		mm_want_ptrs := mmGetShortURL.GetShortURLMock.defaultExpectation.paramPtrs

		mm_got := UrlsKeeperMockGetShortURLParams{ctx, originalURL}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetShortURL.t.Errorf("UrlsKeeperMock.GetShortURL got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetShortURL.GetShortURLMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.originalURL != nil && !minimock.Equal(*mm_want_ptrs.originalURL, mm_got.originalURL) {
				mmGetShortURL.t.Errorf("UrlsKeeperMock.GetShortURL got unexpected parameter originalURL, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetShortURL.GetShortURLMock.defaultExpectation.expectationOrigins.originOriginalURL, *mm_want_ptrs.originalURL, mm_got.originalURL, minimock.Diff(*mm_want_ptrs.originalURL, mm_got.originalURL))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetShortURL.t.Errorf("UrlsKeeperMock.GetShortURL got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetShortURL.GetShortURLMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetShortURL.GetShortURLMock.defaultExpectation.results
		if mm_results == nil {
			mmGetShortURL.t.Fatal("No results are set for the UrlsKeeperMock.GetShortURL")
		}
		return (*mm_results).s1, (*mm_results).err
	}
	if mmGetShortURL.funcGetShortURL != nil {
		return mmGetShortURL.funcGetShortURL(ctx, originalURL)
	}
	mmGetShortURL.t.Fatalf("Unexpected call to UrlsKeeperMock.GetShortURL. %v %v", ctx, originalURL)
	return
}

// GetShortURLAfterCounter returns a count of finished UrlsKeeperMock.GetShortURL invocations
func (mmGetShortURL *UrlsKeeperMock) GetShortURLAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetShortURL.afterGetShortURLCounter)
}

// GetShortURLBeforeCounter returns a count of UrlsKeeperMock.GetShortURL invocations
func (mmGetShortURL *UrlsKeeperMock) GetShortURLBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetShortURL.beforeGetShortURLCounter)
}

// Calls returns a list of arguments used in each call to UrlsKeeperMock.GetShortURL.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetShortURL *mUrlsKeeperMockGetShortURL) Calls() []*UrlsKeeperMockGetShortURLParams {
	mmGetShortURL.mutex.RLock()

	argCopy := make([]*UrlsKeeperMockGetShortURLParams, len(mmGetShortURL.callArgs))
	copy(argCopy, mmGetShortURL.callArgs)

	mmGetShortURL.mutex.RUnlock()

	return argCopy
}

// MinimockGetShortURLDone returns true if the count of the GetShortURL invocations corresponds
// the number of defined expectations
func (m *UrlsKeeperMock) MinimockGetShortURLDone() bool {
	if m.GetShortURLMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetShortURLMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetShortURLMock.invocationsDone()
}

// MinimockGetShortURLInspect logs each unmet expectation
func (m *UrlsKeeperMock) MinimockGetShortURLInspect() {
	for _, e := range m.GetShortURLMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UrlsKeeperMock.GetShortURL at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetShortURLCounter := mm_atomic.LoadUint64(&m.afterGetShortURLCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetShortURLMock.defaultExpectation != nil && afterGetShortURLCounter < 1 {
		if m.GetShortURLMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to UrlsKeeperMock.GetShortURL at\n%s", m.GetShortURLMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to UrlsKeeperMock.GetShortURL at\n%s with params: %#v", m.GetShortURLMock.defaultExpectation.expectationOrigins.origin, *m.GetShortURLMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetShortURL != nil && afterGetShortURLCounter < 1 {
		m.t.Errorf("Expected call to UrlsKeeperMock.GetShortURL at\n%s", m.funcGetShortURLOrigin)
	}

	if !m.GetShortURLMock.invocationsDone() && afterGetShortURLCounter > 0 {
		m.t.Errorf("Expected %d calls to UrlsKeeperMock.GetShortURL at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetShortURLMock.expectedInvocations), m.GetShortURLMock.expectedInvocationsOrigin, afterGetShortURLCounter)
	}
}

type mUrlsKeeperMockSave struct {
	optional           bool
	mock               *UrlsKeeperMock
	defaultExpectation *UrlsKeeperMockSaveExpectation
	expectations       []*UrlsKeeperMockSaveExpectation

	callArgs []*UrlsKeeperMockSaveParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// UrlsKeeperMockSaveExpectation specifies expectation struct of the UrlsKeeper.Save
type UrlsKeeperMockSaveExpectation struct {
	mock               *UrlsKeeperMock
	params             *UrlsKeeperMockSaveParams
	paramPtrs          *UrlsKeeperMockSaveParamPtrs
	expectationOrigins UrlsKeeperMockSaveExpectationOrigins
	results            *UrlsKeeperMockSaveResults
	returnOrigin       string
	Counter            uint64
}

// UrlsKeeperMockSaveParams contains parameters of the UrlsKeeper.Save
type UrlsKeeperMockSaveParams struct {
	ctx         context.Context
	originalURL string
	shortURL    string
	userID      string
}

// UrlsKeeperMockSaveParamPtrs contains pointers to parameters of the UrlsKeeper.Save
type UrlsKeeperMockSaveParamPtrs struct {
	ctx         *context.Context
	originalURL *string
	shortURL    *string
	userID      *string
}

// UrlsKeeperMockSaveResults contains results of the UrlsKeeper.Save
type UrlsKeeperMockSaveResults struct {
	err error
}

// UrlsKeeperMockSaveOrigins contains origins of expectations of the UrlsKeeper.Save
type UrlsKeeperMockSaveExpectationOrigins struct {
	origin            string
	originCtx         string
	originOriginalURL string
	originShortURL    string
	originUserID      string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmSave *mUrlsKeeperMockSave) Optional() *mUrlsKeeperMockSave {
	mmSave.optional = true
	return mmSave
}

// Expect sets up expected params for UrlsKeeper.Save
func (mmSave *mUrlsKeeperMockSave) Expect(ctx context.Context, originalURL string, shortURL string, userID string) *mUrlsKeeperMockSave {
	if mmSave.mock.funcSave != nil {
		mmSave.mock.t.Fatalf("UrlsKeeperMock.Save mock is already set by Set")
	}

	if mmSave.defaultExpectation == nil {
		mmSave.defaultExpectation = &UrlsKeeperMockSaveExpectation{}
	}

	if mmSave.defaultExpectation.paramPtrs != nil {
		mmSave.mock.t.Fatalf("UrlsKeeperMock.Save mock is already set by ExpectParams functions")
	}

	mmSave.defaultExpectation.params = &UrlsKeeperMockSaveParams{ctx, originalURL, shortURL, userID}
	mmSave.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmSave.expectations {
		if minimock.Equal(e.params, mmSave.defaultExpectation.params) {
			mmSave.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSave.defaultExpectation.params)
		}
	}

	return mmSave
}

// ExpectCtxParam1 sets up expected param ctx for UrlsKeeper.Save
func (mmSave *mUrlsKeeperMockSave) ExpectCtxParam1(ctx context.Context) *mUrlsKeeperMockSave {
	if mmSave.mock.funcSave != nil {
		mmSave.mock.t.Fatalf("UrlsKeeperMock.Save mock is already set by Set")
	}

	if mmSave.defaultExpectation == nil {
		mmSave.defaultExpectation = &UrlsKeeperMockSaveExpectation{}
	}

	if mmSave.defaultExpectation.params != nil {
		mmSave.mock.t.Fatalf("UrlsKeeperMock.Save mock is already set by Expect")
	}

	if mmSave.defaultExpectation.paramPtrs == nil {
		mmSave.defaultExpectation.paramPtrs = &UrlsKeeperMockSaveParamPtrs{}
	}
	mmSave.defaultExpectation.paramPtrs.ctx = &ctx
	mmSave.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmSave
}

// ExpectOriginalURLParam2 sets up expected param originalURL for UrlsKeeper.Save
func (mmSave *mUrlsKeeperMockSave) ExpectOriginalURLParam2(originalURL string) *mUrlsKeeperMockSave {
	if mmSave.mock.funcSave != nil {
		mmSave.mock.t.Fatalf("UrlsKeeperMock.Save mock is already set by Set")
	}

	if mmSave.defaultExpectation == nil {
		mmSave.defaultExpectation = &UrlsKeeperMockSaveExpectation{}
	}

	if mmSave.defaultExpectation.params != nil {
		mmSave.mock.t.Fatalf("UrlsKeeperMock.Save mock is already set by Expect")
	}

	if mmSave.defaultExpectation.paramPtrs == nil {
		mmSave.defaultExpectation.paramPtrs = &UrlsKeeperMockSaveParamPtrs{}
	}
	mmSave.defaultExpectation.paramPtrs.originalURL = &originalURL
	mmSave.defaultExpectation.expectationOrigins.originOriginalURL = minimock.CallerInfo(1)

	return mmSave
}

// ExpectShortURLParam3 sets up expected param shortURL for UrlsKeeper.Save
func (mmSave *mUrlsKeeperMockSave) ExpectShortURLParam3(shortURL string) *mUrlsKeeperMockSave {
	if mmSave.mock.funcSave != nil {
		mmSave.mock.t.Fatalf("UrlsKeeperMock.Save mock is already set by Set")
	}

	if mmSave.defaultExpectation == nil {
		mmSave.defaultExpectation = &UrlsKeeperMockSaveExpectation{}
	}

	if mmSave.defaultExpectation.params != nil {
		mmSave.mock.t.Fatalf("UrlsKeeperMock.Save mock is already set by Expect")
	}

	if mmSave.defaultExpectation.paramPtrs == nil {
		mmSave.defaultExpectation.paramPtrs = &UrlsKeeperMockSaveParamPtrs{}
	}
	mmSave.defaultExpectation.paramPtrs.shortURL = &shortURL
	mmSave.defaultExpectation.expectationOrigins.originShortURL = minimock.CallerInfo(1)

	return mmSave
}

// ExpectUserIDParam4 sets up expected param userID for UrlsKeeper.Save
func (mmSave *mUrlsKeeperMockSave) ExpectUserIDParam4(userID string) *mUrlsKeeperMockSave {
	if mmSave.mock.funcSave != nil {
		mmSave.mock.t.Fatalf("UrlsKeeperMock.Save mock is already set by Set")
	}

	if mmSave.defaultExpectation == nil {
		mmSave.defaultExpectation = &UrlsKeeperMockSaveExpectation{}
	}

	if mmSave.defaultExpectation.params != nil {
		mmSave.mock.t.Fatalf("UrlsKeeperMock.Save mock is already set by Expect")
	}

	if mmSave.defaultExpectation.paramPtrs == nil {
		mmSave.defaultExpectation.paramPtrs = &UrlsKeeperMockSaveParamPtrs{}
	}
	mmSave.defaultExpectation.paramPtrs.userID = &userID
	mmSave.defaultExpectation.expectationOrigins.originUserID = minimock.CallerInfo(1)

	return mmSave
}

// Inspect accepts an inspector function that has same arguments as the UrlsKeeper.Save
func (mmSave *mUrlsKeeperMockSave) Inspect(f func(ctx context.Context, originalURL string, shortURL string, userID string)) *mUrlsKeeperMockSave {
	if mmSave.mock.inspectFuncSave != nil {
		mmSave.mock.t.Fatalf("Inspect function is already set for UrlsKeeperMock.Save")
	}

	mmSave.mock.inspectFuncSave = f

	return mmSave
}

// Return sets up results that will be returned by UrlsKeeper.Save
func (mmSave *mUrlsKeeperMockSave) Return(err error) *UrlsKeeperMock {
	if mmSave.mock.funcSave != nil {
		mmSave.mock.t.Fatalf("UrlsKeeperMock.Save mock is already set by Set")
	}

	if mmSave.defaultExpectation == nil {
		mmSave.defaultExpectation = &UrlsKeeperMockSaveExpectation{mock: mmSave.mock}
	}
	mmSave.defaultExpectation.results = &UrlsKeeperMockSaveResults{err}
	mmSave.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmSave.mock
}

// Set uses given function f to mock the UrlsKeeper.Save method
func (mmSave *mUrlsKeeperMockSave) Set(f func(ctx context.Context, originalURL string, shortURL string, userID string) (err error)) *UrlsKeeperMock {
	if mmSave.defaultExpectation != nil {
		mmSave.mock.t.Fatalf("Default expectation is already set for the UrlsKeeper.Save method")
	}

	if len(mmSave.expectations) > 0 {
		mmSave.mock.t.Fatalf("Some expectations are already set for the UrlsKeeper.Save method")
	}

	mmSave.mock.funcSave = f
	mmSave.mock.funcSaveOrigin = minimock.CallerInfo(1)
	return mmSave.mock
}

// When sets expectation for the UrlsKeeper.Save which will trigger the result defined by the following
// Then helper
func (mmSave *mUrlsKeeperMockSave) When(ctx context.Context, originalURL string, shortURL string, userID string) *UrlsKeeperMockSaveExpectation {
	if mmSave.mock.funcSave != nil {
		mmSave.mock.t.Fatalf("UrlsKeeperMock.Save mock is already set by Set")
	}

	expectation := &UrlsKeeperMockSaveExpectation{
		mock:               mmSave.mock,
		params:             &UrlsKeeperMockSaveParams{ctx, originalURL, shortURL, userID},
		expectationOrigins: UrlsKeeperMockSaveExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmSave.expectations = append(mmSave.expectations, expectation)
	return expectation
}

// Then sets up UrlsKeeper.Save return parameters for the expectation previously defined by the When method
func (e *UrlsKeeperMockSaveExpectation) Then(err error) *UrlsKeeperMock {
	e.results = &UrlsKeeperMockSaveResults{err}
	return e.mock
}

// Times sets number of times UrlsKeeper.Save should be invoked
func (mmSave *mUrlsKeeperMockSave) Times(n uint64) *mUrlsKeeperMockSave {
	if n == 0 {
		mmSave.mock.t.Fatalf("Times of UrlsKeeperMock.Save mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmSave.expectedInvocations, n)
	mmSave.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmSave
}

func (mmSave *mUrlsKeeperMockSave) invocationsDone() bool {
	if len(mmSave.expectations) == 0 && mmSave.defaultExpectation == nil && mmSave.mock.funcSave == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmSave.mock.afterSaveCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmSave.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Save implements mm_shorter.UrlsKeeper
func (mmSave *UrlsKeeperMock) Save(ctx context.Context, originalURL string, shortURL string, userID string) (err error) {
	mm_atomic.AddUint64(&mmSave.beforeSaveCounter, 1)
	defer mm_atomic.AddUint64(&mmSave.afterSaveCounter, 1)

	mmSave.t.Helper()

	if mmSave.inspectFuncSave != nil {
		mmSave.inspectFuncSave(ctx, originalURL, shortURL, userID)
	}

	mm_params := UrlsKeeperMockSaveParams{ctx, originalURL, shortURL, userID}

	// Record call args
	mmSave.SaveMock.mutex.Lock()
	mmSave.SaveMock.callArgs = append(mmSave.SaveMock.callArgs, &mm_params)
	mmSave.SaveMock.mutex.Unlock()

	for _, e := range mmSave.SaveMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmSave.SaveMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSave.SaveMock.defaultExpectation.Counter, 1)
		mm_want := mmSave.SaveMock.defaultExpectation.params
		mm_want_ptrs := mmSave.SaveMock.defaultExpectation.paramPtrs

		mm_got := UrlsKeeperMockSaveParams{ctx, originalURL, shortURL, userID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmSave.t.Errorf("UrlsKeeperMock.Save got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSave.SaveMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.originalURL != nil && !minimock.Equal(*mm_want_ptrs.originalURL, mm_got.originalURL) {
				mmSave.t.Errorf("UrlsKeeperMock.Save got unexpected parameter originalURL, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSave.SaveMock.defaultExpectation.expectationOrigins.originOriginalURL, *mm_want_ptrs.originalURL, mm_got.originalURL, minimock.Diff(*mm_want_ptrs.originalURL, mm_got.originalURL))
			}

			if mm_want_ptrs.shortURL != nil && !minimock.Equal(*mm_want_ptrs.shortURL, mm_got.shortURL) {
				mmSave.t.Errorf("UrlsKeeperMock.Save got unexpected parameter shortURL, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSave.SaveMock.defaultExpectation.expectationOrigins.originShortURL, *mm_want_ptrs.shortURL, mm_got.shortURL, minimock.Diff(*mm_want_ptrs.shortURL, mm_got.shortURL))
			}

			if mm_want_ptrs.userID != nil && !minimock.Equal(*mm_want_ptrs.userID, mm_got.userID) {
				mmSave.t.Errorf("UrlsKeeperMock.Save got unexpected parameter userID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSave.SaveMock.defaultExpectation.expectationOrigins.originUserID, *mm_want_ptrs.userID, mm_got.userID, minimock.Diff(*mm_want_ptrs.userID, mm_got.userID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSave.t.Errorf("UrlsKeeperMock.Save got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmSave.SaveMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSave.SaveMock.defaultExpectation.results
		if mm_results == nil {
			mmSave.t.Fatal("No results are set for the UrlsKeeperMock.Save")
		}
		return (*mm_results).err
	}
	if mmSave.funcSave != nil {
		return mmSave.funcSave(ctx, originalURL, shortURL, userID)
	}
	mmSave.t.Fatalf("Unexpected call to UrlsKeeperMock.Save. %v %v %v %v", ctx, originalURL, shortURL, userID)
	return
}

// SaveAfterCounter returns a count of finished UrlsKeeperMock.Save invocations
func (mmSave *UrlsKeeperMock) SaveAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSave.afterSaveCounter)
}

// SaveBeforeCounter returns a count of UrlsKeeperMock.Save invocations
func (mmSave *UrlsKeeperMock) SaveBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSave.beforeSaveCounter)
}

// Calls returns a list of arguments used in each call to UrlsKeeperMock.Save.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSave *mUrlsKeeperMockSave) Calls() []*UrlsKeeperMockSaveParams {
	mmSave.mutex.RLock()

	argCopy := make([]*UrlsKeeperMockSaveParams, len(mmSave.callArgs))
	copy(argCopy, mmSave.callArgs)

	mmSave.mutex.RUnlock()

	return argCopy
}

// MinimockSaveDone returns true if the count of the Save invocations corresponds
// the number of defined expectations
func (m *UrlsKeeperMock) MinimockSaveDone() bool {
	if m.SaveMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.SaveMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.SaveMock.invocationsDone()
}

// MinimockSaveInspect logs each unmet expectation
func (m *UrlsKeeperMock) MinimockSaveInspect() {
	for _, e := range m.SaveMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UrlsKeeperMock.Save at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterSaveCounter := mm_atomic.LoadUint64(&m.afterSaveCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.SaveMock.defaultExpectation != nil && afterSaveCounter < 1 {
		if m.SaveMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to UrlsKeeperMock.Save at\n%s", m.SaveMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to UrlsKeeperMock.Save at\n%s with params: %#v", m.SaveMock.defaultExpectation.expectationOrigins.origin, *m.SaveMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSave != nil && afterSaveCounter < 1 {
		m.t.Errorf("Expected call to UrlsKeeperMock.Save at\n%s", m.funcSaveOrigin)
	}

	if !m.SaveMock.invocationsDone() && afterSaveCounter > 0 {
		m.t.Errorf("Expected %d calls to UrlsKeeperMock.Save at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.SaveMock.expectedInvocations), m.SaveMock.expectedInvocationsOrigin, afterSaveCounter)
	}
}

type mUrlsKeeperMockSaveBatch struct {
	optional           bool
	mock               *UrlsKeeperMock
	defaultExpectation *UrlsKeeperMockSaveBatchExpectation
	expectations       []*UrlsKeeperMockSaveBatchExpectation

	callArgs []*UrlsKeeperMockSaveBatchParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// UrlsKeeperMockSaveBatchExpectation specifies expectation struct of the UrlsKeeper.SaveBatch
type UrlsKeeperMockSaveBatchExpectation struct {
	mock               *UrlsKeeperMock
	params             *UrlsKeeperMockSaveBatchParams
	paramPtrs          *UrlsKeeperMockSaveBatchParamPtrs
	expectationOrigins UrlsKeeperMockSaveBatchExpectationOrigins
	results            *UrlsKeeperMockSaveBatchResults
	returnOrigin       string
	Counter            uint64
}

// UrlsKeeperMockSaveBatchParams contains parameters of the UrlsKeeper.SaveBatch
type UrlsKeeperMockSaveBatchParams struct {
	ctx    context.Context
	urls   map[string]string
	userID string
}

// UrlsKeeperMockSaveBatchParamPtrs contains pointers to parameters of the UrlsKeeper.SaveBatch
type UrlsKeeperMockSaveBatchParamPtrs struct {
	ctx    *context.Context
	urls   *map[string]string
	userID *string
}

// UrlsKeeperMockSaveBatchResults contains results of the UrlsKeeper.SaveBatch
type UrlsKeeperMockSaveBatchResults struct {
	err error
}

// UrlsKeeperMockSaveBatchOrigins contains origins of expectations of the UrlsKeeper.SaveBatch
type UrlsKeeperMockSaveBatchExpectationOrigins struct {
	origin       string
	originCtx    string
	originUrls   string
	originUserID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmSaveBatch *mUrlsKeeperMockSaveBatch) Optional() *mUrlsKeeperMockSaveBatch {
	mmSaveBatch.optional = true
	return mmSaveBatch
}

// Expect sets up expected params for UrlsKeeper.SaveBatch
func (mmSaveBatch *mUrlsKeeperMockSaveBatch) Expect(ctx context.Context, urls map[string]string, userID string) *mUrlsKeeperMockSaveBatch {
	if mmSaveBatch.mock.funcSaveBatch != nil {
		mmSaveBatch.mock.t.Fatalf("UrlsKeeperMock.SaveBatch mock is already set by Set")
	}

	if mmSaveBatch.defaultExpectation == nil {
		mmSaveBatch.defaultExpectation = &UrlsKeeperMockSaveBatchExpectation{}
	}

	if mmSaveBatch.defaultExpectation.paramPtrs != nil {
		mmSaveBatch.mock.t.Fatalf("UrlsKeeperMock.SaveBatch mock is already set by ExpectParams functions")
	}

	mmSaveBatch.defaultExpectation.params = &UrlsKeeperMockSaveBatchParams{ctx, urls, userID}
	mmSaveBatch.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmSaveBatch.expectations {
		if minimock.Equal(e.params, mmSaveBatch.defaultExpectation.params) {
			mmSaveBatch.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSaveBatch.defaultExpectation.params)
		}
	}

	return mmSaveBatch
}

// ExpectCtxParam1 sets up expected param ctx for UrlsKeeper.SaveBatch
func (mmSaveBatch *mUrlsKeeperMockSaveBatch) ExpectCtxParam1(ctx context.Context) *mUrlsKeeperMockSaveBatch {
	if mmSaveBatch.mock.funcSaveBatch != nil {
		mmSaveBatch.mock.t.Fatalf("UrlsKeeperMock.SaveBatch mock is already set by Set")
	}

	if mmSaveBatch.defaultExpectation == nil {
		mmSaveBatch.defaultExpectation = &UrlsKeeperMockSaveBatchExpectation{}
	}

	if mmSaveBatch.defaultExpectation.params != nil {
		mmSaveBatch.mock.t.Fatalf("UrlsKeeperMock.SaveBatch mock is already set by Expect")
	}

	if mmSaveBatch.defaultExpectation.paramPtrs == nil {
		mmSaveBatch.defaultExpectation.paramPtrs = &UrlsKeeperMockSaveBatchParamPtrs{}
	}
	mmSaveBatch.defaultExpectation.paramPtrs.ctx = &ctx
	mmSaveBatch.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmSaveBatch
}

// ExpectUrlsParam2 sets up expected param urls for UrlsKeeper.SaveBatch
func (mmSaveBatch *mUrlsKeeperMockSaveBatch) ExpectUrlsParam2(urls map[string]string) *mUrlsKeeperMockSaveBatch {
	if mmSaveBatch.mock.funcSaveBatch != nil {
		mmSaveBatch.mock.t.Fatalf("UrlsKeeperMock.SaveBatch mock is already set by Set")
	}

	if mmSaveBatch.defaultExpectation == nil {
		mmSaveBatch.defaultExpectation = &UrlsKeeperMockSaveBatchExpectation{}
	}

	if mmSaveBatch.defaultExpectation.params != nil {
		mmSaveBatch.mock.t.Fatalf("UrlsKeeperMock.SaveBatch mock is already set by Expect")
	}

	if mmSaveBatch.defaultExpectation.paramPtrs == nil {
		mmSaveBatch.defaultExpectation.paramPtrs = &UrlsKeeperMockSaveBatchParamPtrs{}
	}
	mmSaveBatch.defaultExpectation.paramPtrs.urls = &urls
	mmSaveBatch.defaultExpectation.expectationOrigins.originUrls = minimock.CallerInfo(1)

	return mmSaveBatch
}

// ExpectUserIDParam3 sets up expected param userID for UrlsKeeper.SaveBatch
func (mmSaveBatch *mUrlsKeeperMockSaveBatch) ExpectUserIDParam3(userID string) *mUrlsKeeperMockSaveBatch {
	if mmSaveBatch.mock.funcSaveBatch != nil {
		mmSaveBatch.mock.t.Fatalf("UrlsKeeperMock.SaveBatch mock is already set by Set")
	}

	if mmSaveBatch.defaultExpectation == nil {
		mmSaveBatch.defaultExpectation = &UrlsKeeperMockSaveBatchExpectation{}
	}

	if mmSaveBatch.defaultExpectation.params != nil {
		mmSaveBatch.mock.t.Fatalf("UrlsKeeperMock.SaveBatch mock is already set by Expect")
	}

	if mmSaveBatch.defaultExpectation.paramPtrs == nil {
		mmSaveBatch.defaultExpectation.paramPtrs = &UrlsKeeperMockSaveBatchParamPtrs{}
	}
	mmSaveBatch.defaultExpectation.paramPtrs.userID = &userID
	mmSaveBatch.defaultExpectation.expectationOrigins.originUserID = minimock.CallerInfo(1)

	return mmSaveBatch
}

// Inspect accepts an inspector function that has same arguments as the UrlsKeeper.SaveBatch
func (mmSaveBatch *mUrlsKeeperMockSaveBatch) Inspect(f func(ctx context.Context, urls map[string]string, userID string)) *mUrlsKeeperMockSaveBatch {
	if mmSaveBatch.mock.inspectFuncSaveBatch != nil {
		mmSaveBatch.mock.t.Fatalf("Inspect function is already set for UrlsKeeperMock.SaveBatch")
	}

	mmSaveBatch.mock.inspectFuncSaveBatch = f

	return mmSaveBatch
}

// Return sets up results that will be returned by UrlsKeeper.SaveBatch
func (mmSaveBatch *mUrlsKeeperMockSaveBatch) Return(err error) *UrlsKeeperMock {
	if mmSaveBatch.mock.funcSaveBatch != nil {
		mmSaveBatch.mock.t.Fatalf("UrlsKeeperMock.SaveBatch mock is already set by Set")
	}

	if mmSaveBatch.defaultExpectation == nil {
		mmSaveBatch.defaultExpectation = &UrlsKeeperMockSaveBatchExpectation{mock: mmSaveBatch.mock}
	}
	mmSaveBatch.defaultExpectation.results = &UrlsKeeperMockSaveBatchResults{err}
	mmSaveBatch.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmSaveBatch.mock
}

// Set uses given function f to mock the UrlsKeeper.SaveBatch method
func (mmSaveBatch *mUrlsKeeperMockSaveBatch) Set(f func(ctx context.Context, urls map[string]string, userID string) (err error)) *UrlsKeeperMock {
	if mmSaveBatch.defaultExpectation != nil {
		mmSaveBatch.mock.t.Fatalf("Default expectation is already set for the UrlsKeeper.SaveBatch method")
	}

	if len(mmSaveBatch.expectations) > 0 {
		mmSaveBatch.mock.t.Fatalf("Some expectations are already set for the UrlsKeeper.SaveBatch method")
	}

	mmSaveBatch.mock.funcSaveBatch = f
	mmSaveBatch.mock.funcSaveBatchOrigin = minimock.CallerInfo(1)
	return mmSaveBatch.mock
}

// When sets expectation for the UrlsKeeper.SaveBatch which will trigger the result defined by the following
// Then helper
func (mmSaveBatch *mUrlsKeeperMockSaveBatch) When(ctx context.Context, urls map[string]string, userID string) *UrlsKeeperMockSaveBatchExpectation {
	if mmSaveBatch.mock.funcSaveBatch != nil {
		mmSaveBatch.mock.t.Fatalf("UrlsKeeperMock.SaveBatch mock is already set by Set")
	}

	expectation := &UrlsKeeperMockSaveBatchExpectation{
		mock:               mmSaveBatch.mock,
		params:             &UrlsKeeperMockSaveBatchParams{ctx, urls, userID},
		expectationOrigins: UrlsKeeperMockSaveBatchExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmSaveBatch.expectations = append(mmSaveBatch.expectations, expectation)
	return expectation
}

// Then sets up UrlsKeeper.SaveBatch return parameters for the expectation previously defined by the When method
func (e *UrlsKeeperMockSaveBatchExpectation) Then(err error) *UrlsKeeperMock {
	e.results = &UrlsKeeperMockSaveBatchResults{err}
	return e.mock
}

// Times sets number of times UrlsKeeper.SaveBatch should be invoked
func (mmSaveBatch *mUrlsKeeperMockSaveBatch) Times(n uint64) *mUrlsKeeperMockSaveBatch {
	if n == 0 {
		mmSaveBatch.mock.t.Fatalf("Times of UrlsKeeperMock.SaveBatch mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmSaveBatch.expectedInvocations, n)
	mmSaveBatch.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmSaveBatch
}

func (mmSaveBatch *mUrlsKeeperMockSaveBatch) invocationsDone() bool {
	if len(mmSaveBatch.expectations) == 0 && mmSaveBatch.defaultExpectation == nil && mmSaveBatch.mock.funcSaveBatch == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmSaveBatch.mock.afterSaveBatchCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmSaveBatch.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// SaveBatch implements mm_shorter.UrlsKeeper
func (mmSaveBatch *UrlsKeeperMock) SaveBatch(ctx context.Context, urls map[string]string, userID string) (err error) {
	mm_atomic.AddUint64(&mmSaveBatch.beforeSaveBatchCounter, 1)
	defer mm_atomic.AddUint64(&mmSaveBatch.afterSaveBatchCounter, 1)

	mmSaveBatch.t.Helper()

	if mmSaveBatch.inspectFuncSaveBatch != nil {
		mmSaveBatch.inspectFuncSaveBatch(ctx, urls, userID)
	}

	mm_params := UrlsKeeperMockSaveBatchParams{ctx, urls, userID}

	// Record call args
	mmSaveBatch.SaveBatchMock.mutex.Lock()
	mmSaveBatch.SaveBatchMock.callArgs = append(mmSaveBatch.SaveBatchMock.callArgs, &mm_params)
	mmSaveBatch.SaveBatchMock.mutex.Unlock()

	for _, e := range mmSaveBatch.SaveBatchMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmSaveBatch.SaveBatchMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSaveBatch.SaveBatchMock.defaultExpectation.Counter, 1)
		mm_want := mmSaveBatch.SaveBatchMock.defaultExpectation.params
		mm_want_ptrs := mmSaveBatch.SaveBatchMock.defaultExpectation.paramPtrs

		mm_got := UrlsKeeperMockSaveBatchParams{ctx, urls, userID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmSaveBatch.t.Errorf("UrlsKeeperMock.SaveBatch got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSaveBatch.SaveBatchMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.urls != nil && !minimock.Equal(*mm_want_ptrs.urls, mm_got.urls) {
				mmSaveBatch.t.Errorf("UrlsKeeperMock.SaveBatch got unexpected parameter urls, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSaveBatch.SaveBatchMock.defaultExpectation.expectationOrigins.originUrls, *mm_want_ptrs.urls, mm_got.urls, minimock.Diff(*mm_want_ptrs.urls, mm_got.urls))
			}

			if mm_want_ptrs.userID != nil && !minimock.Equal(*mm_want_ptrs.userID, mm_got.userID) {
				mmSaveBatch.t.Errorf("UrlsKeeperMock.SaveBatch got unexpected parameter userID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSaveBatch.SaveBatchMock.defaultExpectation.expectationOrigins.originUserID, *mm_want_ptrs.userID, mm_got.userID, minimock.Diff(*mm_want_ptrs.userID, mm_got.userID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSaveBatch.t.Errorf("UrlsKeeperMock.SaveBatch got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmSaveBatch.SaveBatchMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSaveBatch.SaveBatchMock.defaultExpectation.results
		if mm_results == nil {
			mmSaveBatch.t.Fatal("No results are set for the UrlsKeeperMock.SaveBatch")
		}
		return (*mm_results).err
	}
	if mmSaveBatch.funcSaveBatch != nil {
		return mmSaveBatch.funcSaveBatch(ctx, urls, userID)
	}
	mmSaveBatch.t.Fatalf("Unexpected call to UrlsKeeperMock.SaveBatch. %v %v %v", ctx, urls, userID)
	return
}

// SaveBatchAfterCounter returns a count of finished UrlsKeeperMock.SaveBatch invocations
func (mmSaveBatch *UrlsKeeperMock) SaveBatchAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSaveBatch.afterSaveBatchCounter)
}

// SaveBatchBeforeCounter returns a count of UrlsKeeperMock.SaveBatch invocations
func (mmSaveBatch *UrlsKeeperMock) SaveBatchBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSaveBatch.beforeSaveBatchCounter)
}

// Calls returns a list of arguments used in each call to UrlsKeeperMock.SaveBatch.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSaveBatch *mUrlsKeeperMockSaveBatch) Calls() []*UrlsKeeperMockSaveBatchParams {
	mmSaveBatch.mutex.RLock()

	argCopy := make([]*UrlsKeeperMockSaveBatchParams, len(mmSaveBatch.callArgs))
	copy(argCopy, mmSaveBatch.callArgs)

	mmSaveBatch.mutex.RUnlock()

	return argCopy
}

// MinimockSaveBatchDone returns true if the count of the SaveBatch invocations corresponds
// the number of defined expectations
func (m *UrlsKeeperMock) MinimockSaveBatchDone() bool {
	if m.SaveBatchMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.SaveBatchMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.SaveBatchMock.invocationsDone()
}

// MinimockSaveBatchInspect logs each unmet expectation
func (m *UrlsKeeperMock) MinimockSaveBatchInspect() {
	for _, e := range m.SaveBatchMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UrlsKeeperMock.SaveBatch at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterSaveBatchCounter := mm_atomic.LoadUint64(&m.afterSaveBatchCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.SaveBatchMock.defaultExpectation != nil && afterSaveBatchCounter < 1 {
		if m.SaveBatchMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to UrlsKeeperMock.SaveBatch at\n%s", m.SaveBatchMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to UrlsKeeperMock.SaveBatch at\n%s with params: %#v", m.SaveBatchMock.defaultExpectation.expectationOrigins.origin, *m.SaveBatchMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSaveBatch != nil && afterSaveBatchCounter < 1 {
		m.t.Errorf("Expected call to UrlsKeeperMock.SaveBatch at\n%s", m.funcSaveBatchOrigin)
	}

	if !m.SaveBatchMock.invocationsDone() && afterSaveBatchCounter > 0 {
		m.t.Errorf("Expected %d calls to UrlsKeeperMock.SaveBatch at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.SaveBatchMock.expectedInvocations), m.SaveBatchMock.expectedInvocationsOrigin, afterSaveBatchCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *UrlsKeeperMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockGetShortURLInspect()

			m.MinimockSaveInspect()

			m.MinimockSaveBatchInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *UrlsKeeperMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *UrlsKeeperMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockGetShortURLDone() &&
		m.MinimockSaveDone() &&
		m.MinimockSaveBatchDone()
}
