// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// UrlsKeeperMock implements mm_shorter.UrlsKeeper
type UrlsKeeperMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcSave          func(ctx context.Context, originalURL string, shortURL string) (err error)
	funcSaveOrigin    string
	inspectFuncSave   func(ctx context.Context, originalURL string, shortURL string)
	afterSaveCounter  uint64
	beforeSaveCounter uint64
	SaveMock          mUrlsKeeperMockSave
}

// NewUrlsKeeperMock returns a mock for mm_shorter.UrlsKeeper
func NewUrlsKeeperMock(t minimock.Tester) *UrlsKeeperMock {
	m := &UrlsKeeperMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.SaveMock = mUrlsKeeperMockSave{mock: m}
	m.SaveMock.callArgs = []*UrlsKeeperMockSaveParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mUrlsKeeperMockSave struct {
	optional           bool
	mock               *UrlsKeeperMock
	defaultExpectation *UrlsKeeperMockSaveExpectation
	expectations       []*UrlsKeeperMockSaveExpectation

	callArgs []*UrlsKeeperMockSaveParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// UrlsKeeperMockSaveExpectation specifies expectation struct of the UrlsKeeper.Save
type UrlsKeeperMockSaveExpectation struct {
	mock               *UrlsKeeperMock
	params             *UrlsKeeperMockSaveParams
	paramPtrs          *UrlsKeeperMockSaveParamPtrs
	expectationOrigins UrlsKeeperMockSaveExpectationOrigins
	results            *UrlsKeeperMockSaveResults
	returnOrigin       string
	Counter            uint64
}

// UrlsKeeperMockSaveParams contains parameters of the UrlsKeeper.Save
type UrlsKeeperMockSaveParams struct {
	ctx         context.Context
	originalURL string
	shortURL    string
}

// UrlsKeeperMockSaveParamPtrs contains pointers to parameters of the UrlsKeeper.Save
type UrlsKeeperMockSaveParamPtrs struct {
	ctx         *context.Context
	originalURL *string
	shortURL    *string
}

// UrlsKeeperMockSaveResults contains results of the UrlsKeeper.Save
type UrlsKeeperMockSaveResults struct {
	err error
}

// UrlsKeeperMockSaveOrigins contains origins of expectations of the UrlsKeeper.Save
type UrlsKeeperMockSaveExpectationOrigins struct {
	origin            string
	originCtx         string
	originOriginalURL string
	originShortURL    string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmSave *mUrlsKeeperMockSave) Optional() *mUrlsKeeperMockSave {
	mmSave.optional = true
	return mmSave
}

// Expect sets up expected params for UrlsKeeper.Save
func (mmSave *mUrlsKeeperMockSave) Expect(ctx context.Context, originalURL string, shortURL string) *mUrlsKeeperMockSave {
	if mmSave.mock.funcSave != nil {
		mmSave.mock.t.Fatalf("UrlsKeeperMock.Save mock is already set by Set")
	}

	if mmSave.defaultExpectation == nil {
		mmSave.defaultExpectation = &UrlsKeeperMockSaveExpectation{}
	}

	if mmSave.defaultExpectation.paramPtrs != nil {
		mmSave.mock.t.Fatalf("UrlsKeeperMock.Save mock is already set by ExpectParams functions")
	}

	mmSave.defaultExpectation.params = &UrlsKeeperMockSaveParams{ctx, originalURL, shortURL}
	mmSave.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmSave.expectations {
		if minimock.Equal(e.params, mmSave.defaultExpectation.params) {
			mmSave.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSave.defaultExpectation.params)
		}
	}

	return mmSave
}

// ExpectCtxParam1 sets up expected param ctx for UrlsKeeper.Save
func (mmSave *mUrlsKeeperMockSave) ExpectCtxParam1(ctx context.Context) *mUrlsKeeperMockSave {
	if mmSave.mock.funcSave != nil {
		mmSave.mock.t.Fatalf("UrlsKeeperMock.Save mock is already set by Set")
	}

	if mmSave.defaultExpectation == nil {
		mmSave.defaultExpectation = &UrlsKeeperMockSaveExpectation{}
	}

	if mmSave.defaultExpectation.params != nil {
		mmSave.mock.t.Fatalf("UrlsKeeperMock.Save mock is already set by Expect")
	}

	if mmSave.defaultExpectation.paramPtrs == nil {
		mmSave.defaultExpectation.paramPtrs = &UrlsKeeperMockSaveParamPtrs{}
	}
	mmSave.defaultExpectation.paramPtrs.ctx = &ctx
	mmSave.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmSave
}

// ExpectOriginalURLParam2 sets up expected param originalURL for UrlsKeeper.Save
func (mmSave *mUrlsKeeperMockSave) ExpectOriginalURLParam2(originalURL string) *mUrlsKeeperMockSave {
	if mmSave.mock.funcSave != nil {
		mmSave.mock.t.Fatalf("UrlsKeeperMock.Save mock is already set by Set")
	}

	if mmSave.defaultExpectation == nil {
		mmSave.defaultExpectation = &UrlsKeeperMockSaveExpectation{}
	}

	if mmSave.defaultExpectation.params != nil {
		mmSave.mock.t.Fatalf("UrlsKeeperMock.Save mock is already set by Expect")
	}

	if mmSave.defaultExpectation.paramPtrs == nil {
		mmSave.defaultExpectation.paramPtrs = &UrlsKeeperMockSaveParamPtrs{}
	}
	mmSave.defaultExpectation.paramPtrs.originalURL = &originalURL
	mmSave.defaultExpectation.expectationOrigins.originOriginalURL = minimock.CallerInfo(1)

	return mmSave
}

// ExpectShortURLParam3 sets up expected param shortURL for UrlsKeeper.Save
func (mmSave *mUrlsKeeperMockSave) ExpectShortURLParam3(shortURL string) *mUrlsKeeperMockSave {
	if mmSave.mock.funcSave != nil {
		mmSave.mock.t.Fatalf("UrlsKeeperMock.Save mock is already set by Set")
	}

	if mmSave.defaultExpectation == nil {
		mmSave.defaultExpectation = &UrlsKeeperMockSaveExpectation{}
	}

	if mmSave.defaultExpectation.params != nil {
		mmSave.mock.t.Fatalf("UrlsKeeperMock.Save mock is already set by Expect")
	}

	if mmSave.defaultExpectation.paramPtrs == nil {
		mmSave.defaultExpectation.paramPtrs = &UrlsKeeperMockSaveParamPtrs{}
	}
	mmSave.defaultExpectation.paramPtrs.shortURL = &shortURL
	mmSave.defaultExpectation.expectationOrigins.originShortURL = minimock.CallerInfo(1)

	return mmSave
}

// Inspect accepts an inspector function that has same arguments as the UrlsKeeper.Save
func (mmSave *mUrlsKeeperMockSave) Inspect(f func(ctx context.Context, originalURL string, shortURL string)) *mUrlsKeeperMockSave {
	if mmSave.mock.inspectFuncSave != nil {
		mmSave.mock.t.Fatalf("Inspect function is already set for UrlsKeeperMock.Save")
	}

	mmSave.mock.inspectFuncSave = f

	return mmSave
}

// Return sets up results that will be returned by UrlsKeeper.Save
func (mmSave *mUrlsKeeperMockSave) Return(err error) *UrlsKeeperMock {
	if mmSave.mock.funcSave != nil {
		mmSave.mock.t.Fatalf("UrlsKeeperMock.Save mock is already set by Set")
	}

	if mmSave.defaultExpectation == nil {
		mmSave.defaultExpectation = &UrlsKeeperMockSaveExpectation{mock: mmSave.mock}
	}
	mmSave.defaultExpectation.results = &UrlsKeeperMockSaveResults{err}
	mmSave.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmSave.mock
}

// Set uses given function f to mock the UrlsKeeper.Save method
func (mmSave *mUrlsKeeperMockSave) Set(f func(ctx context.Context, originalURL string, shortURL string) (err error)) *UrlsKeeperMock {
	if mmSave.defaultExpectation != nil {
		mmSave.mock.t.Fatalf("Default expectation is already set for the UrlsKeeper.Save method")
	}

	if len(mmSave.expectations) > 0 {
		mmSave.mock.t.Fatalf("Some expectations are already set for the UrlsKeeper.Save method")
	}

	mmSave.mock.funcSave = f
	mmSave.mock.funcSaveOrigin = minimock.CallerInfo(1)
	return mmSave.mock
}

// When sets expectation for the UrlsKeeper.Save which will trigger the result defined by the following
// Then helper
func (mmSave *mUrlsKeeperMockSave) When(ctx context.Context, originalURL string, shortURL string) *UrlsKeeperMockSaveExpectation {
	if mmSave.mock.funcSave != nil {
		mmSave.mock.t.Fatalf("UrlsKeeperMock.Save mock is already set by Set")
	}

	expectation := &UrlsKeeperMockSaveExpectation{
		mock:               mmSave.mock,
		params:             &UrlsKeeperMockSaveParams{ctx, originalURL, shortURL},
		expectationOrigins: UrlsKeeperMockSaveExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmSave.expectations = append(mmSave.expectations, expectation)
	return expectation
}

// Then sets up UrlsKeeper.Save return parameters for the expectation previously defined by the When method
func (e *UrlsKeeperMockSaveExpectation) Then(err error) *UrlsKeeperMock {
	e.results = &UrlsKeeperMockSaveResults{err}
	return e.mock
}

// Times sets number of times UrlsKeeper.Save should be invoked
func (mmSave *mUrlsKeeperMockSave) Times(n uint64) *mUrlsKeeperMockSave {
	if n == 0 {
		mmSave.mock.t.Fatalf("Times of UrlsKeeperMock.Save mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmSave.expectedInvocations, n)
	mmSave.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmSave
}

func (mmSave *mUrlsKeeperMockSave) invocationsDone() bool {
	if len(mmSave.expectations) == 0 && mmSave.defaultExpectation == nil && mmSave.mock.funcSave == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmSave.mock.afterSaveCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmSave.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Save implements mm_shorter.UrlsKeeper
func (mmSave *UrlsKeeperMock) Save(ctx context.Context, originalURL string, shortURL string) (err error) {
	mm_atomic.AddUint64(&mmSave.beforeSaveCounter, 1)
	defer mm_atomic.AddUint64(&mmSave.afterSaveCounter, 1)

	mmSave.t.Helper()

	if mmSave.inspectFuncSave != nil {
		mmSave.inspectFuncSave(ctx, originalURL, shortURL)
	}

	mm_params := UrlsKeeperMockSaveParams{ctx, originalURL, shortURL}

	// Record call args
	mmSave.SaveMock.mutex.Lock()
	mmSave.SaveMock.callArgs = append(mmSave.SaveMock.callArgs, &mm_params)
	mmSave.SaveMock.mutex.Unlock()

	for _, e := range mmSave.SaveMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmSave.SaveMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSave.SaveMock.defaultExpectation.Counter, 1)
		mm_want := mmSave.SaveMock.defaultExpectation.params
		mm_want_ptrs := mmSave.SaveMock.defaultExpectation.paramPtrs

		mm_got := UrlsKeeperMockSaveParams{ctx, originalURL, shortURL}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmSave.t.Errorf("UrlsKeeperMock.Save got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSave.SaveMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.originalURL != nil && !minimock.Equal(*mm_want_ptrs.originalURL, mm_got.originalURL) {
				mmSave.t.Errorf("UrlsKeeperMock.Save got unexpected parameter originalURL, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSave.SaveMock.defaultExpectation.expectationOrigins.originOriginalURL, *mm_want_ptrs.originalURL, mm_got.originalURL, minimock.Diff(*mm_want_ptrs.originalURL, mm_got.originalURL))
			}

			if mm_want_ptrs.shortURL != nil && !minimock.Equal(*mm_want_ptrs.shortURL, mm_got.shortURL) {
				mmSave.t.Errorf("UrlsKeeperMock.Save got unexpected parameter shortURL, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSave.SaveMock.defaultExpectation.expectationOrigins.originShortURL, *mm_want_ptrs.shortURL, mm_got.shortURL, minimock.Diff(*mm_want_ptrs.shortURL, mm_got.shortURL))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSave.t.Errorf("UrlsKeeperMock.Save got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmSave.SaveMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSave.SaveMock.defaultExpectation.results
		if mm_results == nil {
			mmSave.t.Fatal("No results are set for the UrlsKeeperMock.Save")
		}
		return (*mm_results).err
	}
	if mmSave.funcSave != nil {
		return mmSave.funcSave(ctx, originalURL, shortURL)
	}
	mmSave.t.Fatalf("Unexpected call to UrlsKeeperMock.Save. %v %v %v", ctx, originalURL, shortURL)
	return
}

// SaveAfterCounter returns a count of finished UrlsKeeperMock.Save invocations
func (mmSave *UrlsKeeperMock) SaveAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSave.afterSaveCounter)
}

// SaveBeforeCounter returns a count of UrlsKeeperMock.Save invocations
func (mmSave *UrlsKeeperMock) SaveBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSave.beforeSaveCounter)
}

// Calls returns a list of arguments used in each call to UrlsKeeperMock.Save.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSave *mUrlsKeeperMockSave) Calls() []*UrlsKeeperMockSaveParams {
	mmSave.mutex.RLock()

	argCopy := make([]*UrlsKeeperMockSaveParams, len(mmSave.callArgs))
	copy(argCopy, mmSave.callArgs)

	mmSave.mutex.RUnlock()

	return argCopy
}

// MinimockSaveDone returns true if the count of the Save invocations corresponds
// the number of defined expectations
func (m *UrlsKeeperMock) MinimockSaveDone() bool {
	if m.SaveMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.SaveMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.SaveMock.invocationsDone()
}

// MinimockSaveInspect logs each unmet expectation
func (m *UrlsKeeperMock) MinimockSaveInspect() {
	for _, e := range m.SaveMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UrlsKeeperMock.Save at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterSaveCounter := mm_atomic.LoadUint64(&m.afterSaveCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.SaveMock.defaultExpectation != nil && afterSaveCounter < 1 {
		if m.SaveMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to UrlsKeeperMock.Save at\n%s", m.SaveMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to UrlsKeeperMock.Save at\n%s with params: %#v", m.SaveMock.defaultExpectation.expectationOrigins.origin, *m.SaveMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSave != nil && afterSaveCounter < 1 {
		m.t.Errorf("Expected call to UrlsKeeperMock.Save at\n%s", m.funcSaveOrigin)
	}

	if !m.SaveMock.invocationsDone() && afterSaveCounter > 0 {
		m.t.Errorf("Expected %d calls to UrlsKeeperMock.Save at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.SaveMock.expectedInvocations), m.SaveMock.expectedInvocationsOrigin, afterSaveCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *UrlsKeeperMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockSaveInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *UrlsKeeperMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *UrlsKeeperMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockSaveDone()
}
