// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// AuthServiceMock implements mm_grpcserver.AuthService
type AuthServiceMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcGetUserIDFromToken          func(token string) (userID string, err error)
	funcGetUserIDFromTokenOrigin    string
	inspectFuncGetUserIDFromToken   func(token string)
	afterGetUserIDFromTokenCounter  uint64
	beforeGetUserIDFromTokenCounter uint64
	GetUserIDFromTokenMock          mAuthServiceMockGetUserIDFromToken
}

// NewAuthServiceMock returns a mock for mm_grpcserver.AuthService
func NewAuthServiceMock(t minimock.Tester) *AuthServiceMock {
	m := &AuthServiceMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.GetUserIDFromTokenMock = mAuthServiceMockGetUserIDFromToken{mock: m}
	m.GetUserIDFromTokenMock.callArgs = []*AuthServiceMockGetUserIDFromTokenParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mAuthServiceMockGetUserIDFromToken struct {
	optional           bool
	mock               *AuthServiceMock
	defaultExpectation *AuthServiceMockGetUserIDFromTokenExpectation
	expectations       []*AuthServiceMockGetUserIDFromTokenExpectation

	callArgs []*AuthServiceMockGetUserIDFromTokenParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// AuthServiceMockGetUserIDFromTokenExpectation specifies expectation struct of the AuthService.GetUserIDFromToken
type AuthServiceMockGetUserIDFromTokenExpectation struct {
	mock               *AuthServiceMock
	params             *AuthServiceMockGetUserIDFromTokenParams
	paramPtrs          *AuthServiceMockGetUserIDFromTokenParamPtrs
	expectationOrigins AuthServiceMockGetUserIDFromTokenExpectationOrigins
	results            *AuthServiceMockGetUserIDFromTokenResults
	returnOrigin       string
	Counter            uint64
}

// AuthServiceMockGetUserIDFromTokenParams contains parameters of the AuthService.GetUserIDFromToken
type AuthServiceMockGetUserIDFromTokenParams struct {
	token string
}

// AuthServiceMockGetUserIDFromTokenParamPtrs contains pointers to parameters of the AuthService.GetUserIDFromToken
type AuthServiceMockGetUserIDFromTokenParamPtrs struct {
	token *string
}

// AuthServiceMockGetUserIDFromTokenResults contains results of the AuthService.GetUserIDFromToken
type AuthServiceMockGetUserIDFromTokenResults struct {
	userID string
	err    error
}

// AuthServiceMockGetUserIDFromTokenOrigins contains origins of expectations of the AuthService.GetUserIDFromToken
type AuthServiceMockGetUserIDFromTokenExpectationOrigins struct {
	origin      string
	originToken string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetUserIDFromToken *mAuthServiceMockGetUserIDFromToken) Optional() *mAuthServiceMockGetUserIDFromToken {
	mmGetUserIDFromToken.optional = true
	return mmGetUserIDFromToken
}

// Expect sets up expected params for AuthService.GetUserIDFromToken
func (mmGetUserIDFromToken *mAuthServiceMockGetUserIDFromToken) Expect(token string) *mAuthServiceMockGetUserIDFromToken {
	if mmGetUserIDFromToken.mock.funcGetUserIDFromToken != nil {
		mmGetUserIDFromToken.mock.t.Fatalf("AuthServiceMock.GetUserIDFromToken mock is already set by Set")
	}

	if mmGetUserIDFromToken.defaultExpectation == nil {
		mmGetUserIDFromToken.defaultExpectation = &AuthServiceMockGetUserIDFromTokenExpectation{}
	}

	if mmGetUserIDFromToken.defaultExpectation.paramPtrs != nil {
		mmGetUserIDFromToken.mock.t.Fatalf("AuthServiceMock.GetUserIDFromToken mock is already set by ExpectParams functions")
	}

	mmGetUserIDFromToken.defaultExpectation.params = &AuthServiceMockGetUserIDFromTokenParams{token}
	mmGetUserIDFromToken.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetUserIDFromToken.expectations {
		if minimock.Equal(e.params, mmGetUserIDFromToken.defaultExpectation.params) {
			mmGetUserIDFromToken.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetUserIDFromToken.defaultExpectation.params)
		}
	}

	return mmGetUserIDFromToken
}

// ExpectTokenParam1 sets up expected param token for AuthService.GetUserIDFromToken
func (mmGetUserIDFromToken *mAuthServiceMockGetUserIDFromToken) ExpectTokenParam1(token string) *mAuthServiceMockGetUserIDFromToken {
	if mmGetUserIDFromToken.mock.funcGetUserIDFromToken != nil {
		mmGetUserIDFromToken.mock.t.Fatalf("AuthServiceMock.GetUserIDFromToken mock is already set by Set")
	}

	if mmGetUserIDFromToken.defaultExpectation == nil {
		mmGetUserIDFromToken.defaultExpectation = &AuthServiceMockGetUserIDFromTokenExpectation{}
	}

	if mmGetUserIDFromToken.defaultExpectation.params != nil {
		mmGetUserIDFromToken.mock.t.Fatalf("AuthServiceMock.GetUserIDFromToken mock is already set by Expect")
	}

	if mmGetUserIDFromToken.defaultExpectation.paramPtrs == nil {
		mmGetUserIDFromToken.defaultExpectation.paramPtrs = &AuthServiceMockGetUserIDFromTokenParamPtrs{}
	}
	mmGetUserIDFromToken.defaultExpectation.paramPtrs.token = &token
	mmGetUserIDFromToken.defaultExpectation.expectationOrigins.originToken = minimock.CallerInfo(1)

	return mmGetUserIDFromToken
}

// Inspect accepts an inspector function that has same arguments as the AuthService.GetUserIDFromToken
func (mmGetUserIDFromToken *mAuthServiceMockGetUserIDFromToken) Inspect(f func(token string)) *mAuthServiceMockGetUserIDFromToken {
	if mmGetUserIDFromToken.mock.inspectFuncGetUserIDFromToken != nil {
		mmGetUserIDFromToken.mock.t.Fatalf("Inspect function is already set for AuthServiceMock.GetUserIDFromToken")
	}

	mmGetUserIDFromToken.mock.inspectFuncGetUserIDFromToken = f

	return mmGetUserIDFromToken
}

// Return sets up results that will be returned by AuthService.GetUserIDFromToken
func (mmGetUserIDFromToken *mAuthServiceMockGetUserIDFromToken) Return(userID string, err error) *AuthServiceMock {
	if mmGetUserIDFromToken.mock.funcGetUserIDFromToken != nil {
		mmGetUserIDFromToken.mock.t.Fatalf("AuthServiceMock.GetUserIDFromToken mock is already set by Set")
	}

	if mmGetUserIDFromToken.defaultExpectation == nil {
		mmGetUserIDFromToken.defaultExpectation = &AuthServiceMockGetUserIDFromTokenExpectation{mock: mmGetUserIDFromToken.mock}
	}
	mmGetUserIDFromToken.defaultExpectation.results = &AuthServiceMockGetUserIDFromTokenResults{userID, err}
	mmGetUserIDFromToken.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetUserIDFromToken.mock
}

// Set uses given function f to mock the AuthService.GetUserIDFromToken method
func (mmGetUserIDFromToken *mAuthServiceMockGetUserIDFromToken) Set(f func(token string) (userID string, err error)) *AuthServiceMock {
	if mmGetUserIDFromToken.defaultExpectation != nil {
		mmGetUserIDFromToken.mock.t.Fatalf("Default expectation is already set for the AuthService.GetUserIDFromToken method")
	}

	if len(mmGetUserIDFromToken.expectations) > 0 {
		mmGetUserIDFromToken.mock.t.Fatalf("Some expectations are already set for the AuthService.GetUserIDFromToken method")
	}

	mmGetUserIDFromToken.mock.funcGetUserIDFromToken = f
	mmGetUserIDFromToken.mock.funcGetUserIDFromTokenOrigin = minimock.CallerInfo(1)
	return mmGetUserIDFromToken.mock
}

// When sets expectation for the AuthService.GetUserIDFromToken which will trigger the result defined by the following
// Then helper
func (mmGetUserIDFromToken *mAuthServiceMockGetUserIDFromToken) When(token string) *AuthServiceMockGetUserIDFromTokenExpectation {
	if mmGetUserIDFromToken.mock.funcGetUserIDFromToken != nil {
		mmGetUserIDFromToken.mock.t.Fatalf("AuthServiceMock.GetUserIDFromToken mock is already set by Set")
	}

	expectation := &AuthServiceMockGetUserIDFromTokenExpectation{
		mock:               mmGetUserIDFromToken.mock,
		params:             &AuthServiceMockGetUserIDFromTokenParams{token},
		expectationOrigins: AuthServiceMockGetUserIDFromTokenExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetUserIDFromToken.expectations = append(mmGetUserIDFromToken.expectations, expectation)
	return expectation
}

// Then sets up AuthService.GetUserIDFromToken return parameters for the expectation previously defined by the When method
func (e *AuthServiceMockGetUserIDFromTokenExpectation) Then(userID string, err error) *AuthServiceMock {
	e.results = &AuthServiceMockGetUserIDFromTokenResults{userID, err}
	return e.mock
}

// Times sets number of times AuthService.GetUserIDFromToken should be invoked
func (mmGetUserIDFromToken *mAuthServiceMockGetUserIDFromToken) Times(n uint64) *mAuthServiceMockGetUserIDFromToken {
	if n == 0 {
		mmGetUserIDFromToken.mock.t.Fatalf("Times of AuthServiceMock.GetUserIDFromToken mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetUserIDFromToken.expectedInvocations, n)
	mmGetUserIDFromToken.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetUserIDFromToken
}

func (mmGetUserIDFromToken *mAuthServiceMockGetUserIDFromToken) invocationsDone() bool {
	if len(mmGetUserIDFromToken.expectations) == 0 && mmGetUserIDFromToken.defaultExpectation == nil && mmGetUserIDFromToken.mock.funcGetUserIDFromToken == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetUserIDFromToken.mock.afterGetUserIDFromTokenCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetUserIDFromToken.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetUserIDFromToken implements mm_grpcserver.AuthService
func (mmGetUserIDFromToken *AuthServiceMock) GetUserIDFromToken(token string) (userID string, err error) {
	mm_atomic.AddUint64(&mmGetUserIDFromToken.beforeGetUserIDFromTokenCounter, 1)
	defer mm_atomic.AddUint64(&mmGetUserIDFromToken.afterGetUserIDFromTokenCounter, 1)

	mmGetUserIDFromToken.t.Helper()

	if mmGetUserIDFromToken.inspectFuncGetUserIDFromToken != nil {
		mmGetUserIDFromToken.inspectFuncGetUserIDFromToken(token)
	}

	mm_params := AuthServiceMockGetUserIDFromTokenParams{token}

	// Record call args
	mmGetUserIDFromToken.GetUserIDFromTokenMock.mutex.Lock()
	mmGetUserIDFromToken.GetUserIDFromTokenMock.callArgs = append(mmGetUserIDFromToken.GetUserIDFromTokenMock.callArgs, &mm_params)
	mmGetUserIDFromToken.GetUserIDFromTokenMock.mutex.Unlock()

	for _, e := range mmGetUserIDFromToken.GetUserIDFromTokenMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.userID, e.results.err
		}
	}

	if mmGetUserIDFromToken.GetUserIDFromTokenMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetUserIDFromToken.GetUserIDFromTokenMock.defaultExpectation.Counter, 1)
		mm_want := mmGetUserIDFromToken.GetUserIDFromTokenMock.defaultExpectation.params
		mm_want_ptrs := mmGetUserIDFromToken.GetUserIDFromTokenMock.defaultExpectation.paramPtrs

		mm_got := AuthServiceMockGetUserIDFromTokenParams{token}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.token != nil && !minimock.Equal(*mm_want_ptrs.token, mm_got.token) {
				mmGetUserIDFromToken.t.Errorf("AuthServiceMock.GetUserIDFromToken got unexpected parameter token, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetUserIDFromToken.GetUserIDFromTokenMock.defaultExpectation.expectationOrigins.originToken, *mm_want_ptrs.token, mm_got.token, minimock.Diff(*mm_want_ptrs.token, mm_got.token))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetUserIDFromToken.t.Errorf("AuthServiceMock.GetUserIDFromToken got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetUserIDFromToken.GetUserIDFromTokenMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetUserIDFromToken.GetUserIDFromTokenMock.defaultExpectation.results
		if mm_results == nil {
			mmGetUserIDFromToken.t.Fatal("No results are set for the AuthServiceMock.GetUserIDFromToken")
		}
		return (*mm_results).userID, (*mm_results).err
	}
	if mmGetUserIDFromToken.funcGetUserIDFromToken != nil {
		return mmGetUserIDFromToken.funcGetUserIDFromToken(token)
	}
	mmGetUserIDFromToken.t.Fatalf("Unexpected call to AuthServiceMock.GetUserIDFromToken. %v", token)
	return
}

// GetUserIDFromTokenAfterCounter returns a count of finished AuthServiceMock.GetUserIDFromToken invocations
func (mmGetUserIDFromToken *AuthServiceMock) GetUserIDFromTokenAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetUserIDFromToken.afterGetUserIDFromTokenCounter)
}

// GetUserIDFromTokenBeforeCounter returns a count of AuthServiceMock.GetUserIDFromToken invocations
func (mmGetUserIDFromToken *AuthServiceMock) GetUserIDFromTokenBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetUserIDFromToken.beforeGetUserIDFromTokenCounter)
}

// Calls returns a list of arguments used in each call to AuthServiceMock.GetUserIDFromToken.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetUserIDFromToken *mAuthServiceMockGetUserIDFromToken) Calls() []*AuthServiceMockGetUserIDFromTokenParams {
	mmGetUserIDFromToken.mutex.RLock()

	argCopy := make([]*AuthServiceMockGetUserIDFromTokenParams, len(mmGetUserIDFromToken.callArgs))
	copy(argCopy, mmGetUserIDFromToken.callArgs)

	mmGetUserIDFromToken.mutex.RUnlock()

	return argCopy
}

// MinimockGetUserIDFromTokenDone returns true if the count of the GetUserIDFromToken invocations corresponds
// the number of defined expectations
func (m *AuthServiceMock) MinimockGetUserIDFromTokenDone() bool {
	if m.GetUserIDFromTokenMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetUserIDFromTokenMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetUserIDFromTokenMock.invocationsDone()
}

// MinimockGetUserIDFromTokenInspect logs each unmet expectation
func (m *AuthServiceMock) MinimockGetUserIDFromTokenInspect() {
	for _, e := range m.GetUserIDFromTokenMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to AuthServiceMock.GetUserIDFromToken at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetUserIDFromTokenCounter := mm_atomic.LoadUint64(&m.afterGetUserIDFromTokenCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetUserIDFromTokenMock.defaultExpectation != nil && afterGetUserIDFromTokenCounter < 1 {
		if m.GetUserIDFromTokenMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to AuthServiceMock.GetUserIDFromToken at\n%s", m.GetUserIDFromTokenMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to AuthServiceMock.GetUserIDFromToken at\n%s with params: %#v", m.GetUserIDFromTokenMock.defaultExpectation.expectationOrigins.origin, *m.GetUserIDFromTokenMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetUserIDFromToken != nil && afterGetUserIDFromTokenCounter < 1 {
		m.t.Errorf("Expected call to AuthServiceMock.GetUserIDFromToken at\n%s", m.funcGetUserIDFromTokenOrigin)
	}

	if !m.GetUserIDFromTokenMock.invocationsDone() && afterGetUserIDFromTokenCounter > 0 {
		m.t.Errorf("Expected %d calls to AuthServiceMock.GetUserIDFromToken at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetUserIDFromTokenMock.expectedInvocations), m.GetUserIDFromTokenMock.expectedInvocationsOrigin, afterGetUserIDFromTokenCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *AuthServiceMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockGetUserIDFromTokenInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *AuthServiceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *AuthServiceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockGetUserIDFromTokenDone()
}
