// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// ShorterMock implements mm_grpcserver.Shorter
type ShorterMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcCreate          func(ctx context.Context, long string) (s1 string, err error)
	funcCreateOrigin    string
	inspectFuncCreate   func(ctx context.Context, long string)
	afterCreateCounter  uint64
	beforeCreateCounter uint64
	CreateMock          mShorterMockCreate

	funcCreateShortURL          func(shortID string) (s1 string)
	funcCreateShortURLOrigin    string
	inspectFuncCreateShortURL   func(shortID string)
	afterCreateShortURLCounter  uint64
	beforeCreateShortURLCounter uint64
	CreateShortURLMock          mShorterMockCreateShortURL
}

// NewShorterMock returns a mock for mm_grpcserver.Shorter
func NewShorterMock(t minimock.Tester) *ShorterMock {
	m := &ShorterMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CreateMock = mShorterMockCreate{mock: m}
	m.CreateMock.callArgs = []*ShorterMockCreateParams{}

	m.CreateShortURLMock = mShorterMockCreateShortURL{mock: m}
	m.CreateShortURLMock.callArgs = []*ShorterMockCreateShortURLParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mShorterMockCreate struct {
	optional           bool
	mock               *ShorterMock
	defaultExpectation *ShorterMockCreateExpectation
	expectations       []*ShorterMockCreateExpectation

	callArgs []*ShorterMockCreateParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// ShorterMockCreateExpectation specifies expectation struct of the Shorter.Create
type ShorterMockCreateExpectation struct {
	mock               *ShorterMock
	params             *ShorterMockCreateParams
	paramPtrs          *ShorterMockCreateParamPtrs
	expectationOrigins ShorterMockCreateExpectationOrigins
	results            *ShorterMockCreateResults
	returnOrigin       string
	Counter            uint64
}

// ShorterMockCreateParams contains parameters of the Shorter.Create
type ShorterMockCreateParams struct {
	ctx  context.Context
	long string
}

// ShorterMockCreateParamPtrs contains pointers to parameters of the Shorter.Create
type ShorterMockCreateParamPtrs struct {
	ctx  *context.Context
	long *string
}

// ShorterMockCreateResults contains results of the Shorter.Create
type ShorterMockCreateResults struct {
	s1  string
	err error
}

// ShorterMockCreateOrigins contains origins of expectations of the Shorter.Create
type ShorterMockCreateExpectationOrigins struct {
	origin     string
	originCtx  string
	originLong string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCreate *mShorterMockCreate) Optional() *mShorterMockCreate {
	mmCreate.optional = true
	return mmCreate
}

// Expect sets up expected params for Shorter.Create
func (mmCreate *mShorterMockCreate) Expect(ctx context.Context, long string) *mShorterMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("ShorterMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &ShorterMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.paramPtrs != nil {
		mmCreate.mock.t.Fatalf("ShorterMock.Create mock is already set by ExpectParams functions")
	}

	mmCreate.defaultExpectation.params = &ShorterMockCreateParams{ctx, long}
	mmCreate.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCreate.expectations {
		if minimock.Equal(e.params, mmCreate.defaultExpectation.params) {
			mmCreate.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreate.defaultExpectation.params)
		}
	}

	return mmCreate
}

// ExpectCtxParam1 sets up expected param ctx for Shorter.Create
func (mmCreate *mShorterMockCreate) ExpectCtxParam1(ctx context.Context) *mShorterMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("ShorterMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &ShorterMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("ShorterMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &ShorterMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.ctx = &ctx
	mmCreate.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmCreate
}

// ExpectLongParam2 sets up expected param long for Shorter.Create
func (mmCreate *mShorterMockCreate) ExpectLongParam2(long string) *mShorterMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("ShorterMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &ShorterMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("ShorterMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &ShorterMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.long = &long
	mmCreate.defaultExpectation.expectationOrigins.originLong = minimock.CallerInfo(1)

	return mmCreate
}

// Inspect accepts an inspector function that has same arguments as the Shorter.Create
func (mmCreate *mShorterMockCreate) Inspect(f func(ctx context.Context, long string)) *mShorterMockCreate {
	if mmCreate.mock.inspectFuncCreate != nil {
		mmCreate.mock.t.Fatalf("Inspect function is already set for ShorterMock.Create")
	}

	mmCreate.mock.inspectFuncCreate = f

	return mmCreate
}

// Return sets up results that will be returned by Shorter.Create
func (mmCreate *mShorterMockCreate) Return(s1 string, err error) *ShorterMock {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("ShorterMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &ShorterMockCreateExpectation{mock: mmCreate.mock}
	}
	mmCreate.defaultExpectation.results = &ShorterMockCreateResults{s1, err}
	mmCreate.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCreate.mock
}

// Set uses given function f to mock the Shorter.Create method
func (mmCreate *mShorterMockCreate) Set(f func(ctx context.Context, long string) (s1 string, err error)) *ShorterMock {
	if mmCreate.defaultExpectation != nil {
		mmCreate.mock.t.Fatalf("Default expectation is already set for the Shorter.Create method")
	}

	if len(mmCreate.expectations) > 0 {
		mmCreate.mock.t.Fatalf("Some expectations are already set for the Shorter.Create method")
	}

	mmCreate.mock.funcCreate = f
	mmCreate.mock.funcCreateOrigin = minimock.CallerInfo(1)
	return mmCreate.mock
}

// When sets expectation for the Shorter.Create which will trigger the result defined by the following
// Then helper
func (mmCreate *mShorterMockCreate) When(ctx context.Context, long string) *ShorterMockCreateExpectation {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("ShorterMock.Create mock is already set by Set")
	}

	expectation := &ShorterMockCreateExpectation{
		mock:               mmCreate.mock,
		params:             &ShorterMockCreateParams{ctx, long},
		expectationOrigins: ShorterMockCreateExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCreate.expectations = append(mmCreate.expectations, expectation)
	return expectation
}

// Then sets up Shorter.Create return parameters for the expectation previously defined by the When method
func (e *ShorterMockCreateExpectation) Then(s1 string, err error) *ShorterMock {
	e.results = &ShorterMockCreateResults{s1, err}
	return e.mock
}

// Times sets number of times Shorter.Create should be invoked
func (mmCreate *mShorterMockCreate) Times(n uint64) *mShorterMockCreate {
	if n == 0 {
		mmCreate.mock.t.Fatalf("Times of ShorterMock.Create mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCreate.expectedInvocations, n)
	mmCreate.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCreate
}

func (mmCreate *mShorterMockCreate) invocationsDone() bool {
	if len(mmCreate.expectations) == 0 && mmCreate.defaultExpectation == nil && mmCreate.mock.funcCreate == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCreate.mock.afterCreateCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCreate.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Create implements mm_grpcserver.Shorter
func (mmCreate *ShorterMock) Create(ctx context.Context, long string) (s1 string, err error) {
	mm_atomic.AddUint64(&mmCreate.beforeCreateCounter, 1)
	defer mm_atomic.AddUint64(&mmCreate.afterCreateCounter, 1)

	mmCreate.t.Helper()

	if mmCreate.inspectFuncCreate != nil {
		mmCreate.inspectFuncCreate(ctx, long)
	}

	mm_params := ShorterMockCreateParams{ctx, long}

	// Record call args
	mmCreate.CreateMock.mutex.Lock()
	mmCreate.CreateMock.callArgs = append(mmCreate.CreateMock.callArgs, &mm_params)
	mmCreate.CreateMock.mutex.Unlock()

	for _, e := range mmCreate.CreateMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.s1, e.results.err
		}
	}

	if mmCreate.CreateMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreate.CreateMock.defaultExpectation.Counter, 1)
		mm_want := mmCreate.CreateMock.defaultExpectation.params
		mm_want_ptrs := mmCreate.CreateMock.defaultExpectation.paramPtrs

		mm_got := ShorterMockCreateParams{ctx, long}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCreate.t.Errorf("ShorterMock.Create got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreate.CreateMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.long != nil && !minimock.Equal(*mm_want_ptrs.long, mm_got.long) {
				mmCreate.t.Errorf("ShorterMock.Create got unexpected parameter long, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreate.CreateMock.defaultExpectation.expectationOrigins.originLong, *mm_want_ptrs.long, mm_got.long, minimock.Diff(*mm_want_ptrs.long, mm_got.long))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreate.t.Errorf("ShorterMock.Create got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCreate.CreateMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreate.CreateMock.defaultExpectation.results
		if mm_results == nil {
			mmCreate.t.Fatal("No results are set for the ShorterMock.Create")
		}
		return (*mm_results).s1, (*mm_results).err
	}
	if mmCreate.funcCreate != nil {
		return mmCreate.funcCreate(ctx, long)
	}
	mmCreate.t.Fatalf("Unexpected call to ShorterMock.Create. %v %v", ctx, long)
	return
}

// CreateAfterCounter returns a count of finished ShorterMock.Create invocations
func (mmCreate *ShorterMock) CreateAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.afterCreateCounter)
}

// CreateBeforeCounter returns a count of ShorterMock.Create invocations
func (mmCreate *ShorterMock) CreateBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.beforeCreateCounter)
}

// Calls returns a list of arguments used in each call to ShorterMock.Create.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreate *mShorterMockCreate) Calls() []*ShorterMockCreateParams {
	mmCreate.mutex.RLock()

	argCopy := make([]*ShorterMockCreateParams, len(mmCreate.callArgs))
	copy(argCopy, mmCreate.callArgs)

	mmCreate.mutex.RUnlock()

	return argCopy
}

// MinimockCreateDone returns true if the count of the Create invocations corresponds
// the number of defined expectations
func (m *ShorterMock) MinimockCreateDone() bool {
	if m.CreateMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CreateMock.invocationsDone()
}

// MinimockCreateInspect logs each unmet expectation
func (m *ShorterMock) MinimockCreateInspect() {
	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ShorterMock.Create at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCreateCounter := mm_atomic.LoadUint64(&m.afterCreateCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CreateMock.defaultExpectation != nil && afterCreateCounter < 1 {
		if m.CreateMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to ShorterMock.Create at\n%s", m.CreateMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to ShorterMock.Create at\n%s with params: %#v", m.CreateMock.defaultExpectation.expectationOrigins.origin, *m.CreateMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreate != nil && afterCreateCounter < 1 {
		m.t.Errorf("Expected call to ShorterMock.Create at\n%s", m.funcCreateOrigin)
	}

	if !m.CreateMock.invocationsDone() && afterCreateCounter > 0 {
		m.t.Errorf("Expected %d calls to ShorterMock.Create at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CreateMock.expectedInvocations), m.CreateMock.expectedInvocationsOrigin, afterCreateCounter)
	}
}

type mShorterMockCreateShortURL struct {
	optional           bool
	mock               *ShorterMock
	defaultExpectation *ShorterMockCreateShortURLExpectation
	expectations       []*ShorterMockCreateShortURLExpectation

	callArgs []*ShorterMockCreateShortURLParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// ShorterMockCreateShortURLExpectation specifies expectation struct of the Shorter.CreateShortURL
type ShorterMockCreateShortURLExpectation struct {
	mock               *ShorterMock
	params             *ShorterMockCreateShortURLParams
	paramPtrs          *ShorterMockCreateShortURLParamPtrs
	expectationOrigins ShorterMockCreateShortURLExpectationOrigins
	results            *ShorterMockCreateShortURLResults
	returnOrigin       string
	Counter            uint64
}

// ShorterMockCreateShortURLParams contains parameters of the Shorter.CreateShortURL
type ShorterMockCreateShortURLParams struct {
	shortID string
}

// ShorterMockCreateShortURLParamPtrs contains pointers to parameters of the Shorter.CreateShortURL
type ShorterMockCreateShortURLParamPtrs struct {
	shortID *string
}

// ShorterMockCreateShortURLResults contains results of the Shorter.CreateShortURL
type ShorterMockCreateShortURLResults struct {
	s1 string
}

// ShorterMockCreateShortURLOrigins contains origins of expectations of the Shorter.CreateShortURL
type ShorterMockCreateShortURLExpectationOrigins struct {
	origin        string
	originShortID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCreateShortURL *mShorterMockCreateShortURL) Optional() *mShorterMockCreateShortURL {
	mmCreateShortURL.optional = true
	return mmCreateShortURL
}

// Expect sets up expected params for Shorter.CreateShortURL
func (mmCreateShortURL *mShorterMockCreateShortURL) Expect(shortID string) *mShorterMockCreateShortURL {
	if mmCreateShortURL.mock.funcCreateShortURL != nil {
		mmCreateShortURL.mock.t.Fatalf("ShorterMock.CreateShortURL mock is already set by Set")
	}

	if mmCreateShortURL.defaultExpectation == nil {
		mmCreateShortURL.defaultExpectation = &ShorterMockCreateShortURLExpectation{}
	}

	if mmCreateShortURL.defaultExpectation.paramPtrs != nil {
		mmCreateShortURL.mock.t.Fatalf("ShorterMock.CreateShortURL mock is already set by ExpectParams functions")
	}

	mmCreateShortURL.defaultExpectation.params = &ShorterMockCreateShortURLParams{shortID}
	mmCreateShortURL.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCreateShortURL.expectations {
		if minimock.Equal(e.params, mmCreateShortURL.defaultExpectation.params) {
			mmCreateShortURL.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreateShortURL.defaultExpectation.params)
		}
	}

	return mmCreateShortURL
}

// ExpectShortIDParam1 sets up expected param shortID for Shorter.CreateShortURL
func (mmCreateShortURL *mShorterMockCreateShortURL) ExpectShortIDParam1(shortID string) *mShorterMockCreateShortURL {
	if mmCreateShortURL.mock.funcCreateShortURL != nil {
		mmCreateShortURL.mock.t.Fatalf("ShorterMock.CreateShortURL mock is already set by Set")
	}

	if mmCreateShortURL.defaultExpectation == nil {
		mmCreateShortURL.defaultExpectation = &ShorterMockCreateShortURLExpectation{}
	}

	if mmCreateShortURL.defaultExpectation.params != nil {
		mmCreateShortURL.mock.t.Fatalf("ShorterMock.CreateShortURL mock is already set by Expect")
	}

	if mmCreateShortURL.defaultExpectation.paramPtrs == nil {
		mmCreateShortURL.defaultExpectation.paramPtrs = &ShorterMockCreateShortURLParamPtrs{}
	}
	mmCreateShortURL.defaultExpectation.paramPtrs.shortID = &shortID
	mmCreateShortURL.defaultExpectation.expectationOrigins.originShortID = minimock.CallerInfo(1)

	return mmCreateShortURL
}

// Inspect accepts an inspector function that has same arguments as the Shorter.CreateShortURL
func (mmCreateShortURL *mShorterMockCreateShortURL) Inspect(f func(shortID string)) *mShorterMockCreateShortURL {
	if mmCreateShortURL.mock.inspectFuncCreateShortURL != nil {
		mmCreateShortURL.mock.t.Fatalf("Inspect function is already set for ShorterMock.CreateShortURL")
	}

	mmCreateShortURL.mock.inspectFuncCreateShortURL = f

	return mmCreateShortURL
}

// Return sets up results that will be returned by Shorter.CreateShortURL
func (mmCreateShortURL *mShorterMockCreateShortURL) Return(s1 string) *ShorterMock {
	if mmCreateShortURL.mock.funcCreateShortURL != nil {
		mmCreateShortURL.mock.t.Fatalf("ShorterMock.CreateShortURL mock is already set by Set")
	}

	if mmCreateShortURL.defaultExpectation == nil {
		mmCreateShortURL.defaultExpectation = &ShorterMockCreateShortURLExpectation{mock: mmCreateShortURL.mock}
	}
	mmCreateShortURL.defaultExpectation.results = &ShorterMockCreateShortURLResults{s1}
	mmCreateShortURL.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCreateShortURL.mock
}

// Set uses given function f to mock the Shorter.CreateShortURL method
func (mmCreateShortURL *mShorterMockCreateShortURL) Set(f func(shortID string) (s1 string)) *ShorterMock {
	if mmCreateShortURL.defaultExpectation != nil {
		mmCreateShortURL.mock.t.Fatalf("Default expectation is already set for the Shorter.CreateShortURL method")
	}

	if len(mmCreateShortURL.expectations) > 0 {
		mmCreateShortURL.mock.t.Fatalf("Some expectations are already set for the Shorter.CreateShortURL method")
	}

	mmCreateShortURL.mock.funcCreateShortURL = f
	mmCreateShortURL.mock.funcCreateShortURLOrigin = minimock.CallerInfo(1)
	return mmCreateShortURL.mock
}

// When sets expectation for the Shorter.CreateShortURL which will trigger the result defined by the following
// Then helper
func (mmCreateShortURL *mShorterMockCreateShortURL) When(shortID string) *ShorterMockCreateShortURLExpectation {
	if mmCreateShortURL.mock.funcCreateShortURL != nil {
		mmCreateShortURL.mock.t.Fatalf("ShorterMock.CreateShortURL mock is already set by Set")
	}

	expectation := &ShorterMockCreateShortURLExpectation{
		mock:               mmCreateShortURL.mock,
		params:             &ShorterMockCreateShortURLParams{shortID},
		expectationOrigins: ShorterMockCreateShortURLExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCreateShortURL.expectations = append(mmCreateShortURL.expectations, expectation)
	return expectation
}

// Then sets up Shorter.CreateShortURL return parameters for the expectation previously defined by the When method
func (e *ShorterMockCreateShortURLExpectation) Then(s1 string) *ShorterMock {
	e.results = &ShorterMockCreateShortURLResults{s1}
	return e.mock
}

// Times sets number of times Shorter.CreateShortURL should be invoked
func (mmCreateShortURL *mShorterMockCreateShortURL) Times(n uint64) *mShorterMockCreateShortURL {
	if n == 0 {
		mmCreateShortURL.mock.t.Fatalf("Times of ShorterMock.CreateShortURL mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCreateShortURL.expectedInvocations, n)
	mmCreateShortURL.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCreateShortURL
}

func (mmCreateShortURL *mShorterMockCreateShortURL) invocationsDone() bool {
	if len(mmCreateShortURL.expectations) == 0 && mmCreateShortURL.defaultExpectation == nil && mmCreateShortURL.mock.funcCreateShortURL == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCreateShortURL.mock.afterCreateShortURLCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCreateShortURL.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// CreateShortURL implements mm_grpcserver.Shorter
func (mmCreateShortURL *ShorterMock) CreateShortURL(shortID string) (s1 string) {
	mm_atomic.AddUint64(&mmCreateShortURL.beforeCreateShortURLCounter, 1)
	defer mm_atomic.AddUint64(&mmCreateShortURL.afterCreateShortURLCounter, 1)

	mmCreateShortURL.t.Helper()

	if mmCreateShortURL.inspectFuncCreateShortURL != nil {
		mmCreateShortURL.inspectFuncCreateShortURL(shortID)
	}

	mm_params := ShorterMockCreateShortURLParams{shortID}

	// Record call args
	mmCreateShortURL.CreateShortURLMock.mutex.Lock()
	mmCreateShortURL.CreateShortURLMock.callArgs = append(mmCreateShortURL.CreateShortURLMock.callArgs, &mm_params)
	mmCreateShortURL.CreateShortURLMock.mutex.Unlock()

	for _, e := range mmCreateShortURL.CreateShortURLMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.s1
		}
	}

	if mmCreateShortURL.CreateShortURLMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreateShortURL.CreateShortURLMock.defaultExpectation.Counter, 1)
		mm_want := mmCreateShortURL.CreateShortURLMock.defaultExpectation.params
		mm_want_ptrs := mmCreateShortURL.CreateShortURLMock.defaultExpectation.paramPtrs

		mm_got := ShorterMockCreateShortURLParams{shortID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.shortID != nil && !minimock.Equal(*mm_want_ptrs.shortID, mm_got.shortID) {
				mmCreateShortURL.t.Errorf("ShorterMock.CreateShortURL got unexpected parameter shortID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateShortURL.CreateShortURLMock.defaultExpectation.expectationOrigins.originShortID, *mm_want_ptrs.shortID, mm_got.shortID, minimock.Diff(*mm_want_ptrs.shortID, mm_got.shortID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreateShortURL.t.Errorf("ShorterMock.CreateShortURL got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCreateShortURL.CreateShortURLMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreateShortURL.CreateShortURLMock.defaultExpectation.results
		if mm_results == nil {
			mmCreateShortURL.t.Fatal("No results are set for the ShorterMock.CreateShortURL")
		}
		return (*mm_results).s1
	}
	if mmCreateShortURL.funcCreateShortURL != nil {
		return mmCreateShortURL.funcCreateShortURL(shortID)
	}
	mmCreateShortURL.t.Fatalf("Unexpected call to ShorterMock.CreateShortURL. %v", shortID)
	return
}

// CreateShortURLAfterCounter returns a count of finished ShorterMock.CreateShortURL invocations
func (mmCreateShortURL *ShorterMock) CreateShortURLAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateShortURL.afterCreateShortURLCounter)
}

// CreateShortURLBeforeCounter returns a count of ShorterMock.CreateShortURL invocations
func (mmCreateShortURL *ShorterMock) CreateShortURLBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateShortURL.beforeCreateShortURLCounter)
}

// Calls returns a list of arguments used in each call to ShorterMock.CreateShortURL.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreateShortURL *mShorterMockCreateShortURL) Calls() []*ShorterMockCreateShortURLParams {
	mmCreateShortURL.mutex.RLock()

	argCopy := make([]*ShorterMockCreateShortURLParams, len(mmCreateShortURL.callArgs))
	copy(argCopy, mmCreateShortURL.callArgs)

	mmCreateShortURL.mutex.RUnlock()

	return argCopy
}

// MinimockCreateShortURLDone returns true if the count of the CreateShortURL invocations corresponds
// the number of defined expectations
func (m *ShorterMock) MinimockCreateShortURLDone() bool {
	if m.CreateShortURLMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CreateShortURLMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CreateShortURLMock.invocationsDone()
}

// MinimockCreateShortURLInspect logs each unmet expectation
func (m *ShorterMock) MinimockCreateShortURLInspect() {
	for _, e := range m.CreateShortURLMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ShorterMock.CreateShortURL at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCreateShortURLCounter := mm_atomic.LoadUint64(&m.afterCreateShortURLCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CreateShortURLMock.defaultExpectation != nil && afterCreateShortURLCounter < 1 {
		if m.CreateShortURLMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to ShorterMock.CreateShortURL at\n%s", m.CreateShortURLMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to ShorterMock.CreateShortURL at\n%s with params: %#v", m.CreateShortURLMock.defaultExpectation.expectationOrigins.origin, *m.CreateShortURLMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreateShortURL != nil && afterCreateShortURLCounter < 1 {
		m.t.Errorf("Expected call to ShorterMock.CreateShortURL at\n%s", m.funcCreateShortURLOrigin)
	}

	if !m.CreateShortURLMock.invocationsDone() && afterCreateShortURLCounter > 0 {
		m.t.Errorf("Expected %d calls to ShorterMock.CreateShortURL at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CreateShortURLMock.expectedInvocations), m.CreateShortURLMock.expectedInvocationsOrigin, afterCreateShortURLCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *ShorterMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCreateInspect()

			m.MinimockCreateShortURLInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *ShorterMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *ShorterMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCreateDone() &&
		m.MinimockCreateShortURLDone()
}
