// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// UrlsKeeperMock implements mm_grpcserver.UrlsKeeper
type UrlsKeeperMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcGet          func(ctx context.Context, shortURL string) (url string, found bool, err error)
	funcGetOrigin    string
	inspectFuncGet   func(ctx context.Context, shortURL string)
	afterGetCounter  uint64
	beforeGetCounter uint64
	GetMock          mUrlsKeeperMockGet

	funcGetAllByUser          func(ctx context.Context, userID string) (urls map[string]string, err error)
	funcGetAllByUserOrigin    string
	inspectFuncGetAllByUser   func(ctx context.Context, userID string)
	afterGetAllByUserCounter  uint64
	beforeGetAllByUserCounter uint64
	GetAllByUserMock          mUrlsKeeperMockGetAllByUser
}

// NewUrlsKeeperMock returns a mock for mm_grpcserver.UrlsKeeper
func NewUrlsKeeperMock(t minimock.Tester) *UrlsKeeperMock {
	m := &UrlsKeeperMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.GetMock = mUrlsKeeperMockGet{mock: m}
	m.GetMock.callArgs = []*UrlsKeeperMockGetParams{}

	m.GetAllByUserMock = mUrlsKeeperMockGetAllByUser{mock: m}
	m.GetAllByUserMock.callArgs = []*UrlsKeeperMockGetAllByUserParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mUrlsKeeperMockGet struct {
	optional           bool
	mock               *UrlsKeeperMock
	defaultExpectation *UrlsKeeperMockGetExpectation
	expectations       []*UrlsKeeperMockGetExpectation

	callArgs []*UrlsKeeperMockGetParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// UrlsKeeperMockGetExpectation specifies expectation struct of the UrlsKeeper.Get
type UrlsKeeperMockGetExpectation struct {
	mock               *UrlsKeeperMock
	params             *UrlsKeeperMockGetParams
	paramPtrs          *UrlsKeeperMockGetParamPtrs
	expectationOrigins UrlsKeeperMockGetExpectationOrigins
	results            *UrlsKeeperMockGetResults
	returnOrigin       string
	Counter            uint64
}

// UrlsKeeperMockGetParams contains parameters of the UrlsKeeper.Get
type UrlsKeeperMockGetParams struct {
	ctx      context.Context
	shortURL string
}

// UrlsKeeperMockGetParamPtrs contains pointers to parameters of the UrlsKeeper.Get
type UrlsKeeperMockGetParamPtrs struct {
	ctx      *context.Context
	shortURL *string
}

// UrlsKeeperMockGetResults contains results of the UrlsKeeper.Get
type UrlsKeeperMockGetResults struct {
	url   string
	found bool
	err   error
}

// UrlsKeeperMockGetOrigins contains origins of expectations of the UrlsKeeper.Get
type UrlsKeeperMockGetExpectationOrigins struct {
	origin         string
	originCtx      string
	originShortURL string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGet *mUrlsKeeperMockGet) Optional() *mUrlsKeeperMockGet {
	mmGet.optional = true
	return mmGet
}

// Expect sets up expected params for UrlsKeeper.Get
func (mmGet *mUrlsKeeperMockGet) Expect(ctx context.Context, shortURL string) *mUrlsKeeperMockGet {
	if mmGet.mock.funcGet != nil {
		mmGet.mock.t.Fatalf("UrlsKeeperMock.Get mock is already set by Set")
	}

	if mmGet.defaultExpectation == nil {
		mmGet.defaultExpectation = &UrlsKeeperMockGetExpectation{}
	}

	if mmGet.defaultExpectation.paramPtrs != nil {
		mmGet.mock.t.Fatalf("UrlsKeeperMock.Get mock is already set by ExpectParams functions")
	}

	mmGet.defaultExpectation.params = &UrlsKeeperMockGetParams{ctx, shortURL}
	mmGet.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGet.expectations {
		if minimock.Equal(e.params, mmGet.defaultExpectation.params) {
			mmGet.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGet.defaultExpectation.params)
		}
	}

	return mmGet
}

// ExpectCtxParam1 sets up expected param ctx for UrlsKeeper.Get
func (mmGet *mUrlsKeeperMockGet) ExpectCtxParam1(ctx context.Context) *mUrlsKeeperMockGet {
	if mmGet.mock.funcGet != nil {
		mmGet.mock.t.Fatalf("UrlsKeeperMock.Get mock is already set by Set")
	}

	if mmGet.defaultExpectation == nil {
		mmGet.defaultExpectation = &UrlsKeeperMockGetExpectation{}
	}

	if mmGet.defaultExpectation.params != nil {
		mmGet.mock.t.Fatalf("UrlsKeeperMock.Get mock is already set by Expect")
	}

	if mmGet.defaultExpectation.paramPtrs == nil {
		mmGet.defaultExpectation.paramPtrs = &UrlsKeeperMockGetParamPtrs{}
	}
	mmGet.defaultExpectation.paramPtrs.ctx = &ctx
	mmGet.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGet
}

// ExpectShortURLParam2 sets up expected param shortURL for UrlsKeeper.Get
func (mmGet *mUrlsKeeperMockGet) ExpectShortURLParam2(shortURL string) *mUrlsKeeperMockGet {
	if mmGet.mock.funcGet != nil {
		mmGet.mock.t.Fatalf("UrlsKeeperMock.Get mock is already set by Set")
	}

	if mmGet.defaultExpectation == nil {
		mmGet.defaultExpectation = &UrlsKeeperMockGetExpectation{}
	}

	if mmGet.defaultExpectation.params != nil {
		mmGet.mock.t.Fatalf("UrlsKeeperMock.Get mock is already set by Expect")
	}

	if mmGet.defaultExpectation.paramPtrs == nil {
		mmGet.defaultExpectation.paramPtrs = &UrlsKeeperMockGetParamPtrs{}
	}
	mmGet.defaultExpectation.paramPtrs.shortURL = &shortURL
	mmGet.defaultExpectation.expectationOrigins.originShortURL = minimock.CallerInfo(1)

	return mmGet
}

// Inspect accepts an inspector function that has same arguments as the UrlsKeeper.Get
func (mmGet *mUrlsKeeperMockGet) Inspect(f func(ctx context.Context, shortURL string)) *mUrlsKeeperMockGet {
	if mmGet.mock.inspectFuncGet != nil {
		mmGet.mock.t.Fatalf("Inspect function is already set for UrlsKeeperMock.Get")
	}

	mmGet.mock.inspectFuncGet = f

	return mmGet
}

// Return sets up results that will be returned by UrlsKeeper.Get
func (mmGet *mUrlsKeeperMockGet) Return(url string, found bool, err error) *UrlsKeeperMock {
	if mmGet.mock.funcGet != nil {
		mmGet.mock.t.Fatalf("UrlsKeeperMock.Get mock is already set by Set")
	}

	if mmGet.defaultExpectation == nil {
		mmGet.defaultExpectation = &UrlsKeeperMockGetExpectation{mock: mmGet.mock}
	}
	mmGet.defaultExpectation.results = &UrlsKeeperMockGetResults{url, found, err}
	mmGet.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGet.mock
}

// Set uses given function f to mock the UrlsKeeper.Get method
func (mmGet *mUrlsKeeperMockGet) Set(f func(ctx context.Context, shortURL string) (url string, found bool, err error)) *UrlsKeeperMock {
	if mmGet.defaultExpectation != nil {
		mmGet.mock.t.Fatalf("Default expectation is already set for the UrlsKeeper.Get method")
	}

	if len(mmGet.expectations) > 0 {
		mmGet.mock.t.Fatalf("Some expectations are already set for the UrlsKeeper.Get method")
	}

	mmGet.mock.funcGet = f
	mmGet.mock.funcGetOrigin = minimock.CallerInfo(1)
	return mmGet.mock
}

// When sets expectation for the UrlsKeeper.Get which will trigger the result defined by the following
// Then helper
func (mmGet *mUrlsKeeperMockGet) When(ctx context.Context, shortURL string) *UrlsKeeperMockGetExpectation {
	if mmGet.mock.funcGet != nil {
		mmGet.mock.t.Fatalf("UrlsKeeperMock.Get mock is already set by Set")
	}

	expectation := &UrlsKeeperMockGetExpectation{
		mock:               mmGet.mock,
		params:             &UrlsKeeperMockGetParams{ctx, shortURL},
		expectationOrigins: UrlsKeeperMockGetExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGet.expectations = append(mmGet.expectations, expectation)
	return expectation
}

// Then sets up UrlsKeeper.Get return parameters for the expectation previously defined by the When method
func (e *UrlsKeeperMockGetExpectation) Then(url string, found bool, err error) *UrlsKeeperMock {
	e.results = &UrlsKeeperMockGetResults{url, found, err}
	return e.mock
}

// Times sets number of times UrlsKeeper.Get should be invoked
func (mmGet *mUrlsKeeperMockGet) Times(n uint64) *mUrlsKeeperMockGet {
	if n == 0 {
		mmGet.mock.t.Fatalf("Times of UrlsKeeperMock.Get mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGet.expectedInvocations, n)
	mmGet.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGet
}

func (mmGet *mUrlsKeeperMockGet) invocationsDone() bool {
	if len(mmGet.expectations) == 0 && mmGet.defaultExpectation == nil && mmGet.mock.funcGet == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGet.mock.afterGetCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGet.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Get implements mm_grpcserver.UrlsKeeper
func (mmGet *UrlsKeeperMock) Get(ctx context.Context, shortURL string) (url string, found bool, err error) {
	mm_atomic.AddUint64(&mmGet.beforeGetCounter, 1)
	defer mm_atomic.AddUint64(&mmGet.afterGetCounter, 1)

	mmGet.t.Helper()

	if mmGet.inspectFuncGet != nil {
		mmGet.inspectFuncGet(ctx, shortURL)
	}

	mm_params := UrlsKeeperMockGetParams{ctx, shortURL}

	// Record call args
	mmGet.GetMock.mutex.Lock()
	mmGet.GetMock.callArgs = append(mmGet.GetMock.callArgs, &mm_params)
	mmGet.GetMock.mutex.Unlock()

	for _, e := range mmGet.GetMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.url, e.results.found, e.results.err
		}
	}

	if mmGet.GetMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGet.GetMock.defaultExpectation.Counter, 1)
		mm_want := mmGet.GetMock.defaultExpectation.params
		mm_want_ptrs := mmGet.GetMock.defaultExpectation.paramPtrs

		mm_got := UrlsKeeperMockGetParams{ctx, shortURL}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGet.t.Errorf("UrlsKeeperMock.Get got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGet.GetMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.shortURL != nil && !minimock.Equal(*mm_want_ptrs.shortURL, mm_got.shortURL) {
				mmGet.t.Errorf("UrlsKeeperMock.Get got unexpected parameter shortURL, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGet.GetMock.defaultExpectation.expectationOrigins.originShortURL, *mm_want_ptrs.shortURL, mm_got.shortURL, minimock.Diff(*mm_want_ptrs.shortURL, mm_got.shortURL))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGet.t.Errorf("UrlsKeeperMock.Get got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGet.GetMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGet.GetMock.defaultExpectation.results
		if mm_results == nil {
			mmGet.t.Fatal("No results are set for the UrlsKeeperMock.Get")
		}
		return (*mm_results).url, (*mm_results).found, (*mm_results).err
	}
	if mmGet.funcGet != nil {
		return mmGet.funcGet(ctx, shortURL)
	}
	mmGet.t.Fatalf("Unexpected call to UrlsKeeperMock.Get. %v %v", ctx, shortURL)
	return
}

// GetAfterCounter returns a count of finished UrlsKeeperMock.Get invocations
func (mmGet *UrlsKeeperMock) GetAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGet.afterGetCounter)
}

// GetBeforeCounter returns a count of UrlsKeeperMock.Get invocations
func (mmGet *UrlsKeeperMock) GetBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGet.beforeGetCounter)
}

// Calls returns a list of arguments used in each call to UrlsKeeperMock.Get.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGet *mUrlsKeeperMockGet) Calls() []*UrlsKeeperMockGetParams {
	mmGet.mutex.RLock()

	argCopy := make([]*UrlsKeeperMockGetParams, len(mmGet.callArgs))
	copy(argCopy, mmGet.callArgs)

	mmGet.mutex.RUnlock()

	return argCopy
}

// MinimockGetDone returns true if the count of the Get invocations corresponds
// the number of defined expectations
func (m *UrlsKeeperMock) MinimockGetDone() bool {
	if m.GetMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetMock.invocationsDone()
}

// MinimockGetInspect logs each unmet expectation
func (m *UrlsKeeperMock) MinimockGetInspect() {
	for _, e := range m.GetMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UrlsKeeperMock.Get at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetCounter := mm_atomic.LoadUint64(&m.afterGetCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetMock.defaultExpectation != nil && afterGetCounter < 1 {
		if m.GetMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to UrlsKeeperMock.Get at\n%s", m.GetMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to UrlsKeeperMock.Get at\n%s with params: %#v", m.GetMock.defaultExpectation.expectationOrigins.origin, *m.GetMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGet != nil && afterGetCounter < 1 {
		m.t.Errorf("Expected call to UrlsKeeperMock.Get at\n%s", m.funcGetOrigin)
	}

	if !m.GetMock.invocationsDone() && afterGetCounter > 0 {
		m.t.Errorf("Expected %d calls to UrlsKeeperMock.Get at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetMock.expectedInvocations), m.GetMock.expectedInvocationsOrigin, afterGetCounter)
	}
}

type mUrlsKeeperMockGetAllByUser struct {
	optional           bool
	mock               *UrlsKeeperMock
	defaultExpectation *UrlsKeeperMockGetAllByUserExpectation
	expectations       []*UrlsKeeperMockGetAllByUserExpectation

	callArgs []*UrlsKeeperMockGetAllByUserParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// UrlsKeeperMockGetAllByUserExpectation specifies expectation struct of the UrlsKeeper.GetAllByUser
type UrlsKeeperMockGetAllByUserExpectation struct {
	mock               *UrlsKeeperMock
	params             *UrlsKeeperMockGetAllByUserParams
	paramPtrs          *UrlsKeeperMockGetAllByUserParamPtrs
	expectationOrigins UrlsKeeperMockGetAllByUserExpectationOrigins
	results            *UrlsKeeperMockGetAllByUserResults
	returnOrigin       string
	Counter            uint64
}

// UrlsKeeperMockGetAllByUserParams contains parameters of the UrlsKeeper.GetAllByUser
type UrlsKeeperMockGetAllByUserParams struct {
	ctx    context.Context
	userID string
}

// UrlsKeeperMockGetAllByUserParamPtrs contains pointers to parameters of the UrlsKeeper.GetAllByUser
type UrlsKeeperMockGetAllByUserParamPtrs struct {
	ctx    *context.Context
	userID *string
}

// UrlsKeeperMockGetAllByUserResults contains results of the UrlsKeeper.GetAllByUser
type UrlsKeeperMockGetAllByUserResults struct {
	urls map[string]string
	err  error
}

// UrlsKeeperMockGetAllByUserOrigins contains origins of expectations of the UrlsKeeper.GetAllByUser
type UrlsKeeperMockGetAllByUserExpectationOrigins struct {
	origin       string
	originCtx    string
	originUserID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetAllByUser *mUrlsKeeperMockGetAllByUser) Optional() *mUrlsKeeperMockGetAllByUser {
	mmGetAllByUser.optional = true
	return mmGetAllByUser
}

// Expect sets up expected params for UrlsKeeper.GetAllByUser
func (mmGetAllByUser *mUrlsKeeperMockGetAllByUser) Expect(ctx context.Context, userID string) *mUrlsKeeperMockGetAllByUser {
	if mmGetAllByUser.mock.funcGetAllByUser != nil {
		mmGetAllByUser.mock.t.Fatalf("UrlsKeeperMock.GetAllByUser mock is already set by Set")
	}

	if mmGetAllByUser.defaultExpectation == nil {
		mmGetAllByUser.defaultExpectation = &UrlsKeeperMockGetAllByUserExpectation{}
	}

	if mmGetAllByUser.defaultExpectation.paramPtrs != nil {
		mmGetAllByUser.mock.t.Fatalf("UrlsKeeperMock.GetAllByUser mock is already set by ExpectParams functions")
	}

	mmGetAllByUser.defaultExpectation.params = &UrlsKeeperMockGetAllByUserParams{ctx, userID}
	mmGetAllByUser.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetAllByUser.expectations {
		if minimock.Equal(e.params, mmGetAllByUser.defaultExpectation.params) {
			mmGetAllByUser.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetAllByUser.defaultExpectation.params)
		}
	}

	return mmGetAllByUser
}

// ExpectCtxParam1 sets up expected param ctx for UrlsKeeper.GetAllByUser
func (mmGetAllByUser *mUrlsKeeperMockGetAllByUser) ExpectCtxParam1(ctx context.Context) *mUrlsKeeperMockGetAllByUser {
	if mmGetAllByUser.mock.funcGetAllByUser != nil {
		mmGetAllByUser.mock.t.Fatalf("UrlsKeeperMock.GetAllByUser mock is already set by Set")
	}

	if mmGetAllByUser.defaultExpectation == nil {
		mmGetAllByUser.defaultExpectation = &UrlsKeeperMockGetAllByUserExpectation{}
	}

	if mmGetAllByUser.defaultExpectation.params != nil {
		mmGetAllByUser.mock.t.Fatalf("UrlsKeeperMock.GetAllByUser mock is already set by Expect")
	}

	if mmGetAllByUser.defaultExpectation.paramPtrs == nil {
		mmGetAllByUser.defaultExpectation.paramPtrs = &UrlsKeeperMockGetAllByUserParamPtrs{}
	}
	mmGetAllByUser.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetAllByUser.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetAllByUser
}

// ExpectUserIDParam2 sets up expected param userID for UrlsKeeper.GetAllByUser
func (mmGetAllByUser *mUrlsKeeperMockGetAllByUser) ExpectUserIDParam2(userID string) *mUrlsKeeperMockGetAllByUser {
	if mmGetAllByUser.mock.funcGetAllByUser != nil {
		mmGetAllByUser.mock.t.Fatalf("UrlsKeeperMock.GetAllByUser mock is already set by Set")
	}

	if mmGetAllByUser.defaultExpectation == nil {
		mmGetAllByUser.defaultExpectation = &UrlsKeeperMockGetAllByUserExpectation{}
	}

	if mmGetAllByUser.defaultExpectation.params != nil {
		mmGetAllByUser.mock.t.Fatalf("UrlsKeeperMock.GetAllByUser mock is already set by Expect")
	}

	if mmGetAllByUser.defaultExpectation.paramPtrs == nil {
		mmGetAllByUser.defaultExpectation.paramPtrs = &UrlsKeeperMockGetAllByUserParamPtrs{}
	}
	mmGetAllByUser.defaultExpectation.paramPtrs.userID = &userID
	mmGetAllByUser.defaultExpectation.expectationOrigins.originUserID = minimock.CallerInfo(1)

	return mmGetAllByUser
}

// Inspect accepts an inspector function that has same arguments as the UrlsKeeper.GetAllByUser
func (mmGetAllByUser *mUrlsKeeperMockGetAllByUser) Inspect(f func(ctx context.Context, userID string)) *mUrlsKeeperMockGetAllByUser {
	if mmGetAllByUser.mock.inspectFuncGetAllByUser != nil {
		mmGetAllByUser.mock.t.Fatalf("Inspect function is already set for UrlsKeeperMock.GetAllByUser")
	}

	mmGetAllByUser.mock.inspectFuncGetAllByUser = f

	return mmGetAllByUser
}

// Return sets up results that will be returned by UrlsKeeper.GetAllByUser
func (mmGetAllByUser *mUrlsKeeperMockGetAllByUser) Return(urls map[string]string, err error) *UrlsKeeperMock {
	if mmGetAllByUser.mock.funcGetAllByUser != nil {
		mmGetAllByUser.mock.t.Fatalf("UrlsKeeperMock.GetAllByUser mock is already set by Set")
	}

	if mmGetAllByUser.defaultExpectation == nil {
		mmGetAllByUser.defaultExpectation = &UrlsKeeperMockGetAllByUserExpectation{mock: mmGetAllByUser.mock}
	}
	mmGetAllByUser.defaultExpectation.results = &UrlsKeeperMockGetAllByUserResults{urls, err}
	mmGetAllByUser.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetAllByUser.mock
}

// Set uses given function f to mock the UrlsKeeper.GetAllByUser method
func (mmGetAllByUser *mUrlsKeeperMockGetAllByUser) Set(f func(ctx context.Context, userID string) (urls map[string]string, err error)) *UrlsKeeperMock {
	if mmGetAllByUser.defaultExpectation != nil {
		mmGetAllByUser.mock.t.Fatalf("Default expectation is already set for the UrlsKeeper.GetAllByUser method")
	}

	if len(mmGetAllByUser.expectations) > 0 {
		mmGetAllByUser.mock.t.Fatalf("Some expectations are already set for the UrlsKeeper.GetAllByUser method")
	}

	mmGetAllByUser.mock.funcGetAllByUser = f
	mmGetAllByUser.mock.funcGetAllByUserOrigin = minimock.CallerInfo(1)
	return mmGetAllByUser.mock
}

// When sets expectation for the UrlsKeeper.GetAllByUser which will trigger the result defined by the following
// Then helper
func (mmGetAllByUser *mUrlsKeeperMockGetAllByUser) When(ctx context.Context, userID string) *UrlsKeeperMockGetAllByUserExpectation {
	if mmGetAllByUser.mock.funcGetAllByUser != nil {
		mmGetAllByUser.mock.t.Fatalf("UrlsKeeperMock.GetAllByUser mock is already set by Set")
	}

	expectation := &UrlsKeeperMockGetAllByUserExpectation{
		mock:               mmGetAllByUser.mock,
		params:             &UrlsKeeperMockGetAllByUserParams{ctx, userID},
		expectationOrigins: UrlsKeeperMockGetAllByUserExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetAllByUser.expectations = append(mmGetAllByUser.expectations, expectation)
	return expectation
}

// Then sets up UrlsKeeper.GetAllByUser return parameters for the expectation previously defined by the When method
func (e *UrlsKeeperMockGetAllByUserExpectation) Then(urls map[string]string, err error) *UrlsKeeperMock {
	e.results = &UrlsKeeperMockGetAllByUserResults{urls, err}
	return e.mock
}

// Times sets number of times UrlsKeeper.GetAllByUser should be invoked
func (mmGetAllByUser *mUrlsKeeperMockGetAllByUser) Times(n uint64) *mUrlsKeeperMockGetAllByUser {
	if n == 0 {
		mmGetAllByUser.mock.t.Fatalf("Times of UrlsKeeperMock.GetAllByUser mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetAllByUser.expectedInvocations, n)
	mmGetAllByUser.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetAllByUser
}

func (mmGetAllByUser *mUrlsKeeperMockGetAllByUser) invocationsDone() bool {
	if len(mmGetAllByUser.expectations) == 0 && mmGetAllByUser.defaultExpectation == nil && mmGetAllByUser.mock.funcGetAllByUser == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetAllByUser.mock.afterGetAllByUserCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetAllByUser.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetAllByUser implements mm_grpcserver.UrlsKeeper
func (mmGetAllByUser *UrlsKeeperMock) GetAllByUser(ctx context.Context, userID string) (urls map[string]string, err error) {
	mm_atomic.AddUint64(&mmGetAllByUser.beforeGetAllByUserCounter, 1)
	defer mm_atomic.AddUint64(&mmGetAllByUser.afterGetAllByUserCounter, 1)

	mmGetAllByUser.t.Helper()

	if mmGetAllByUser.inspectFuncGetAllByUser != nil {
		mmGetAllByUser.inspectFuncGetAllByUser(ctx, userID)
	}

	mm_params := UrlsKeeperMockGetAllByUserParams{ctx, userID}

	// Record call args
	mmGetAllByUser.GetAllByUserMock.mutex.Lock()
	mmGetAllByUser.GetAllByUserMock.callArgs = append(mmGetAllByUser.GetAllByUserMock.callArgs, &mm_params)
	mmGetAllByUser.GetAllByUserMock.mutex.Unlock()

	for _, e := range mmGetAllByUser.GetAllByUserMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.urls, e.results.err
		}
	}

	if mmGetAllByUser.GetAllByUserMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetAllByUser.GetAllByUserMock.defaultExpectation.Counter, 1)
		mm_want := mmGetAllByUser.GetAllByUserMock.defaultExpectation.params
		mm_want_ptrs := mmGetAllByUser.GetAllByUserMock.defaultExpectation.paramPtrs

		mm_got := UrlsKeeperMockGetAllByUserParams{ctx, userID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetAllByUser.t.Errorf("UrlsKeeperMock.GetAllByUser got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetAllByUser.GetAllByUserMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.userID != nil && !minimock.Equal(*mm_want_ptrs.userID, mm_got.userID) {
				mmGetAllByUser.t.Errorf("UrlsKeeperMock.GetAllByUser got unexpected parameter userID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetAllByUser.GetAllByUserMock.defaultExpectation.expectationOrigins.originUserID, *mm_want_ptrs.userID, mm_got.userID, minimock.Diff(*mm_want_ptrs.userID, mm_got.userID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetAllByUser.t.Errorf("UrlsKeeperMock.GetAllByUser got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetAllByUser.GetAllByUserMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetAllByUser.GetAllByUserMock.defaultExpectation.results
		if mm_results == nil {
			mmGetAllByUser.t.Fatal("No results are set for the UrlsKeeperMock.GetAllByUser")
		}
		return (*mm_results).urls, (*mm_results).err
	}
	if mmGetAllByUser.funcGetAllByUser != nil {
		return mmGetAllByUser.funcGetAllByUser(ctx, userID)
	}
	mmGetAllByUser.t.Fatalf("Unexpected call to UrlsKeeperMock.GetAllByUser. %v %v", ctx, userID)
	return
}

// GetAllByUserAfterCounter returns a count of finished UrlsKeeperMock.GetAllByUser invocations
func (mmGetAllByUser *UrlsKeeperMock) GetAllByUserAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetAllByUser.afterGetAllByUserCounter)
}

// GetAllByUserBeforeCounter returns a count of UrlsKeeperMock.GetAllByUser invocations
func (mmGetAllByUser *UrlsKeeperMock) GetAllByUserBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetAllByUser.beforeGetAllByUserCounter)
}

// Calls returns a list of arguments used in each call to UrlsKeeperMock.GetAllByUser.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetAllByUser *mUrlsKeeperMockGetAllByUser) Calls() []*UrlsKeeperMockGetAllByUserParams {
	mmGetAllByUser.mutex.RLock()

	argCopy := make([]*UrlsKeeperMockGetAllByUserParams, len(mmGetAllByUser.callArgs))
	copy(argCopy, mmGetAllByUser.callArgs)

	mmGetAllByUser.mutex.RUnlock()

	return argCopy
}

// MinimockGetAllByUserDone returns true if the count of the GetAllByUser invocations corresponds
// the number of defined expectations
func (m *UrlsKeeperMock) MinimockGetAllByUserDone() bool {
	if m.GetAllByUserMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetAllByUserMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetAllByUserMock.invocationsDone()
}

// MinimockGetAllByUserInspect logs each unmet expectation
func (m *UrlsKeeperMock) MinimockGetAllByUserInspect() {
	for _, e := range m.GetAllByUserMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UrlsKeeperMock.GetAllByUser at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetAllByUserCounter := mm_atomic.LoadUint64(&m.afterGetAllByUserCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetAllByUserMock.defaultExpectation != nil && afterGetAllByUserCounter < 1 {
		if m.GetAllByUserMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to UrlsKeeperMock.GetAllByUser at\n%s", m.GetAllByUserMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to UrlsKeeperMock.GetAllByUser at\n%s with params: %#v", m.GetAllByUserMock.defaultExpectation.expectationOrigins.origin, *m.GetAllByUserMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetAllByUser != nil && afterGetAllByUserCounter < 1 {
		m.t.Errorf("Expected call to UrlsKeeperMock.GetAllByUser at\n%s", m.funcGetAllByUserOrigin)
	}

	if !m.GetAllByUserMock.invocationsDone() && afterGetAllByUserCounter > 0 {
		m.t.Errorf("Expected %d calls to UrlsKeeperMock.GetAllByUser at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetAllByUserMock.expectedInvocations), m.GetAllByUserMock.expectedInvocationsOrigin, afterGetAllByUserCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *UrlsKeeperMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockGetInspect()

			m.MinimockGetAllByUserInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *UrlsKeeperMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *UrlsKeeperMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockGetDone() &&
		m.MinimockGetAllByUserDone()
}
