// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// ShorterMock implements mm_getshorturlsbatchhandler.Shorter
type ShorterMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcCreateBatch          func(ctx context.Context, longURLs map[string]string) (m1 map[string]string, err error)
	funcCreateBatchOrigin    string
	inspectFuncCreateBatch   func(ctx context.Context, longURLs map[string]string)
	afterCreateBatchCounter  uint64
	beforeCreateBatchCounter uint64
	CreateBatchMock          mShorterMockCreateBatch
}

// NewShorterMock returns a mock for mm_getshorturlsbatchhandler.Shorter
func NewShorterMock(t minimock.Tester) *ShorterMock {
	m := &ShorterMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CreateBatchMock = mShorterMockCreateBatch{mock: m}
	m.CreateBatchMock.callArgs = []*ShorterMockCreateBatchParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mShorterMockCreateBatch struct {
	optional           bool
	mock               *ShorterMock
	defaultExpectation *ShorterMockCreateBatchExpectation
	expectations       []*ShorterMockCreateBatchExpectation

	callArgs []*ShorterMockCreateBatchParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// ShorterMockCreateBatchExpectation specifies expectation struct of the Shorter.CreateBatch
type ShorterMockCreateBatchExpectation struct {
	mock               *ShorterMock
	params             *ShorterMockCreateBatchParams
	paramPtrs          *ShorterMockCreateBatchParamPtrs
	expectationOrigins ShorterMockCreateBatchExpectationOrigins
	results            *ShorterMockCreateBatchResults
	returnOrigin       string
	Counter            uint64
}

// ShorterMockCreateBatchParams contains parameters of the Shorter.CreateBatch
type ShorterMockCreateBatchParams struct {
	ctx      context.Context
	longURLs map[string]string
}

// ShorterMockCreateBatchParamPtrs contains pointers to parameters of the Shorter.CreateBatch
type ShorterMockCreateBatchParamPtrs struct {
	ctx      *context.Context
	longURLs *map[string]string
}

// ShorterMockCreateBatchResults contains results of the Shorter.CreateBatch
type ShorterMockCreateBatchResults struct {
	m1  map[string]string
	err error
}

// ShorterMockCreateBatchOrigins contains origins of expectations of the Shorter.CreateBatch
type ShorterMockCreateBatchExpectationOrigins struct {
	origin         string
	originCtx      string
	originLongURLs string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCreateBatch *mShorterMockCreateBatch) Optional() *mShorterMockCreateBatch {
	mmCreateBatch.optional = true
	return mmCreateBatch
}

// Expect sets up expected params for Shorter.CreateBatch
func (mmCreateBatch *mShorterMockCreateBatch) Expect(ctx context.Context, longURLs map[string]string) *mShorterMockCreateBatch {
	if mmCreateBatch.mock.funcCreateBatch != nil {
		mmCreateBatch.mock.t.Fatalf("ShorterMock.CreateBatch mock is already set by Set")
	}

	if mmCreateBatch.defaultExpectation == nil {
		mmCreateBatch.defaultExpectation = &ShorterMockCreateBatchExpectation{}
	}

	if mmCreateBatch.defaultExpectation.paramPtrs != nil {
		mmCreateBatch.mock.t.Fatalf("ShorterMock.CreateBatch mock is already set by ExpectParams functions")
	}

	mmCreateBatch.defaultExpectation.params = &ShorterMockCreateBatchParams{ctx, longURLs}
	mmCreateBatch.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCreateBatch.expectations {
		if minimock.Equal(e.params, mmCreateBatch.defaultExpectation.params) {
			mmCreateBatch.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreateBatch.defaultExpectation.params)
		}
	}

	return mmCreateBatch
}

// ExpectCtxParam1 sets up expected param ctx for Shorter.CreateBatch
func (mmCreateBatch *mShorterMockCreateBatch) ExpectCtxParam1(ctx context.Context) *mShorterMockCreateBatch {
	if mmCreateBatch.mock.funcCreateBatch != nil {
		mmCreateBatch.mock.t.Fatalf("ShorterMock.CreateBatch mock is already set by Set")
	}

	if mmCreateBatch.defaultExpectation == nil {
		mmCreateBatch.defaultExpectation = &ShorterMockCreateBatchExpectation{}
	}

	if mmCreateBatch.defaultExpectation.params != nil {
		mmCreateBatch.mock.t.Fatalf("ShorterMock.CreateBatch mock is already set by Expect")
	}

	if mmCreateBatch.defaultExpectation.paramPtrs == nil {
		mmCreateBatch.defaultExpectation.paramPtrs = &ShorterMockCreateBatchParamPtrs{}
	}
	mmCreateBatch.defaultExpectation.paramPtrs.ctx = &ctx
	mmCreateBatch.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmCreateBatch
}

// ExpectLongURLsParam2 sets up expected param longURLs for Shorter.CreateBatch
func (mmCreateBatch *mShorterMockCreateBatch) ExpectLongURLsParam2(longURLs map[string]string) *mShorterMockCreateBatch {
	if mmCreateBatch.mock.funcCreateBatch != nil {
		mmCreateBatch.mock.t.Fatalf("ShorterMock.CreateBatch mock is already set by Set")
	}

	if mmCreateBatch.defaultExpectation == nil {
		mmCreateBatch.defaultExpectation = &ShorterMockCreateBatchExpectation{}
	}

	if mmCreateBatch.defaultExpectation.params != nil {
		mmCreateBatch.mock.t.Fatalf("ShorterMock.CreateBatch mock is already set by Expect")
	}

	if mmCreateBatch.defaultExpectation.paramPtrs == nil {
		mmCreateBatch.defaultExpectation.paramPtrs = &ShorterMockCreateBatchParamPtrs{}
	}
	mmCreateBatch.defaultExpectation.paramPtrs.longURLs = &longURLs
	mmCreateBatch.defaultExpectation.expectationOrigins.originLongURLs = minimock.CallerInfo(1)

	return mmCreateBatch
}

// Inspect accepts an inspector function that has same arguments as the Shorter.CreateBatch
func (mmCreateBatch *mShorterMockCreateBatch) Inspect(f func(ctx context.Context, longURLs map[string]string)) *mShorterMockCreateBatch {
	if mmCreateBatch.mock.inspectFuncCreateBatch != nil {
		mmCreateBatch.mock.t.Fatalf("Inspect function is already set for ShorterMock.CreateBatch")
	}

	mmCreateBatch.mock.inspectFuncCreateBatch = f

	return mmCreateBatch
}

// Return sets up results that will be returned by Shorter.CreateBatch
func (mmCreateBatch *mShorterMockCreateBatch) Return(m1 map[string]string, err error) *ShorterMock {
	if mmCreateBatch.mock.funcCreateBatch != nil {
		mmCreateBatch.mock.t.Fatalf("ShorterMock.CreateBatch mock is already set by Set")
	}

	if mmCreateBatch.defaultExpectation == nil {
		mmCreateBatch.defaultExpectation = &ShorterMockCreateBatchExpectation{mock: mmCreateBatch.mock}
	}
	mmCreateBatch.defaultExpectation.results = &ShorterMockCreateBatchResults{m1, err}
	mmCreateBatch.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCreateBatch.mock
}

// Set uses given function f to mock the Shorter.CreateBatch method
func (mmCreateBatch *mShorterMockCreateBatch) Set(f func(ctx context.Context, longURLs map[string]string) (m1 map[string]string, err error)) *ShorterMock {
	if mmCreateBatch.defaultExpectation != nil {
		mmCreateBatch.mock.t.Fatalf("Default expectation is already set for the Shorter.CreateBatch method")
	}

	if len(mmCreateBatch.expectations) > 0 {
		mmCreateBatch.mock.t.Fatalf("Some expectations are already set for the Shorter.CreateBatch method")
	}

	mmCreateBatch.mock.funcCreateBatch = f
	mmCreateBatch.mock.funcCreateBatchOrigin = minimock.CallerInfo(1)
	return mmCreateBatch.mock
}

// When sets expectation for the Shorter.CreateBatch which will trigger the result defined by the following
// Then helper
func (mmCreateBatch *mShorterMockCreateBatch) When(ctx context.Context, longURLs map[string]string) *ShorterMockCreateBatchExpectation {
	if mmCreateBatch.mock.funcCreateBatch != nil {
		mmCreateBatch.mock.t.Fatalf("ShorterMock.CreateBatch mock is already set by Set")
	}

	expectation := &ShorterMockCreateBatchExpectation{
		mock:               mmCreateBatch.mock,
		params:             &ShorterMockCreateBatchParams{ctx, longURLs},
		expectationOrigins: ShorterMockCreateBatchExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCreateBatch.expectations = append(mmCreateBatch.expectations, expectation)
	return expectation
}

// Then sets up Shorter.CreateBatch return parameters for the expectation previously defined by the When method
func (e *ShorterMockCreateBatchExpectation) Then(m1 map[string]string, err error) *ShorterMock {
	e.results = &ShorterMockCreateBatchResults{m1, err}
	return e.mock
}

// Times sets number of times Shorter.CreateBatch should be invoked
func (mmCreateBatch *mShorterMockCreateBatch) Times(n uint64) *mShorterMockCreateBatch {
	if n == 0 {
		mmCreateBatch.mock.t.Fatalf("Times of ShorterMock.CreateBatch mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCreateBatch.expectedInvocations, n)
	mmCreateBatch.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCreateBatch
}

func (mmCreateBatch *mShorterMockCreateBatch) invocationsDone() bool {
	if len(mmCreateBatch.expectations) == 0 && mmCreateBatch.defaultExpectation == nil && mmCreateBatch.mock.funcCreateBatch == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCreateBatch.mock.afterCreateBatchCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCreateBatch.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// CreateBatch implements mm_getshorturlsbatchhandler.Shorter
func (mmCreateBatch *ShorterMock) CreateBatch(ctx context.Context, longURLs map[string]string) (m1 map[string]string, err error) {
	mm_atomic.AddUint64(&mmCreateBatch.beforeCreateBatchCounter, 1)
	defer mm_atomic.AddUint64(&mmCreateBatch.afterCreateBatchCounter, 1)

	mmCreateBatch.t.Helper()

	if mmCreateBatch.inspectFuncCreateBatch != nil {
		mmCreateBatch.inspectFuncCreateBatch(ctx, longURLs)
	}

	mm_params := ShorterMockCreateBatchParams{ctx, longURLs}

	// Record call args
	mmCreateBatch.CreateBatchMock.mutex.Lock()
	mmCreateBatch.CreateBatchMock.callArgs = append(mmCreateBatch.CreateBatchMock.callArgs, &mm_params)
	mmCreateBatch.CreateBatchMock.mutex.Unlock()

	for _, e := range mmCreateBatch.CreateBatchMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.m1, e.results.err
		}
	}

	if mmCreateBatch.CreateBatchMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreateBatch.CreateBatchMock.defaultExpectation.Counter, 1)
		mm_want := mmCreateBatch.CreateBatchMock.defaultExpectation.params
		mm_want_ptrs := mmCreateBatch.CreateBatchMock.defaultExpectation.paramPtrs

		mm_got := ShorterMockCreateBatchParams{ctx, longURLs}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCreateBatch.t.Errorf("ShorterMock.CreateBatch got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateBatch.CreateBatchMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.longURLs != nil && !minimock.Equal(*mm_want_ptrs.longURLs, mm_got.longURLs) {
				mmCreateBatch.t.Errorf("ShorterMock.CreateBatch got unexpected parameter longURLs, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateBatch.CreateBatchMock.defaultExpectation.expectationOrigins.originLongURLs, *mm_want_ptrs.longURLs, mm_got.longURLs, minimock.Diff(*mm_want_ptrs.longURLs, mm_got.longURLs))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreateBatch.t.Errorf("ShorterMock.CreateBatch got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCreateBatch.CreateBatchMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreateBatch.CreateBatchMock.defaultExpectation.results
		if mm_results == nil {
			mmCreateBatch.t.Fatal("No results are set for the ShorterMock.CreateBatch")
		}
		return (*mm_results).m1, (*mm_results).err
	}
	if mmCreateBatch.funcCreateBatch != nil {
		return mmCreateBatch.funcCreateBatch(ctx, longURLs)
	}
	mmCreateBatch.t.Fatalf("Unexpected call to ShorterMock.CreateBatch. %v %v", ctx, longURLs)
	return
}

// CreateBatchAfterCounter returns a count of finished ShorterMock.CreateBatch invocations
func (mmCreateBatch *ShorterMock) CreateBatchAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateBatch.afterCreateBatchCounter)
}

// CreateBatchBeforeCounter returns a count of ShorterMock.CreateBatch invocations
func (mmCreateBatch *ShorterMock) CreateBatchBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateBatch.beforeCreateBatchCounter)
}

// Calls returns a list of arguments used in each call to ShorterMock.CreateBatch.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreateBatch *mShorterMockCreateBatch) Calls() []*ShorterMockCreateBatchParams {
	mmCreateBatch.mutex.RLock()

	argCopy := make([]*ShorterMockCreateBatchParams, len(mmCreateBatch.callArgs))
	copy(argCopy, mmCreateBatch.callArgs)

	mmCreateBatch.mutex.RUnlock()

	return argCopy
}

// MinimockCreateBatchDone returns true if the count of the CreateBatch invocations corresponds
// the number of defined expectations
func (m *ShorterMock) MinimockCreateBatchDone() bool {
	if m.CreateBatchMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CreateBatchMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CreateBatchMock.invocationsDone()
}

// MinimockCreateBatchInspect logs each unmet expectation
func (m *ShorterMock) MinimockCreateBatchInspect() {
	for _, e := range m.CreateBatchMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ShorterMock.CreateBatch at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCreateBatchCounter := mm_atomic.LoadUint64(&m.afterCreateBatchCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CreateBatchMock.defaultExpectation != nil && afterCreateBatchCounter < 1 {
		if m.CreateBatchMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to ShorterMock.CreateBatch at\n%s", m.CreateBatchMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to ShorterMock.CreateBatch at\n%s with params: %#v", m.CreateBatchMock.defaultExpectation.expectationOrigins.origin, *m.CreateBatchMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreateBatch != nil && afterCreateBatchCounter < 1 {
		m.t.Errorf("Expected call to ShorterMock.CreateBatch at\n%s", m.funcCreateBatchOrigin)
	}

	if !m.CreateBatchMock.invocationsDone() && afterCreateBatchCounter > 0 {
		m.t.Errorf("Expected %d calls to ShorterMock.CreateBatch at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CreateBatchMock.expectedInvocations), m.CreateBatchMock.expectedInvocationsOrigin, afterCreateBatchCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *ShorterMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCreateBatchInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *ShorterMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *ShorterMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCreateBatchDone()
}
