// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// AuditServiceMock implements mm_getshorturlhandler.AuditService
type AuditServiceMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcPublishShortenEvent          func(longURL string, userID string)
	funcPublishShortenEventOrigin    string
	inspectFuncPublishShortenEvent   func(longURL string, userID string)
	afterPublishShortenEventCounter  uint64
	beforePublishShortenEventCounter uint64
	PublishShortenEventMock          mAuditServiceMockPublishShortenEvent
}

// NewAuditServiceMock returns a mock for mm_getshorturlhandler.AuditService
func NewAuditServiceMock(t minimock.Tester) *AuditServiceMock {
	m := &AuditServiceMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.PublishShortenEventMock = mAuditServiceMockPublishShortenEvent{mock: m}
	m.PublishShortenEventMock.callArgs = []*AuditServiceMockPublishShortenEventParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mAuditServiceMockPublishShortenEvent struct {
	optional           bool
	mock               *AuditServiceMock
	defaultExpectation *AuditServiceMockPublishShortenEventExpectation
	expectations       []*AuditServiceMockPublishShortenEventExpectation

	callArgs []*AuditServiceMockPublishShortenEventParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// AuditServiceMockPublishShortenEventExpectation specifies expectation struct of the AuditService.PublishShortenEvent
type AuditServiceMockPublishShortenEventExpectation struct {
	mock               *AuditServiceMock
	params             *AuditServiceMockPublishShortenEventParams
	paramPtrs          *AuditServiceMockPublishShortenEventParamPtrs
	expectationOrigins AuditServiceMockPublishShortenEventExpectationOrigins

	returnOrigin string
	Counter      uint64
}

// AuditServiceMockPublishShortenEventParams contains parameters of the AuditService.PublishShortenEvent
type AuditServiceMockPublishShortenEventParams struct {
	longURL string
	userID  string
}

// AuditServiceMockPublishShortenEventParamPtrs contains pointers to parameters of the AuditService.PublishShortenEvent
type AuditServiceMockPublishShortenEventParamPtrs struct {
	longURL *string
	userID  *string
}

// AuditServiceMockPublishShortenEventOrigins contains origins of expectations of the AuditService.PublishShortenEvent
type AuditServiceMockPublishShortenEventExpectationOrigins struct {
	origin        string
	originLongURL string
	originUserID  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmPublishShortenEvent *mAuditServiceMockPublishShortenEvent) Optional() *mAuditServiceMockPublishShortenEvent {
	mmPublishShortenEvent.optional = true
	return mmPublishShortenEvent
}

// Expect sets up expected params for AuditService.PublishShortenEvent
func (mmPublishShortenEvent *mAuditServiceMockPublishShortenEvent) Expect(longURL string, userID string) *mAuditServiceMockPublishShortenEvent {
	if mmPublishShortenEvent.mock.funcPublishShortenEvent != nil {
		mmPublishShortenEvent.mock.t.Fatalf("AuditServiceMock.PublishShortenEvent mock is already set by Set")
	}

	if mmPublishShortenEvent.defaultExpectation == nil {
		mmPublishShortenEvent.defaultExpectation = &AuditServiceMockPublishShortenEventExpectation{}
	}

	if mmPublishShortenEvent.defaultExpectation.paramPtrs != nil {
		mmPublishShortenEvent.mock.t.Fatalf("AuditServiceMock.PublishShortenEvent mock is already set by ExpectParams functions")
	}

	mmPublishShortenEvent.defaultExpectation.params = &AuditServiceMockPublishShortenEventParams{longURL, userID}
	mmPublishShortenEvent.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmPublishShortenEvent.expectations {
		if minimock.Equal(e.params, mmPublishShortenEvent.defaultExpectation.params) {
			mmPublishShortenEvent.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmPublishShortenEvent.defaultExpectation.params)
		}
	}

	return mmPublishShortenEvent
}

// ExpectLongURLParam1 sets up expected param longURL for AuditService.PublishShortenEvent
func (mmPublishShortenEvent *mAuditServiceMockPublishShortenEvent) ExpectLongURLParam1(longURL string) *mAuditServiceMockPublishShortenEvent {
	if mmPublishShortenEvent.mock.funcPublishShortenEvent != nil {
		mmPublishShortenEvent.mock.t.Fatalf("AuditServiceMock.PublishShortenEvent mock is already set by Set")
	}

	if mmPublishShortenEvent.defaultExpectation == nil {
		mmPublishShortenEvent.defaultExpectation = &AuditServiceMockPublishShortenEventExpectation{}
	}

	if mmPublishShortenEvent.defaultExpectation.params != nil {
		mmPublishShortenEvent.mock.t.Fatalf("AuditServiceMock.PublishShortenEvent mock is already set by Expect")
	}

	if mmPublishShortenEvent.defaultExpectation.paramPtrs == nil {
		mmPublishShortenEvent.defaultExpectation.paramPtrs = &AuditServiceMockPublishShortenEventParamPtrs{}
	}
	mmPublishShortenEvent.defaultExpectation.paramPtrs.longURL = &longURL
	mmPublishShortenEvent.defaultExpectation.expectationOrigins.originLongURL = minimock.CallerInfo(1)

	return mmPublishShortenEvent
}

// ExpectUserIDParam2 sets up expected param userID for AuditService.PublishShortenEvent
func (mmPublishShortenEvent *mAuditServiceMockPublishShortenEvent) ExpectUserIDParam2(userID string) *mAuditServiceMockPublishShortenEvent {
	if mmPublishShortenEvent.mock.funcPublishShortenEvent != nil {
		mmPublishShortenEvent.mock.t.Fatalf("AuditServiceMock.PublishShortenEvent mock is already set by Set")
	}

	if mmPublishShortenEvent.defaultExpectation == nil {
		mmPublishShortenEvent.defaultExpectation = &AuditServiceMockPublishShortenEventExpectation{}
	}

	if mmPublishShortenEvent.defaultExpectation.params != nil {
		mmPublishShortenEvent.mock.t.Fatalf("AuditServiceMock.PublishShortenEvent mock is already set by Expect")
	}

	if mmPublishShortenEvent.defaultExpectation.paramPtrs == nil {
		mmPublishShortenEvent.defaultExpectation.paramPtrs = &AuditServiceMockPublishShortenEventParamPtrs{}
	}
	mmPublishShortenEvent.defaultExpectation.paramPtrs.userID = &userID
	mmPublishShortenEvent.defaultExpectation.expectationOrigins.originUserID = minimock.CallerInfo(1)

	return mmPublishShortenEvent
}

// Inspect accepts an inspector function that has same arguments as the AuditService.PublishShortenEvent
func (mmPublishShortenEvent *mAuditServiceMockPublishShortenEvent) Inspect(f func(longURL string, userID string)) *mAuditServiceMockPublishShortenEvent {
	if mmPublishShortenEvent.mock.inspectFuncPublishShortenEvent != nil {
		mmPublishShortenEvent.mock.t.Fatalf("Inspect function is already set for AuditServiceMock.PublishShortenEvent")
	}

	mmPublishShortenEvent.mock.inspectFuncPublishShortenEvent = f

	return mmPublishShortenEvent
}

// Return sets up results that will be returned by AuditService.PublishShortenEvent
func (mmPublishShortenEvent *mAuditServiceMockPublishShortenEvent) Return() *AuditServiceMock {
	if mmPublishShortenEvent.mock.funcPublishShortenEvent != nil {
		mmPublishShortenEvent.mock.t.Fatalf("AuditServiceMock.PublishShortenEvent mock is already set by Set")
	}

	if mmPublishShortenEvent.defaultExpectation == nil {
		mmPublishShortenEvent.defaultExpectation = &AuditServiceMockPublishShortenEventExpectation{mock: mmPublishShortenEvent.mock}
	}

	mmPublishShortenEvent.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmPublishShortenEvent.mock
}

// Set uses given function f to mock the AuditService.PublishShortenEvent method
func (mmPublishShortenEvent *mAuditServiceMockPublishShortenEvent) Set(f func(longURL string, userID string)) *AuditServiceMock {
	if mmPublishShortenEvent.defaultExpectation != nil {
		mmPublishShortenEvent.mock.t.Fatalf("Default expectation is already set for the AuditService.PublishShortenEvent method")
	}

	if len(mmPublishShortenEvent.expectations) > 0 {
		mmPublishShortenEvent.mock.t.Fatalf("Some expectations are already set for the AuditService.PublishShortenEvent method")
	}

	mmPublishShortenEvent.mock.funcPublishShortenEvent = f
	mmPublishShortenEvent.mock.funcPublishShortenEventOrigin = minimock.CallerInfo(1)
	return mmPublishShortenEvent.mock
}

// When sets expectation for the AuditService.PublishShortenEvent which will trigger the result defined by the following
// Then helper
func (mmPublishShortenEvent *mAuditServiceMockPublishShortenEvent) When(longURL string, userID string) *AuditServiceMockPublishShortenEventExpectation {
	if mmPublishShortenEvent.mock.funcPublishShortenEvent != nil {
		mmPublishShortenEvent.mock.t.Fatalf("AuditServiceMock.PublishShortenEvent mock is already set by Set")
	}

	expectation := &AuditServiceMockPublishShortenEventExpectation{
		mock:               mmPublishShortenEvent.mock,
		params:             &AuditServiceMockPublishShortenEventParams{longURL, userID},
		expectationOrigins: AuditServiceMockPublishShortenEventExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmPublishShortenEvent.expectations = append(mmPublishShortenEvent.expectations, expectation)
	return expectation
}

// Then sets up AuditService.PublishShortenEvent return parameters for the expectation previously defined by the When method

func (e *AuditServiceMockPublishShortenEventExpectation) Then() *AuditServiceMock {
	return e.mock
}

// Times sets number of times AuditService.PublishShortenEvent should be invoked
func (mmPublishShortenEvent *mAuditServiceMockPublishShortenEvent) Times(n uint64) *mAuditServiceMockPublishShortenEvent {
	if n == 0 {
		mmPublishShortenEvent.mock.t.Fatalf("Times of AuditServiceMock.PublishShortenEvent mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmPublishShortenEvent.expectedInvocations, n)
	mmPublishShortenEvent.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmPublishShortenEvent
}

func (mmPublishShortenEvent *mAuditServiceMockPublishShortenEvent) invocationsDone() bool {
	if len(mmPublishShortenEvent.expectations) == 0 && mmPublishShortenEvent.defaultExpectation == nil && mmPublishShortenEvent.mock.funcPublishShortenEvent == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmPublishShortenEvent.mock.afterPublishShortenEventCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmPublishShortenEvent.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// PublishShortenEvent implements mm_getshorturlhandler.AuditService
func (mmPublishShortenEvent *AuditServiceMock) PublishShortenEvent(longURL string, userID string) {
	mm_atomic.AddUint64(&mmPublishShortenEvent.beforePublishShortenEventCounter, 1)
	defer mm_atomic.AddUint64(&mmPublishShortenEvent.afterPublishShortenEventCounter, 1)

	mmPublishShortenEvent.t.Helper()

	if mmPublishShortenEvent.inspectFuncPublishShortenEvent != nil {
		mmPublishShortenEvent.inspectFuncPublishShortenEvent(longURL, userID)
	}

	mm_params := AuditServiceMockPublishShortenEventParams{longURL, userID}

	// Record call args
	mmPublishShortenEvent.PublishShortenEventMock.mutex.Lock()
	mmPublishShortenEvent.PublishShortenEventMock.callArgs = append(mmPublishShortenEvent.PublishShortenEventMock.callArgs, &mm_params)
	mmPublishShortenEvent.PublishShortenEventMock.mutex.Unlock()

	for _, e := range mmPublishShortenEvent.PublishShortenEventMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return
		}
	}

	if mmPublishShortenEvent.PublishShortenEventMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmPublishShortenEvent.PublishShortenEventMock.defaultExpectation.Counter, 1)
		mm_want := mmPublishShortenEvent.PublishShortenEventMock.defaultExpectation.params
		mm_want_ptrs := mmPublishShortenEvent.PublishShortenEventMock.defaultExpectation.paramPtrs

		mm_got := AuditServiceMockPublishShortenEventParams{longURL, userID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.longURL != nil && !minimock.Equal(*mm_want_ptrs.longURL, mm_got.longURL) {
				mmPublishShortenEvent.t.Errorf("AuditServiceMock.PublishShortenEvent got unexpected parameter longURL, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmPublishShortenEvent.PublishShortenEventMock.defaultExpectation.expectationOrigins.originLongURL, *mm_want_ptrs.longURL, mm_got.longURL, minimock.Diff(*mm_want_ptrs.longURL, mm_got.longURL))
			}

			if mm_want_ptrs.userID != nil && !minimock.Equal(*mm_want_ptrs.userID, mm_got.userID) {
				mmPublishShortenEvent.t.Errorf("AuditServiceMock.PublishShortenEvent got unexpected parameter userID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmPublishShortenEvent.PublishShortenEventMock.defaultExpectation.expectationOrigins.originUserID, *mm_want_ptrs.userID, mm_got.userID, minimock.Diff(*mm_want_ptrs.userID, mm_got.userID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmPublishShortenEvent.t.Errorf("AuditServiceMock.PublishShortenEvent got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmPublishShortenEvent.PublishShortenEventMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		return

	}
	if mmPublishShortenEvent.funcPublishShortenEvent != nil {
		mmPublishShortenEvent.funcPublishShortenEvent(longURL, userID)
		return
	}
	mmPublishShortenEvent.t.Fatalf("Unexpected call to AuditServiceMock.PublishShortenEvent. %v %v", longURL, userID)

}

// PublishShortenEventAfterCounter returns a count of finished AuditServiceMock.PublishShortenEvent invocations
func (mmPublishShortenEvent *AuditServiceMock) PublishShortenEventAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmPublishShortenEvent.afterPublishShortenEventCounter)
}

// PublishShortenEventBeforeCounter returns a count of AuditServiceMock.PublishShortenEvent invocations
func (mmPublishShortenEvent *AuditServiceMock) PublishShortenEventBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmPublishShortenEvent.beforePublishShortenEventCounter)
}

// Calls returns a list of arguments used in each call to AuditServiceMock.PublishShortenEvent.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmPublishShortenEvent *mAuditServiceMockPublishShortenEvent) Calls() []*AuditServiceMockPublishShortenEventParams {
	mmPublishShortenEvent.mutex.RLock()

	argCopy := make([]*AuditServiceMockPublishShortenEventParams, len(mmPublishShortenEvent.callArgs))
	copy(argCopy, mmPublishShortenEvent.callArgs)

	mmPublishShortenEvent.mutex.RUnlock()

	return argCopy
}

// MinimockPublishShortenEventDone returns true if the count of the PublishShortenEvent invocations corresponds
// the number of defined expectations
func (m *AuditServiceMock) MinimockPublishShortenEventDone() bool {
	if m.PublishShortenEventMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.PublishShortenEventMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.PublishShortenEventMock.invocationsDone()
}

// MinimockPublishShortenEventInspect logs each unmet expectation
func (m *AuditServiceMock) MinimockPublishShortenEventInspect() {
	for _, e := range m.PublishShortenEventMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to AuditServiceMock.PublishShortenEvent at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterPublishShortenEventCounter := mm_atomic.LoadUint64(&m.afterPublishShortenEventCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.PublishShortenEventMock.defaultExpectation != nil && afterPublishShortenEventCounter < 1 {
		if m.PublishShortenEventMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to AuditServiceMock.PublishShortenEvent at\n%s", m.PublishShortenEventMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to AuditServiceMock.PublishShortenEvent at\n%s with params: %#v", m.PublishShortenEventMock.defaultExpectation.expectationOrigins.origin, *m.PublishShortenEventMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcPublishShortenEvent != nil && afterPublishShortenEventCounter < 1 {
		m.t.Errorf("Expected call to AuditServiceMock.PublishShortenEvent at\n%s", m.funcPublishShortenEventOrigin)
	}

	if !m.PublishShortenEventMock.invocationsDone() && afterPublishShortenEventCounter > 0 {
		m.t.Errorf("Expected %d calls to AuditServiceMock.PublishShortenEvent at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.PublishShortenEventMock.expectedInvocations), m.PublishShortenEventMock.expectedInvocationsOrigin, afterPublishShortenEventCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *AuditServiceMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockPublishShortenEventInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *AuditServiceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *AuditServiceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockPublishShortenEventDone()
}
