// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// DBMock implements mm_pinghandler.DB
type DBMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcPingContext          func(ctx context.Context) (err error)
	funcPingContextOrigin    string
	inspectFuncPingContext   func(ctx context.Context)
	afterPingContextCounter  uint64
	beforePingContextCounter uint64
	PingContextMock          mDBMockPingContext
}

// NewDBMock returns a mock for mm_pinghandler.DB
func NewDBMock(t minimock.Tester) *DBMock {
	m := &DBMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.PingContextMock = mDBMockPingContext{mock: m}
	m.PingContextMock.callArgs = []*DBMockPingContextParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mDBMockPingContext struct {
	optional           bool
	mock               *DBMock
	defaultExpectation *DBMockPingContextExpectation
	expectations       []*DBMockPingContextExpectation

	callArgs []*DBMockPingContextParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// DBMockPingContextExpectation specifies expectation struct of the DB.PingContext
type DBMockPingContextExpectation struct {
	mock               *DBMock
	params             *DBMockPingContextParams
	paramPtrs          *DBMockPingContextParamPtrs
	expectationOrigins DBMockPingContextExpectationOrigins
	results            *DBMockPingContextResults
	returnOrigin       string
	Counter            uint64
}

// DBMockPingContextParams contains parameters of the DB.PingContext
type DBMockPingContextParams struct {
	ctx context.Context
}

// DBMockPingContextParamPtrs contains pointers to parameters of the DB.PingContext
type DBMockPingContextParamPtrs struct {
	ctx *context.Context
}

// DBMockPingContextResults contains results of the DB.PingContext
type DBMockPingContextResults struct {
	err error
}

// DBMockPingContextOrigins contains origins of expectations of the DB.PingContext
type DBMockPingContextExpectationOrigins struct {
	origin    string
	originCtx string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmPingContext *mDBMockPingContext) Optional() *mDBMockPingContext {
	mmPingContext.optional = true
	return mmPingContext
}

// Expect sets up expected params for DB.PingContext
func (mmPingContext *mDBMockPingContext) Expect(ctx context.Context) *mDBMockPingContext {
	if mmPingContext.mock.funcPingContext != nil {
		mmPingContext.mock.t.Fatalf("DBMock.PingContext mock is already set by Set")
	}

	if mmPingContext.defaultExpectation == nil {
		mmPingContext.defaultExpectation = &DBMockPingContextExpectation{}
	}

	if mmPingContext.defaultExpectation.paramPtrs != nil {
		mmPingContext.mock.t.Fatalf("DBMock.PingContext mock is already set by ExpectParams functions")
	}

	mmPingContext.defaultExpectation.params = &DBMockPingContextParams{ctx}
	mmPingContext.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmPingContext.expectations {
		if minimock.Equal(e.params, mmPingContext.defaultExpectation.params) {
			mmPingContext.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmPingContext.defaultExpectation.params)
		}
	}

	return mmPingContext
}

// ExpectCtxParam1 sets up expected param ctx for DB.PingContext
func (mmPingContext *mDBMockPingContext) ExpectCtxParam1(ctx context.Context) *mDBMockPingContext {
	if mmPingContext.mock.funcPingContext != nil {
		mmPingContext.mock.t.Fatalf("DBMock.PingContext mock is already set by Set")
	}

	if mmPingContext.defaultExpectation == nil {
		mmPingContext.defaultExpectation = &DBMockPingContextExpectation{}
	}

	if mmPingContext.defaultExpectation.params != nil {
		mmPingContext.mock.t.Fatalf("DBMock.PingContext mock is already set by Expect")
	}

	if mmPingContext.defaultExpectation.paramPtrs == nil {
		mmPingContext.defaultExpectation.paramPtrs = &DBMockPingContextParamPtrs{}
	}
	mmPingContext.defaultExpectation.paramPtrs.ctx = &ctx
	mmPingContext.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmPingContext
}

// Inspect accepts an inspector function that has same arguments as the DB.PingContext
func (mmPingContext *mDBMockPingContext) Inspect(f func(ctx context.Context)) *mDBMockPingContext {
	if mmPingContext.mock.inspectFuncPingContext != nil {
		mmPingContext.mock.t.Fatalf("Inspect function is already set for DBMock.PingContext")
	}

	mmPingContext.mock.inspectFuncPingContext = f

	return mmPingContext
}

// Return sets up results that will be returned by DB.PingContext
func (mmPingContext *mDBMockPingContext) Return(err error) *DBMock {
	if mmPingContext.mock.funcPingContext != nil {
		mmPingContext.mock.t.Fatalf("DBMock.PingContext mock is already set by Set")
	}

	if mmPingContext.defaultExpectation == nil {
		mmPingContext.defaultExpectation = &DBMockPingContextExpectation{mock: mmPingContext.mock}
	}
	mmPingContext.defaultExpectation.results = &DBMockPingContextResults{err}
	mmPingContext.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmPingContext.mock
}

// Set uses given function f to mock the DB.PingContext method
func (mmPingContext *mDBMockPingContext) Set(f func(ctx context.Context) (err error)) *DBMock {
	if mmPingContext.defaultExpectation != nil {
		mmPingContext.mock.t.Fatalf("Default expectation is already set for the DB.PingContext method")
	}

	if len(mmPingContext.expectations) > 0 {
		mmPingContext.mock.t.Fatalf("Some expectations are already set for the DB.PingContext method")
	}

	mmPingContext.mock.funcPingContext = f
	mmPingContext.mock.funcPingContextOrigin = minimock.CallerInfo(1)
	return mmPingContext.mock
}

// When sets expectation for the DB.PingContext which will trigger the result defined by the following
// Then helper
func (mmPingContext *mDBMockPingContext) When(ctx context.Context) *DBMockPingContextExpectation {
	if mmPingContext.mock.funcPingContext != nil {
		mmPingContext.mock.t.Fatalf("DBMock.PingContext mock is already set by Set")
	}

	expectation := &DBMockPingContextExpectation{
		mock:               mmPingContext.mock,
		params:             &DBMockPingContextParams{ctx},
		expectationOrigins: DBMockPingContextExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmPingContext.expectations = append(mmPingContext.expectations, expectation)
	return expectation
}

// Then sets up DB.PingContext return parameters for the expectation previously defined by the When method
func (e *DBMockPingContextExpectation) Then(err error) *DBMock {
	e.results = &DBMockPingContextResults{err}
	return e.mock
}

// Times sets number of times DB.PingContext should be invoked
func (mmPingContext *mDBMockPingContext) Times(n uint64) *mDBMockPingContext {
	if n == 0 {
		mmPingContext.mock.t.Fatalf("Times of DBMock.PingContext mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmPingContext.expectedInvocations, n)
	mmPingContext.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmPingContext
}

func (mmPingContext *mDBMockPingContext) invocationsDone() bool {
	if len(mmPingContext.expectations) == 0 && mmPingContext.defaultExpectation == nil && mmPingContext.mock.funcPingContext == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmPingContext.mock.afterPingContextCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmPingContext.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// PingContext implements mm_pinghandler.DB
func (mmPingContext *DBMock) PingContext(ctx context.Context) (err error) {
	mm_atomic.AddUint64(&mmPingContext.beforePingContextCounter, 1)
	defer mm_atomic.AddUint64(&mmPingContext.afterPingContextCounter, 1)

	mmPingContext.t.Helper()

	if mmPingContext.inspectFuncPingContext != nil {
		mmPingContext.inspectFuncPingContext(ctx)
	}

	mm_params := DBMockPingContextParams{ctx}

	// Record call args
	mmPingContext.PingContextMock.mutex.Lock()
	mmPingContext.PingContextMock.callArgs = append(mmPingContext.PingContextMock.callArgs, &mm_params)
	mmPingContext.PingContextMock.mutex.Unlock()

	for _, e := range mmPingContext.PingContextMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmPingContext.PingContextMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmPingContext.PingContextMock.defaultExpectation.Counter, 1)
		mm_want := mmPingContext.PingContextMock.defaultExpectation.params
		mm_want_ptrs := mmPingContext.PingContextMock.defaultExpectation.paramPtrs

		mm_got := DBMockPingContextParams{ctx}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmPingContext.t.Errorf("DBMock.PingContext got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmPingContext.PingContextMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmPingContext.t.Errorf("DBMock.PingContext got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmPingContext.PingContextMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmPingContext.PingContextMock.defaultExpectation.results
		if mm_results == nil {
			mmPingContext.t.Fatal("No results are set for the DBMock.PingContext")
		}
		return (*mm_results).err
	}
	if mmPingContext.funcPingContext != nil {
		return mmPingContext.funcPingContext(ctx)
	}
	mmPingContext.t.Fatalf("Unexpected call to DBMock.PingContext. %v", ctx)
	return
}

// PingContextAfterCounter returns a count of finished DBMock.PingContext invocations
func (mmPingContext *DBMock) PingContextAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmPingContext.afterPingContextCounter)
}

// PingContextBeforeCounter returns a count of DBMock.PingContext invocations
func (mmPingContext *DBMock) PingContextBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmPingContext.beforePingContextCounter)
}

// Calls returns a list of arguments used in each call to DBMock.PingContext.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmPingContext *mDBMockPingContext) Calls() []*DBMockPingContextParams {
	mmPingContext.mutex.RLock()

	argCopy := make([]*DBMockPingContextParams, len(mmPingContext.callArgs))
	copy(argCopy, mmPingContext.callArgs)

	mmPingContext.mutex.RUnlock()

	return argCopy
}

// MinimockPingContextDone returns true if the count of the PingContext invocations corresponds
// the number of defined expectations
func (m *DBMock) MinimockPingContextDone() bool {
	if m.PingContextMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.PingContextMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.PingContextMock.invocationsDone()
}

// MinimockPingContextInspect logs each unmet expectation
func (m *DBMock) MinimockPingContextInspect() {
	for _, e := range m.PingContextMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to DBMock.PingContext at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterPingContextCounter := mm_atomic.LoadUint64(&m.afterPingContextCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.PingContextMock.defaultExpectation != nil && afterPingContextCounter < 1 {
		if m.PingContextMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to DBMock.PingContext at\n%s", m.PingContextMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to DBMock.PingContext at\n%s with params: %#v", m.PingContextMock.defaultExpectation.expectationOrigins.origin, *m.PingContextMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcPingContext != nil && afterPingContextCounter < 1 {
		m.t.Errorf("Expected call to DBMock.PingContext at\n%s", m.funcPingContextOrigin)
	}

	if !m.PingContextMock.invocationsDone() && afterPingContextCounter > 0 {
		m.t.Errorf("Expected %d calls to DBMock.PingContext at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.PingContextMock.expectedInvocations), m.PingContextMock.expectedInvocationsOrigin, afterPingContextCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *DBMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockPingContextInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *DBMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *DBMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockPingContextDone()
}
