// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// UrlsKeeperMock implements mm_deleteuserurlshandler.UrlsKeeper
type UrlsKeeperMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcDeleteAsync          func(ctx context.Context, userID string, shortURLs []string)
	funcDeleteAsyncOrigin    string
	inspectFuncDeleteAsync   func(ctx context.Context, userID string, shortURLs []string)
	afterDeleteAsyncCounter  uint64
	beforeDeleteAsyncCounter uint64
	DeleteAsyncMock          mUrlsKeeperMockDeleteAsync
}

// NewUrlsKeeperMock returns a mock for mm_deleteuserurlshandler.UrlsKeeper
func NewUrlsKeeperMock(t minimock.Tester) *UrlsKeeperMock {
	m := &UrlsKeeperMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.DeleteAsyncMock = mUrlsKeeperMockDeleteAsync{mock: m}
	m.DeleteAsyncMock.callArgs = []*UrlsKeeperMockDeleteAsyncParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mUrlsKeeperMockDeleteAsync struct {
	optional           bool
	mock               *UrlsKeeperMock
	defaultExpectation *UrlsKeeperMockDeleteAsyncExpectation
	expectations       []*UrlsKeeperMockDeleteAsyncExpectation

	callArgs []*UrlsKeeperMockDeleteAsyncParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// UrlsKeeperMockDeleteAsyncExpectation specifies expectation struct of the UrlsKeeper.DeleteAsync
type UrlsKeeperMockDeleteAsyncExpectation struct {
	mock               *UrlsKeeperMock
	params             *UrlsKeeperMockDeleteAsyncParams
	paramPtrs          *UrlsKeeperMockDeleteAsyncParamPtrs
	expectationOrigins UrlsKeeperMockDeleteAsyncExpectationOrigins

	returnOrigin string
	Counter      uint64
}

// UrlsKeeperMockDeleteAsyncParams contains parameters of the UrlsKeeper.DeleteAsync
type UrlsKeeperMockDeleteAsyncParams struct {
	ctx       context.Context
	userID    string
	shortURLs []string
}

// UrlsKeeperMockDeleteAsyncParamPtrs contains pointers to parameters of the UrlsKeeper.DeleteAsync
type UrlsKeeperMockDeleteAsyncParamPtrs struct {
	ctx       *context.Context
	userID    *string
	shortURLs *[]string
}

// UrlsKeeperMockDeleteAsyncOrigins contains origins of expectations of the UrlsKeeper.DeleteAsync
type UrlsKeeperMockDeleteAsyncExpectationOrigins struct {
	origin          string
	originCtx       string
	originUserID    string
	originShortURLs string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmDeleteAsync *mUrlsKeeperMockDeleteAsync) Optional() *mUrlsKeeperMockDeleteAsync {
	mmDeleteAsync.optional = true
	return mmDeleteAsync
}

// Expect sets up expected params for UrlsKeeper.DeleteAsync
func (mmDeleteAsync *mUrlsKeeperMockDeleteAsync) Expect(ctx context.Context, userID string, shortURLs []string) *mUrlsKeeperMockDeleteAsync {
	if mmDeleteAsync.mock.funcDeleteAsync != nil {
		mmDeleteAsync.mock.t.Fatalf("UrlsKeeperMock.DeleteAsync mock is already set by Set")
	}

	if mmDeleteAsync.defaultExpectation == nil {
		mmDeleteAsync.defaultExpectation = &UrlsKeeperMockDeleteAsyncExpectation{}
	}

	if mmDeleteAsync.defaultExpectation.paramPtrs != nil {
		mmDeleteAsync.mock.t.Fatalf("UrlsKeeperMock.DeleteAsync mock is already set by ExpectParams functions")
	}

	mmDeleteAsync.defaultExpectation.params = &UrlsKeeperMockDeleteAsyncParams{ctx, userID, shortURLs}
	mmDeleteAsync.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmDeleteAsync.expectations {
		if minimock.Equal(e.params, mmDeleteAsync.defaultExpectation.params) {
			mmDeleteAsync.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmDeleteAsync.defaultExpectation.params)
		}
	}

	return mmDeleteAsync
}

// ExpectCtxParam1 sets up expected param ctx for UrlsKeeper.DeleteAsync
func (mmDeleteAsync *mUrlsKeeperMockDeleteAsync) ExpectCtxParam1(ctx context.Context) *mUrlsKeeperMockDeleteAsync {
	if mmDeleteAsync.mock.funcDeleteAsync != nil {
		mmDeleteAsync.mock.t.Fatalf("UrlsKeeperMock.DeleteAsync mock is already set by Set")
	}

	if mmDeleteAsync.defaultExpectation == nil {
		mmDeleteAsync.defaultExpectation = &UrlsKeeperMockDeleteAsyncExpectation{}
	}

	if mmDeleteAsync.defaultExpectation.params != nil {
		mmDeleteAsync.mock.t.Fatalf("UrlsKeeperMock.DeleteAsync mock is already set by Expect")
	}

	if mmDeleteAsync.defaultExpectation.paramPtrs == nil {
		mmDeleteAsync.defaultExpectation.paramPtrs = &UrlsKeeperMockDeleteAsyncParamPtrs{}
	}
	mmDeleteAsync.defaultExpectation.paramPtrs.ctx = &ctx
	mmDeleteAsync.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmDeleteAsync
}

// ExpectUserIDParam2 sets up expected param userID for UrlsKeeper.DeleteAsync
func (mmDeleteAsync *mUrlsKeeperMockDeleteAsync) ExpectUserIDParam2(userID string) *mUrlsKeeperMockDeleteAsync {
	if mmDeleteAsync.mock.funcDeleteAsync != nil {
		mmDeleteAsync.mock.t.Fatalf("UrlsKeeperMock.DeleteAsync mock is already set by Set")
	}

	if mmDeleteAsync.defaultExpectation == nil {
		mmDeleteAsync.defaultExpectation = &UrlsKeeperMockDeleteAsyncExpectation{}
	}

	if mmDeleteAsync.defaultExpectation.params != nil {
		mmDeleteAsync.mock.t.Fatalf("UrlsKeeperMock.DeleteAsync mock is already set by Expect")
	}

	if mmDeleteAsync.defaultExpectation.paramPtrs == nil {
		mmDeleteAsync.defaultExpectation.paramPtrs = &UrlsKeeperMockDeleteAsyncParamPtrs{}
	}
	mmDeleteAsync.defaultExpectation.paramPtrs.userID = &userID
	mmDeleteAsync.defaultExpectation.expectationOrigins.originUserID = minimock.CallerInfo(1)

	return mmDeleteAsync
}

// ExpectShortURLsParam3 sets up expected param shortURLs for UrlsKeeper.DeleteAsync
func (mmDeleteAsync *mUrlsKeeperMockDeleteAsync) ExpectShortURLsParam3(shortURLs []string) *mUrlsKeeperMockDeleteAsync {
	if mmDeleteAsync.mock.funcDeleteAsync != nil {
		mmDeleteAsync.mock.t.Fatalf("UrlsKeeperMock.DeleteAsync mock is already set by Set")
	}

	if mmDeleteAsync.defaultExpectation == nil {
		mmDeleteAsync.defaultExpectation = &UrlsKeeperMockDeleteAsyncExpectation{}
	}

	if mmDeleteAsync.defaultExpectation.params != nil {
		mmDeleteAsync.mock.t.Fatalf("UrlsKeeperMock.DeleteAsync mock is already set by Expect")
	}

	if mmDeleteAsync.defaultExpectation.paramPtrs == nil {
		mmDeleteAsync.defaultExpectation.paramPtrs = &UrlsKeeperMockDeleteAsyncParamPtrs{}
	}
	mmDeleteAsync.defaultExpectation.paramPtrs.shortURLs = &shortURLs
	mmDeleteAsync.defaultExpectation.expectationOrigins.originShortURLs = minimock.CallerInfo(1)

	return mmDeleteAsync
}

// Inspect accepts an inspector function that has same arguments as the UrlsKeeper.DeleteAsync
func (mmDeleteAsync *mUrlsKeeperMockDeleteAsync) Inspect(f func(ctx context.Context, userID string, shortURLs []string)) *mUrlsKeeperMockDeleteAsync {
	if mmDeleteAsync.mock.inspectFuncDeleteAsync != nil {
		mmDeleteAsync.mock.t.Fatalf("Inspect function is already set for UrlsKeeperMock.DeleteAsync")
	}

	mmDeleteAsync.mock.inspectFuncDeleteAsync = f

	return mmDeleteAsync
}

// Return sets up results that will be returned by UrlsKeeper.DeleteAsync
func (mmDeleteAsync *mUrlsKeeperMockDeleteAsync) Return() *UrlsKeeperMock {
	if mmDeleteAsync.mock.funcDeleteAsync != nil {
		mmDeleteAsync.mock.t.Fatalf("UrlsKeeperMock.DeleteAsync mock is already set by Set")
	}

	if mmDeleteAsync.defaultExpectation == nil {
		mmDeleteAsync.defaultExpectation = &UrlsKeeperMockDeleteAsyncExpectation{mock: mmDeleteAsync.mock}
	}

	mmDeleteAsync.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmDeleteAsync.mock
}

// Set uses given function f to mock the UrlsKeeper.DeleteAsync method
func (mmDeleteAsync *mUrlsKeeperMockDeleteAsync) Set(f func(ctx context.Context, userID string, shortURLs []string)) *UrlsKeeperMock {
	if mmDeleteAsync.defaultExpectation != nil {
		mmDeleteAsync.mock.t.Fatalf("Default expectation is already set for the UrlsKeeper.DeleteAsync method")
	}

	if len(mmDeleteAsync.expectations) > 0 {
		mmDeleteAsync.mock.t.Fatalf("Some expectations are already set for the UrlsKeeper.DeleteAsync method")
	}

	mmDeleteAsync.mock.funcDeleteAsync = f
	mmDeleteAsync.mock.funcDeleteAsyncOrigin = minimock.CallerInfo(1)
	return mmDeleteAsync.mock
}

// When sets expectation for the UrlsKeeper.DeleteAsync which will trigger the result defined by the following
// Then helper
func (mmDeleteAsync *mUrlsKeeperMockDeleteAsync) When(ctx context.Context, userID string, shortURLs []string) *UrlsKeeperMockDeleteAsyncExpectation {
	if mmDeleteAsync.mock.funcDeleteAsync != nil {
		mmDeleteAsync.mock.t.Fatalf("UrlsKeeperMock.DeleteAsync mock is already set by Set")
	}

	expectation := &UrlsKeeperMockDeleteAsyncExpectation{
		mock:               mmDeleteAsync.mock,
		params:             &UrlsKeeperMockDeleteAsyncParams{ctx, userID, shortURLs},
		expectationOrigins: UrlsKeeperMockDeleteAsyncExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmDeleteAsync.expectations = append(mmDeleteAsync.expectations, expectation)
	return expectation
}

// Then sets up UrlsKeeper.DeleteAsync return parameters for the expectation previously defined by the When method

func (e *UrlsKeeperMockDeleteAsyncExpectation) Then() *UrlsKeeperMock {
	return e.mock
}

// Times sets number of times UrlsKeeper.DeleteAsync should be invoked
func (mmDeleteAsync *mUrlsKeeperMockDeleteAsync) Times(n uint64) *mUrlsKeeperMockDeleteAsync {
	if n == 0 {
		mmDeleteAsync.mock.t.Fatalf("Times of UrlsKeeperMock.DeleteAsync mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmDeleteAsync.expectedInvocations, n)
	mmDeleteAsync.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmDeleteAsync
}

func (mmDeleteAsync *mUrlsKeeperMockDeleteAsync) invocationsDone() bool {
	if len(mmDeleteAsync.expectations) == 0 && mmDeleteAsync.defaultExpectation == nil && mmDeleteAsync.mock.funcDeleteAsync == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmDeleteAsync.mock.afterDeleteAsyncCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmDeleteAsync.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// DeleteAsync implements mm_deleteuserurlshandler.UrlsKeeper
func (mmDeleteAsync *UrlsKeeperMock) DeleteAsync(ctx context.Context, userID string, shortURLs []string) {
	mm_atomic.AddUint64(&mmDeleteAsync.beforeDeleteAsyncCounter, 1)
	defer mm_atomic.AddUint64(&mmDeleteAsync.afterDeleteAsyncCounter, 1)

	mmDeleteAsync.t.Helper()

	if mmDeleteAsync.inspectFuncDeleteAsync != nil {
		mmDeleteAsync.inspectFuncDeleteAsync(ctx, userID, shortURLs)
	}

	mm_params := UrlsKeeperMockDeleteAsyncParams{ctx, userID, shortURLs}

	// Record call args
	mmDeleteAsync.DeleteAsyncMock.mutex.Lock()
	mmDeleteAsync.DeleteAsyncMock.callArgs = append(mmDeleteAsync.DeleteAsyncMock.callArgs, &mm_params)
	mmDeleteAsync.DeleteAsyncMock.mutex.Unlock()

	for _, e := range mmDeleteAsync.DeleteAsyncMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return
		}
	}

	if mmDeleteAsync.DeleteAsyncMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmDeleteAsync.DeleteAsyncMock.defaultExpectation.Counter, 1)
		mm_want := mmDeleteAsync.DeleteAsyncMock.defaultExpectation.params
		mm_want_ptrs := mmDeleteAsync.DeleteAsyncMock.defaultExpectation.paramPtrs

		mm_got := UrlsKeeperMockDeleteAsyncParams{ctx, userID, shortURLs}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmDeleteAsync.t.Errorf("UrlsKeeperMock.DeleteAsync got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDeleteAsync.DeleteAsyncMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.userID != nil && !minimock.Equal(*mm_want_ptrs.userID, mm_got.userID) {
				mmDeleteAsync.t.Errorf("UrlsKeeperMock.DeleteAsync got unexpected parameter userID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDeleteAsync.DeleteAsyncMock.defaultExpectation.expectationOrigins.originUserID, *mm_want_ptrs.userID, mm_got.userID, minimock.Diff(*mm_want_ptrs.userID, mm_got.userID))
			}

			if mm_want_ptrs.shortURLs != nil && !minimock.Equal(*mm_want_ptrs.shortURLs, mm_got.shortURLs) {
				mmDeleteAsync.t.Errorf("UrlsKeeperMock.DeleteAsync got unexpected parameter shortURLs, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDeleteAsync.DeleteAsyncMock.defaultExpectation.expectationOrigins.originShortURLs, *mm_want_ptrs.shortURLs, mm_got.shortURLs, minimock.Diff(*mm_want_ptrs.shortURLs, mm_got.shortURLs))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmDeleteAsync.t.Errorf("UrlsKeeperMock.DeleteAsync got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmDeleteAsync.DeleteAsyncMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		return

	}
	if mmDeleteAsync.funcDeleteAsync != nil {
		mmDeleteAsync.funcDeleteAsync(ctx, userID, shortURLs)
		return
	}
	mmDeleteAsync.t.Fatalf("Unexpected call to UrlsKeeperMock.DeleteAsync. %v %v %v", ctx, userID, shortURLs)

}

// DeleteAsyncAfterCounter returns a count of finished UrlsKeeperMock.DeleteAsync invocations
func (mmDeleteAsync *UrlsKeeperMock) DeleteAsyncAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDeleteAsync.afterDeleteAsyncCounter)
}

// DeleteAsyncBeforeCounter returns a count of UrlsKeeperMock.DeleteAsync invocations
func (mmDeleteAsync *UrlsKeeperMock) DeleteAsyncBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDeleteAsync.beforeDeleteAsyncCounter)
}

// Calls returns a list of arguments used in each call to UrlsKeeperMock.DeleteAsync.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmDeleteAsync *mUrlsKeeperMockDeleteAsync) Calls() []*UrlsKeeperMockDeleteAsyncParams {
	mmDeleteAsync.mutex.RLock()

	argCopy := make([]*UrlsKeeperMockDeleteAsyncParams, len(mmDeleteAsync.callArgs))
	copy(argCopy, mmDeleteAsync.callArgs)

	mmDeleteAsync.mutex.RUnlock()

	return argCopy
}

// MinimockDeleteAsyncDone returns true if the count of the DeleteAsync invocations corresponds
// the number of defined expectations
func (m *UrlsKeeperMock) MinimockDeleteAsyncDone() bool {
	if m.DeleteAsyncMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.DeleteAsyncMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.DeleteAsyncMock.invocationsDone()
}

// MinimockDeleteAsyncInspect logs each unmet expectation
func (m *UrlsKeeperMock) MinimockDeleteAsyncInspect() {
	for _, e := range m.DeleteAsyncMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UrlsKeeperMock.DeleteAsync at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterDeleteAsyncCounter := mm_atomic.LoadUint64(&m.afterDeleteAsyncCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.DeleteAsyncMock.defaultExpectation != nil && afterDeleteAsyncCounter < 1 {
		if m.DeleteAsyncMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to UrlsKeeperMock.DeleteAsync at\n%s", m.DeleteAsyncMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to UrlsKeeperMock.DeleteAsync at\n%s with params: %#v", m.DeleteAsyncMock.defaultExpectation.expectationOrigins.origin, *m.DeleteAsyncMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDeleteAsync != nil && afterDeleteAsyncCounter < 1 {
		m.t.Errorf("Expected call to UrlsKeeperMock.DeleteAsync at\n%s", m.funcDeleteAsyncOrigin)
	}

	if !m.DeleteAsyncMock.invocationsDone() && afterDeleteAsyncCounter > 0 {
		m.t.Errorf("Expected %d calls to UrlsKeeperMock.DeleteAsync at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.DeleteAsyncMock.expectedInvocations), m.DeleteAsyncMock.expectedInvocationsOrigin, afterDeleteAsyncCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *UrlsKeeperMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockDeleteAsyncInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *UrlsKeeperMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *UrlsKeeperMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockDeleteAsyncDone()
}
