// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

import (
	"net/http"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// AuthServiceMock implements mm_getshorturlbyjsonhandler.AuthService
type AuthServiceMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcSetAuthCookie          func(w http.ResponseWriter, userID string)
	funcSetAuthCookieOrigin    string
	inspectFuncSetAuthCookie   func(w http.ResponseWriter, userID string)
	afterSetAuthCookieCounter  uint64
	beforeSetAuthCookieCounter uint64
	SetAuthCookieMock          mAuthServiceMockSetAuthCookie
}

// NewAuthServiceMock returns a mock for mm_getshorturlbyjsonhandler.AuthService
func NewAuthServiceMock(t minimock.Tester) *AuthServiceMock {
	m := &AuthServiceMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.SetAuthCookieMock = mAuthServiceMockSetAuthCookie{mock: m}
	m.SetAuthCookieMock.callArgs = []*AuthServiceMockSetAuthCookieParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mAuthServiceMockSetAuthCookie struct {
	optional           bool
	mock               *AuthServiceMock
	defaultExpectation *AuthServiceMockSetAuthCookieExpectation
	expectations       []*AuthServiceMockSetAuthCookieExpectation

	callArgs []*AuthServiceMockSetAuthCookieParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// AuthServiceMockSetAuthCookieExpectation specifies expectation struct of the AuthService.SetAuthCookie
type AuthServiceMockSetAuthCookieExpectation struct {
	mock               *AuthServiceMock
	params             *AuthServiceMockSetAuthCookieParams
	paramPtrs          *AuthServiceMockSetAuthCookieParamPtrs
	expectationOrigins AuthServiceMockSetAuthCookieExpectationOrigins

	returnOrigin string
	Counter      uint64
}

// AuthServiceMockSetAuthCookieParams contains parameters of the AuthService.SetAuthCookie
type AuthServiceMockSetAuthCookieParams struct {
	w      http.ResponseWriter
	userID string
}

// AuthServiceMockSetAuthCookieParamPtrs contains pointers to parameters of the AuthService.SetAuthCookie
type AuthServiceMockSetAuthCookieParamPtrs struct {
	w      *http.ResponseWriter
	userID *string
}

// AuthServiceMockSetAuthCookieOrigins contains origins of expectations of the AuthService.SetAuthCookie
type AuthServiceMockSetAuthCookieExpectationOrigins struct {
	origin       string
	originW      string
	originUserID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmSetAuthCookie *mAuthServiceMockSetAuthCookie) Optional() *mAuthServiceMockSetAuthCookie {
	mmSetAuthCookie.optional = true
	return mmSetAuthCookie
}

// Expect sets up expected params for AuthService.SetAuthCookie
func (mmSetAuthCookie *mAuthServiceMockSetAuthCookie) Expect(w http.ResponseWriter, userID string) *mAuthServiceMockSetAuthCookie {
	if mmSetAuthCookie.mock.funcSetAuthCookie != nil {
		mmSetAuthCookie.mock.t.Fatalf("AuthServiceMock.SetAuthCookie mock is already set by Set")
	}

	if mmSetAuthCookie.defaultExpectation == nil {
		mmSetAuthCookie.defaultExpectation = &AuthServiceMockSetAuthCookieExpectation{}
	}

	if mmSetAuthCookie.defaultExpectation.paramPtrs != nil {
		mmSetAuthCookie.mock.t.Fatalf("AuthServiceMock.SetAuthCookie mock is already set by ExpectParams functions")
	}

	mmSetAuthCookie.defaultExpectation.params = &AuthServiceMockSetAuthCookieParams{w, userID}
	mmSetAuthCookie.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmSetAuthCookie.expectations {
		if minimock.Equal(e.params, mmSetAuthCookie.defaultExpectation.params) {
			mmSetAuthCookie.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSetAuthCookie.defaultExpectation.params)
		}
	}

	return mmSetAuthCookie
}

// ExpectWParam1 sets up expected param w for AuthService.SetAuthCookie
func (mmSetAuthCookie *mAuthServiceMockSetAuthCookie) ExpectWParam1(w http.ResponseWriter) *mAuthServiceMockSetAuthCookie {
	if mmSetAuthCookie.mock.funcSetAuthCookie != nil {
		mmSetAuthCookie.mock.t.Fatalf("AuthServiceMock.SetAuthCookie mock is already set by Set")
	}

	if mmSetAuthCookie.defaultExpectation == nil {
		mmSetAuthCookie.defaultExpectation = &AuthServiceMockSetAuthCookieExpectation{}
	}

	if mmSetAuthCookie.defaultExpectation.params != nil {
		mmSetAuthCookie.mock.t.Fatalf("AuthServiceMock.SetAuthCookie mock is already set by Expect")
	}

	if mmSetAuthCookie.defaultExpectation.paramPtrs == nil {
		mmSetAuthCookie.defaultExpectation.paramPtrs = &AuthServiceMockSetAuthCookieParamPtrs{}
	}
	mmSetAuthCookie.defaultExpectation.paramPtrs.w = &w
	mmSetAuthCookie.defaultExpectation.expectationOrigins.originW = minimock.CallerInfo(1)

	return mmSetAuthCookie
}

// ExpectUserIDParam2 sets up expected param userID for AuthService.SetAuthCookie
func (mmSetAuthCookie *mAuthServiceMockSetAuthCookie) ExpectUserIDParam2(userID string) *mAuthServiceMockSetAuthCookie {
	if mmSetAuthCookie.mock.funcSetAuthCookie != nil {
		mmSetAuthCookie.mock.t.Fatalf("AuthServiceMock.SetAuthCookie mock is already set by Set")
	}

	if mmSetAuthCookie.defaultExpectation == nil {
		mmSetAuthCookie.defaultExpectation = &AuthServiceMockSetAuthCookieExpectation{}
	}

	if mmSetAuthCookie.defaultExpectation.params != nil {
		mmSetAuthCookie.mock.t.Fatalf("AuthServiceMock.SetAuthCookie mock is already set by Expect")
	}

	if mmSetAuthCookie.defaultExpectation.paramPtrs == nil {
		mmSetAuthCookie.defaultExpectation.paramPtrs = &AuthServiceMockSetAuthCookieParamPtrs{}
	}
	mmSetAuthCookie.defaultExpectation.paramPtrs.userID = &userID
	mmSetAuthCookie.defaultExpectation.expectationOrigins.originUserID = minimock.CallerInfo(1)

	return mmSetAuthCookie
}

// Inspect accepts an inspector function that has same arguments as the AuthService.SetAuthCookie
func (mmSetAuthCookie *mAuthServiceMockSetAuthCookie) Inspect(f func(w http.ResponseWriter, userID string)) *mAuthServiceMockSetAuthCookie {
	if mmSetAuthCookie.mock.inspectFuncSetAuthCookie != nil {
		mmSetAuthCookie.mock.t.Fatalf("Inspect function is already set for AuthServiceMock.SetAuthCookie")
	}

	mmSetAuthCookie.mock.inspectFuncSetAuthCookie = f

	return mmSetAuthCookie
}

// Return sets up results that will be returned by AuthService.SetAuthCookie
func (mmSetAuthCookie *mAuthServiceMockSetAuthCookie) Return() *AuthServiceMock {
	if mmSetAuthCookie.mock.funcSetAuthCookie != nil {
		mmSetAuthCookie.mock.t.Fatalf("AuthServiceMock.SetAuthCookie mock is already set by Set")
	}

	if mmSetAuthCookie.defaultExpectation == nil {
		mmSetAuthCookie.defaultExpectation = &AuthServiceMockSetAuthCookieExpectation{mock: mmSetAuthCookie.mock}
	}

	mmSetAuthCookie.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmSetAuthCookie.mock
}

// Set uses given function f to mock the AuthService.SetAuthCookie method
func (mmSetAuthCookie *mAuthServiceMockSetAuthCookie) Set(f func(w http.ResponseWriter, userID string)) *AuthServiceMock {
	if mmSetAuthCookie.defaultExpectation != nil {
		mmSetAuthCookie.mock.t.Fatalf("Default expectation is already set for the AuthService.SetAuthCookie method")
	}

	if len(mmSetAuthCookie.expectations) > 0 {
		mmSetAuthCookie.mock.t.Fatalf("Some expectations are already set for the AuthService.SetAuthCookie method")
	}

	mmSetAuthCookie.mock.funcSetAuthCookie = f
	mmSetAuthCookie.mock.funcSetAuthCookieOrigin = minimock.CallerInfo(1)
	return mmSetAuthCookie.mock
}

// When sets expectation for the AuthService.SetAuthCookie which will trigger the result defined by the following
// Then helper
func (mmSetAuthCookie *mAuthServiceMockSetAuthCookie) When(w http.ResponseWriter, userID string) *AuthServiceMockSetAuthCookieExpectation {
	if mmSetAuthCookie.mock.funcSetAuthCookie != nil {
		mmSetAuthCookie.mock.t.Fatalf("AuthServiceMock.SetAuthCookie mock is already set by Set")
	}

	expectation := &AuthServiceMockSetAuthCookieExpectation{
		mock:               mmSetAuthCookie.mock,
		params:             &AuthServiceMockSetAuthCookieParams{w, userID},
		expectationOrigins: AuthServiceMockSetAuthCookieExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmSetAuthCookie.expectations = append(mmSetAuthCookie.expectations, expectation)
	return expectation
}

// Then sets up AuthService.SetAuthCookie return parameters for the expectation previously defined by the When method

func (e *AuthServiceMockSetAuthCookieExpectation) Then() *AuthServiceMock {
	return e.mock
}

// Times sets number of times AuthService.SetAuthCookie should be invoked
func (mmSetAuthCookie *mAuthServiceMockSetAuthCookie) Times(n uint64) *mAuthServiceMockSetAuthCookie {
	if n == 0 {
		mmSetAuthCookie.mock.t.Fatalf("Times of AuthServiceMock.SetAuthCookie mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmSetAuthCookie.expectedInvocations, n)
	mmSetAuthCookie.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmSetAuthCookie
}

func (mmSetAuthCookie *mAuthServiceMockSetAuthCookie) invocationsDone() bool {
	if len(mmSetAuthCookie.expectations) == 0 && mmSetAuthCookie.defaultExpectation == nil && mmSetAuthCookie.mock.funcSetAuthCookie == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmSetAuthCookie.mock.afterSetAuthCookieCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmSetAuthCookie.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// SetAuthCookie implements mm_getshorturlbyjsonhandler.AuthService
func (mmSetAuthCookie *AuthServiceMock) SetAuthCookie(w http.ResponseWriter, userID string) {
	mm_atomic.AddUint64(&mmSetAuthCookie.beforeSetAuthCookieCounter, 1)
	defer mm_atomic.AddUint64(&mmSetAuthCookie.afterSetAuthCookieCounter, 1)

	mmSetAuthCookie.t.Helper()

	if mmSetAuthCookie.inspectFuncSetAuthCookie != nil {
		mmSetAuthCookie.inspectFuncSetAuthCookie(w, userID)
	}

	mm_params := AuthServiceMockSetAuthCookieParams{w, userID}

	// Record call args
	mmSetAuthCookie.SetAuthCookieMock.mutex.Lock()
	mmSetAuthCookie.SetAuthCookieMock.callArgs = append(mmSetAuthCookie.SetAuthCookieMock.callArgs, &mm_params)
	mmSetAuthCookie.SetAuthCookieMock.mutex.Unlock()

	for _, e := range mmSetAuthCookie.SetAuthCookieMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return
		}
	}

	if mmSetAuthCookie.SetAuthCookieMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSetAuthCookie.SetAuthCookieMock.defaultExpectation.Counter, 1)
		mm_want := mmSetAuthCookie.SetAuthCookieMock.defaultExpectation.params
		mm_want_ptrs := mmSetAuthCookie.SetAuthCookieMock.defaultExpectation.paramPtrs

		mm_got := AuthServiceMockSetAuthCookieParams{w, userID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.w != nil && !minimock.Equal(*mm_want_ptrs.w, mm_got.w) {
				mmSetAuthCookie.t.Errorf("AuthServiceMock.SetAuthCookie got unexpected parameter w, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSetAuthCookie.SetAuthCookieMock.defaultExpectation.expectationOrigins.originW, *mm_want_ptrs.w, mm_got.w, minimock.Diff(*mm_want_ptrs.w, mm_got.w))
			}

			if mm_want_ptrs.userID != nil && !minimock.Equal(*mm_want_ptrs.userID, mm_got.userID) {
				mmSetAuthCookie.t.Errorf("AuthServiceMock.SetAuthCookie got unexpected parameter userID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSetAuthCookie.SetAuthCookieMock.defaultExpectation.expectationOrigins.originUserID, *mm_want_ptrs.userID, mm_got.userID, minimock.Diff(*mm_want_ptrs.userID, mm_got.userID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSetAuthCookie.t.Errorf("AuthServiceMock.SetAuthCookie got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmSetAuthCookie.SetAuthCookieMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		return

	}
	if mmSetAuthCookie.funcSetAuthCookie != nil {
		mmSetAuthCookie.funcSetAuthCookie(w, userID)
		return
	}
	mmSetAuthCookie.t.Fatalf("Unexpected call to AuthServiceMock.SetAuthCookie. %v %v", w, userID)

}

// SetAuthCookieAfterCounter returns a count of finished AuthServiceMock.SetAuthCookie invocations
func (mmSetAuthCookie *AuthServiceMock) SetAuthCookieAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSetAuthCookie.afterSetAuthCookieCounter)
}

// SetAuthCookieBeforeCounter returns a count of AuthServiceMock.SetAuthCookie invocations
func (mmSetAuthCookie *AuthServiceMock) SetAuthCookieBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSetAuthCookie.beforeSetAuthCookieCounter)
}

// Calls returns a list of arguments used in each call to AuthServiceMock.SetAuthCookie.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSetAuthCookie *mAuthServiceMockSetAuthCookie) Calls() []*AuthServiceMockSetAuthCookieParams {
	mmSetAuthCookie.mutex.RLock()

	argCopy := make([]*AuthServiceMockSetAuthCookieParams, len(mmSetAuthCookie.callArgs))
	copy(argCopy, mmSetAuthCookie.callArgs)

	mmSetAuthCookie.mutex.RUnlock()

	return argCopy
}

// MinimockSetAuthCookieDone returns true if the count of the SetAuthCookie invocations corresponds
// the number of defined expectations
func (m *AuthServiceMock) MinimockSetAuthCookieDone() bool {
	if m.SetAuthCookieMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.SetAuthCookieMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.SetAuthCookieMock.invocationsDone()
}

// MinimockSetAuthCookieInspect logs each unmet expectation
func (m *AuthServiceMock) MinimockSetAuthCookieInspect() {
	for _, e := range m.SetAuthCookieMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to AuthServiceMock.SetAuthCookie at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterSetAuthCookieCounter := mm_atomic.LoadUint64(&m.afterSetAuthCookieCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.SetAuthCookieMock.defaultExpectation != nil && afterSetAuthCookieCounter < 1 {
		if m.SetAuthCookieMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to AuthServiceMock.SetAuthCookie at\n%s", m.SetAuthCookieMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to AuthServiceMock.SetAuthCookie at\n%s with params: %#v", m.SetAuthCookieMock.defaultExpectation.expectationOrigins.origin, *m.SetAuthCookieMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSetAuthCookie != nil && afterSetAuthCookieCounter < 1 {
		m.t.Errorf("Expected call to AuthServiceMock.SetAuthCookie at\n%s", m.funcSetAuthCookieOrigin)
	}

	if !m.SetAuthCookieMock.invocationsDone() && afterSetAuthCookieCounter > 0 {
		m.t.Errorf("Expected %d calls to AuthServiceMock.SetAuthCookie at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.SetAuthCookieMock.expectedInvocations), m.SetAuthCookieMock.expectedInvocationsOrigin, afterSetAuthCookieCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *AuthServiceMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockSetAuthCookieInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *AuthServiceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *AuthServiceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockSetAuthCookieDone()
}
